type Topic={slug:string;title:string;excerpt:string;task:string;inputs:string;fields:string;owner:string;stop:string;example:string;image:string};

const topics:readonly Topic[]=[
 {slug:'offshore-legal-support-discovery-production-receipt-reconciliation',title:'Reconciling discovery production receipts with offshore legal support',excerpt:'Match approved production packages to transfer and receipt evidence while discovery counsel controls scope and sufficiency.',task:'discovery production receipt reconciliation',inputs:'the counsel-approved production manifest, transfer log, recipient acknowledgment, exception messages, and current instruction',fields:'production identifier, manifest count, transfer event, receipt event, stated difference, evidence link, owner, and disposition',owner:'discovery counsel',stop:'counts differ, a package changes, receipt is missing, scope is questioned, or another transfer is proposed',example:'The transfer log shows 804 files while the approved manifest shows 803. Preserve both counts and route the difference; do not resend the package.',image:'/aug23-heroes/discovery-custodian-index.png'},
 {slug:'law-firm-offshore-signature-page-return-register',title:'A signature-page return register for law firm offshore teams',excerpt:'Track requested and returned signature pages without deciding authority, execution, completeness, or legal effect.',task:'signature-page return registration',inputs:'the lawyer-approved signature request, recipient list, document version, returned page, transmission evidence, and reviewer instruction',fields:'signer label, request version, sent time, return source, displayed signature state, page reference, exception, and reviewer',owner:'transaction counsel',stop:'identity is unclear, a page belongs to another version, a signature is incomplete, authority is questioned, or assembly is requested',example:'A returned page has the expected title but no document identifier. Keep it separate and ask counsel which version, if any, it belongs to.',image:'/sep3-heroes/board-consent-signature-collection-tracker.png'},
 {slug:'offshore-legal-support-subpoena-response-materials-inventory',title:'Inventorying subpoena response materials with offshore legal support',excerpt:'Create a source-linked materials inventory while counsel decides objections, responsiveness, privilege, and production.',task:'subpoena response materials inventorying',inputs:'the attorney-defined request list, approved collection locations, supplied files, custodian labels, and review protocol',fields:'request label, source location, filename, custodian as supplied, received date, review state, exception, and counsel disposition',owner:'the supervising litigation lawyer',stop:'scope is uncertain, privileged material may appear, a custodian changes, a deadline must be calculated, or production is proposed',example:'A folder label names one custodian while its manifest names another. Record both source labels without choosing the correct identity.',image:'/sep3-heroes/subpoena-witness-fee-disbursement-worksheet.png'},
 {slug:'law-firm-offshore-lease-document-version-index',title:'Lease document version indexes for supervised offshore support',excerpt:'Keep lease drafts, exhibits, and comparison bases traceable while real-estate counsel controls interpretation and negotiation.',task:'lease document version indexing',inputs:'the counsel-supplied lease set, email history, comparison base, exhibit list, filenames, and drafting instruction',fields:'document identifier, displayed version, sender, received time, comparison base, attached exhibits, open question, and reviewer',owner:'real-estate counsel',stop:'two files claim to be final, exhibits conflict, language needs interpretation, a party changes, or a draft would be circulated',example:'Two drafts share a filename but have different page counts. Retain each original, record its message source, and do not label either operative.',image:'/sep3-heroes/lease-abstraction-source-note-register.png'},
 {slug:'offshore-legal-support-corporate-minute-book-gap-log',title:'Corporate minute-book gap logs for offshore legal support',excerpt:'Record missing and conflicting corporate records while corporate counsel decides validity, completeness, and remediation.',task:'corporate minute-book gap logging',inputs:'the approved minute-book index, supplied resolutions, minutes, registers, certificates, and counsel instruction',fields:'record category, stated period, source filename, visible date, referenced attachment, observed gap, owner, and disposition',owner:'corporate counsel',stop:'a record is missing, dates conflict, execution is unclear, reconstruction is proposed, or corporate status must be stated',example:'Minutes refer to an exhibit that is not in the supplied folder. Log the reference and missing exhibit without recreating it.',image:'/aug23-heroes/matter-closeout-records.png'},
 {slug:'law-firm-offshore-medical-records-provider-response-log',title:'Provider response logs for medical-records collection support',excerpt:'Track approved requests and provider responses without assessing completeness, causation, damages, or medical meaning.',task:'medical-records provider response logging',inputs:'the approved provider list, request copy, delivery evidence, provider correspondence, received package, and attorney instruction',fields:'provider label, request date, delivery event, response date, package reference, stated gap, next owner, and disposition',owner:'the matter attorney',stop:'authorization is questioned, scope changes, clinical interpretation is needed, a deadline must be calculated, or new outreach is proposed',example:'A provider says records are complete through June, while the request names July. Record both date ranges and route the scope difference.',image:'/sep3-heroes/litigation-medical-records-chronology-intake.png'},
 {slug:'offshore-legal-support-trademark-renewal-source-packet',title:'Preparing trademark renewal source packets with offshore support',excerpt:'Assemble registration and instruction sources while trademark counsel controls deadlines, declarations, and filing decisions.',task:'trademark renewal source-packet preparation',inputs:'the attorney-approved portfolio list, registration records, owner information, specimen files, docket entry, and filing instruction',fields:'mark label, registration identifier, jurisdiction, source date, owner as displayed, specimen reference, discrepancy, and reviewer',owner:'trademark counsel',stop:'ownership differs, a deadline needs calculation, use must be characterized, a declaration is needed, or a filing would be submitted',example:'The docket and supplied registration show different owner punctuation. Preserve the exact strings and their source dates for counsel.',image:'/sep3-heroes/trademark-specimen-intake-inventory.png'},
 {slug:'law-firm-offshore-legal-bill-guideline-checklist',title:'Legal-bill guideline checklists for offshore support teams',excerpt:'Check invoice packages against firm-supplied administrative rules while lawyers and finance retain approval and adjustment decisions.',task:'legal-bill guideline checking',inputs:'the approved billing guidelines, invoice, time-detail export, matter code list, expense support, and reviewer instruction',fields:'invoice identifier, rule reference, line reference, observed condition, support link, question, owner, and disposition',owner:'the billing lawyer and authorized finance owner',stop:'a rule requires interpretation, privilege may be exposed, rates conflict, an adjustment is proposed, or payment is requested',example:'A narrative uses a blocked phrase but may quote a court order. Flag the line and rule; do not rewrite or reject it.',image:'/aug23-heroes/billing-exception-queues.png'},
 {slug:'offshore-legal-support-court-filing-confirmation-packet',title:'Court filing confirmation packets for supervised offshore support',excerpt:'Connect counsel-approved filings to portal events and receipts while authorized lawyers control filing substance and response.',task:'court filing confirmation packet preparation',inputs:'the approved filing copy, written submission instruction, portal event, payment record, stamped copy, and court message',fields:'matter label, filing version, submitter, portal time, confirmation identifier, stamped-copy link, exception, and reviewer',owner:'the filing attorney',stop:'the portal rejects a field, versions differ, fees change, timing is uncertain, or corrective filing is proposed',example:'The receipt names the expected filing but the stamped copy is absent. Keep the receipt and mark the missing artifact for the filing attorney.',image:'/aug21-heroes/legal-support-offshore-court-message-register.png'},
 {slug:'law-firm-offshore-data-room-access-request-ledger',title:'Data-room access request ledgers for law firm offshore teams',excerpt:'Preserve requests, approvals, and observed access states while deal counsel and system owners control entitlement.',task:'data-room access request logging',inputs:'the approved participant list, access request, owner approval, platform event, role description, and removal instruction',fields:'person as supplied, organization, requested role, approval link, invite event, observed state, expiry or removal event, and exception',owner:'deal counsel and the authorized data-room owner',stop:'identity differs, approval is absent, permissions exceed the request, content is unexpectedly visible, or access would be changed',example:'An invite shows a viewer role, but the interface presents download controls. Record the observed capability without testing a download.',image:'/aug23-heroes/privileged-folder-permissions.png'},
 {slug:'offshore-legal-support-client-update-source-check',title:'Source checks for client-update drafts in offshore legal support',excerpt:'Link each supplied status statement to approved evidence while counsel controls interpretation, tone, promises, and release.',task:'client-update source checking',inputs:'the lawyer-approved update outline, matter-status sources, task records, correspondence, decision notes, and current instruction',fields:'draft statement, cited source, source time, observed support, unresolved gap, proposed owner question, reviewer, and release state',owner:'the responsible lawyer',stop:'sources conflict, a conclusion is implied, strategy appears, a promise is proposed, or the update would be sent',example:'The draft says discovery is complete while the tracker has an open exception. Link both items and ask counsel; do not edit the status to resolve it.',image:'/aug23-heroes/client-update-digests.png'},
 {slug:'law-firm-offshore-matter-closeout-return-checklist',title:'Matter-closeout return checklists for offshore legal support',excerpt:'Document return, transfer, access removal, and retention evidence while the firm decides final disposition.',task:'matter-closeout return checking',inputs:'the firm-approved closeout instruction, matter inventory, transfer receipts, access list, retention schedule, and owner decisions',fields:'asset or access label, source location, required action, event evidence, completion time, exception, owner, and disposition',owner:'the records lawyer or authorized matter manager',stop:'retention is unclear, legal hold may apply, ownership is disputed, deletion is proposed, or evidence of return is missing',example:'A shared folder is empty but the access list still names an external user. Record both states and route removal to the authorized system owner.',image:'/research-heroes/aug23-closeout-evidence.png'},
];

const sections=(t:Topic,i:number)=>[
 {heading:`Define the ${t.task} lane`,body:`Published September 8, 2026. Give this routine the identifier S8-${String(i+1).padStart(2,'0')} and name ${t.owner} before work starts. Offshore support may prepare an administrative record from approved material. Legal analysis, advice, approval, and external release stay with the firm.`},
 {heading:'Use a closed source set',body:`Work only from ${t.inputs}. Record the location, visible version, and access time for each input. Do not search for substitute evidence or repair a mismatch silently. Missing material remains an explicit exception.`},
 {heading:'Build a reproducible record',body:`Capture ${t.fields}. Use neutral language that another authorized reviewer can trace back to the same source. Keep prior values when a later instruction changes the record so the sequence remains reviewable.`},
 {heading:'Treat the awkward case as evidence',body:`${t.example} The point is not to make the tracker look complete. It is to preserve what was observed, identify the narrow uncertainty, and place the decision with ${t.owner}.`},
 {heading:'Apply the stop rule',body:`Pause when ${t.stop}. Send the relevant source references, the observed difference, and one precise question to ${t.owner}. Prepared, reviewed, approved, and released must remain separate states.`},
 {heading:'Pilot the routine',body:`Test a small batch containing ordinary items and at least one known exception. Review source selection, version control, field accuracy, access scope, escalation speed, and disposition evidence separately. Do not turn the sample into a universal accuracy claim.`},
 {heading:'Protect client information',body:`Use named accounts, matter-limited permissions, approved devices, and firm-approved transfer paths. Prefer links and identifiers over copied sensitive text. If information appears in the wrong location or reaches an unexpected recipient, stop and use the firm's incident process.`},
 {heading:'Close with an attributable decision',body:`Close only after ${t.owner} records a disposition and any correction links back to the earlier observation. Remove temporary access when instructed and retain records under firm policy. Recheck the routine whenever its system, source, instruction, reviewer, or client requirement changes.`},
];

export const september8BlogPosts=topics.map((topic,index)=>({slug:topic.slug,title:topic.title,excerpt:topic.excerpt,published:'2026-09-08' as const,modified:'2026-09-08',minutes:8,featuredImage:topic.image,sections:sections(topic,index)}));
