type Section = { heading: string; body: string };

export const august18ReplacementBlogPost = {
  slug: 'offshore-legal-support-client-document-request-review-packet',
  title: 'Building a review packet for offshore legal document requests',
  excerpt: 'Turn a document request into a reviewable packet of instructions, sources, gaps, and follow-up history while the firm keeps legal judgment.',
  minutes: 10,
  published: '2026-08-18' as const,
  sourceDate: '2026-08-18' as const,
  sections: [
    { heading: 'Begin with the request as received', body: 'A document-request packet should begin with the firm-approved request, not with a summary written from memory. Record the matter identifier, requestor, recipient, date sent, requested period, delivery channel, and the exact source location. Keep the original request available beside the working checklist. If the request was amended, retain the earlier version and identify which instruction is current according to the named firm reviewer. Offshore legal support can make this administrative trail easier to inspect, but it should not decide what a request legally means or silently rewrite an unclear sentence. When a field is missing, mark it missing. When two instructions differ, show both and ask the designated reviewer which one controls. That habit prevents a polished packet from concealing an unresolved instruction.' },
    { heading: 'Design the packet around reviewer questions', body: 'The useful unit is not simply a folder of received files. It is a packet that lets a lawyer or matter owner answer predictable questions: what was requested, what arrived, when did it arrive, where did it come from, what appears incomplete, and what decision is needed? Create an index with one row per requested item or clearly defined sub-item. Include the request wording, source filename, received timestamp, page or file count where available, apparent coverage, and open question. Use neutral labels such as received, partially received, unreadable, not found in supplied material, or awaiting clarification. Avoid labels that imply legal sufficiency, compliance, responsiveness, or privilege unless an authorized reviewer supplied that conclusion.' },
    { heading: 'Separate source evidence from working notes', body: 'A review packet becomes unreliable when observations and source text are mixed together. Preserve the original email, portal message, attachment, or file in its received form according to the firm’s retention and access rules. Put administrative observations in a separate field or companion note. For example, “file contains three pages” is an observable record; “file proves the requested event” is a legal or factual conclusion that may require review. Record the source name exactly, including unusual punctuation or version markings, and link duplicate-looking files rather than overwriting one with another. If a file cannot be opened, say that plainly and identify the attempted location. The support worker’s job is to make the evidence and the gap visible, not to make the gap disappear.' },
    { heading: 'Handle substitutions and partial responses carefully', body: 'Clients and counterparties may send a substitute document, a screenshot, a later version, or a response that addresses only part of a request. The packet should preserve the relationship between the original request and the material received. Add a response-status field that distinguishes “different item supplied” from “requested item received.” Record the sender’s description and the date received, then route the question to the firm: should the substitute be accepted for review, should the original request be repeated, or should the scope be clarified? Offshore support may prepare a draft follow-up using approved wording, but it should not tell a client that the substitute is adequate or promise that no further material is needed. A clear exception is more useful than an unsupported completion mark.' },
    { heading: 'Make follow-up history auditable', body: 'Every reminder should be tied to an approved instruction and a specific unresolved item. Record the date, channel, recipient, wording source, sender authorized by the firm, and result. If there is no response, record that fact without guessing why. If the recipient asks a question about legal scope, urgency, confidentiality, or what will satisfy the matter, stop and escalate the question. A compact follow-up table helps the reviewer see whether the same item has been requested twice, whether a promised delivery date passed, or whether a new message changes the record. Do not treat repeated reminders as proof that the request is urgent or legally enforceable. Those decisions belong to counsel or the matter owner.' },
    { heading: 'Build confidentiality into the handoff', body: 'Document requests often contain personal, financial, medical, employment, or commercially sensitive material. The packet should use the firm’s approved matter location, named accounts, least-access permissions, and defined transfer method. Do not copy files into a personal workspace simply to make indexing convenient. Keep source documents and review notes distinct, and use redacted training examples when teaching the workflow. Record access or transfer exceptions for the responsible firm contact rather than attempting an informal fix. The offshore location does not itself answer the firm’s confidentiality, supervision, retention, or contractual questions. Those controls must be set by the firm with appropriate professional advice. A safe packet makes it clear who can view the source, who reviewed the preparation, and what remains restricted.' },
    { heading: 'Use a bounded quality check and closeout', body: 'Before handoff, compare the packet against the approved request and check that every requested line has a status, every received file has a source reference, every gap has an explanation, and every open question has an owner. Sample the links and filenames, verify that dates were copied accurately, and confirm that the packet does not contain unsupported conclusions. The reviewer decides whether the packet is ready for substantive use, needs more collection, or should be closed with an unresolved gap. Closeout should record the disposition, reviewer, date, remaining questions, and any authorized follow-up. This is the practical role of offshore legal support: disciplined preparation that reduces administrative friction while leaving legal interpretation, advice, strategy, and final communication with the firm. A repeatable packet structure can then be improved from real review questions without pretending that administrative completeness equals legal adequacy.' }
  ]
};
