type Topic = { slug:string; title:string; excerpt:string; work:string; inputs:string; output:string; owner:string; stop:string; image:string };

const topics: readonly Topic[] = [
  {slug:'offshore-legal-support-demand-letter-attachment-index',title:'Demand-letter attachment indexes with offshore legal support',excerpt:'Build a source-linked attachment index while counsel controls the demand, legal position, recipients, and release.',work:'demand-letter attachment indexing',inputs:'the counsel-approved draft, attachment list, source folder, recipient instruction, and version record',output:'an index connecting every listed attachment to its filename, source path, version, page count, and review state',owner:'the responsible attorney',stop:'an attachment is missing, a version differs, a recipient changes, or relevance must be decided',image:'/sep3-heroes/regulatory-comment-letter-source-packet.png'},
  {slug:'law-firm-offshore-court-order-obligation-register',title:'Court-order obligation registers for offshore legal support',excerpt:'Record attorney-approved obligations and source passages without interpreting an order or calculating deadlines.',work:'court-order obligation registration',inputs:'the entered order, docket record, attorney-marked provisions, approved fields, and matter instruction',output:'a register linking each supplied obligation field to the order, page, passage, named owner, and status',owner:'the supervising litigation attorney',stop:'language is ambiguous, dates depend on a legal trigger, orders conflict, or compliance must be judged',image:'/sep3-heroes/deposition-errata-return-tracker.png'},
  {slug:'offshore-legal-support-data-room-access-request-log',title:'Data-room access request logs with offshore legal support',excerpt:'Track approved access requests and evidence while firm owners decide entitlement, scope, and removal.',work:'data-room access request logging',inputs:'the approved participant list, request ticket, matter role, folder map, authorization, and platform event',output:'a log of requester, stated purpose, requested folder, approving owner, system event, exception, and removal state',owner:'the deal attorney or data-room administrator',stop:'identity differs, scope expands, approval is absent, a restricted folder appears, or access persists unexpectedly',image:'/sep3-heroes/board-consent-signature-collection-tracker.png'},
  {slug:'law-firm-offshore-insurance-policy-document-inventory',title:'Insurance-policy document inventories with offshore legal support',excerpt:'Inventory supplied policies, endorsements, and notices while lawyers control coverage analysis and legal conclusions.',work:'insurance-policy document inventory preparation',inputs:'the supplied policy set, declarations, endorsements, notices, claim correspondence, and counsel taxonomy',output:'an inventory preserving document identity, policy reference, visible period, endorsement link, source, and gap',owner:'coverage counsel or the designated matter attorney',stop:'forms conflict, a schedule is missing, dates require interpretation, or coverage must be characterized',image:'/sep3-heroes/lease-abstraction-source-note-register.png'},
  {slug:'offshore-legal-support-closing-signature-page-matrix',title:'Closing signature-page matrices with offshore legal support',excerpt:'Match approved signature pages to document versions while transaction counsel controls authority and closing.',work:'closing signature-page matching',inputs:'the counsel-approved document set, signer list, entity record, returned pages, signature-platform events, and closing instruction',output:'a matrix showing document version, signer, returned page, source event, observed mismatch, and reviewer disposition',owner:'transaction counsel or the closing coordinator',stop:'authority is uncertain, versions differ, a page lacks context, a signer changes, or release is requested',image:'/sep3-heroes/settlement-document-execution-status-board.png'},
  {slug:'law-firm-offshore-foia-production-receipt-register',title:'FOIA production receipt registers with offshore legal support',excerpt:'Log supplied productions and correspondence without deciding completeness, exemptions, appeal rights, or response strategy.',work:'FOIA production receipt registration',inputs:'the request copy, agency correspondence, production files, delivery event, supplied scope, and counsel instruction',output:'a receipt register of batches, filenames, visible dates, page counts, correspondence links, and unresolved gaps',owner:'the supervising attorney or records lead',stop:'a file is unreadable, a batch is missing, redactions need analysis, scope is disputed, or a response is proposed',image:'/sep3-heroes/legal-mail-service-proof-packet.png'},
  {slug:'offshore-legal-support-ip-license-royalty-report-index',title:'IP-license royalty report indexes with offshore legal support',excerpt:'Organize approved royalty reports and source references while counsel and finance retain interpretation and approval.',work:'IP-license royalty report indexing',inputs:'the executed license, approved reporting fields, period statement, supporting schedule, amendment set, and owner instruction',output:'an index linking every supplied report and schedule to period, version, source clause reference, exception, and review state',owner:'licensing counsel and the authorized finance owner',stop:'periods overlap, amendments conflict, a calculation is requested, supporting data is absent, or compliance must be decided',image:'/sep3-heroes/outside-counsel-guideline-exception-log.png'},
  {slug:'law-firm-offshore-immigration-evidence-receipt-ledger',title:'Immigration evidence receipt ledgers with offshore legal support',excerpt:'Record client-supplied evidence and gaps while authorized counsel decides relevance, sufficiency, and filing use.',work:'immigration evidence receipt logging',inputs:'the attorney-approved request list, client upload, identity reference, file metadata, translation status, and matter instruction',output:'a ledger of requested item, received artifact, source, visible date, file state, gap, and attorney disposition',owner:'the responsible immigration attorney',stop:'identities conflict, a translation is uncertain, a record is incomplete, a new request is needed, or filing use must be decided',image:'/sep3-heroes/litigation-medical-records-chronology-intake.png'},
  {slug:'offshore-legal-support-discovery-load-file-preflight',title:'Discovery load-file preflight with offshore legal support',excerpt:'Perform mechanical package checks while discovery counsel controls scope, responsiveness, privilege, and production release.',work:'discovery load-file preflight',inputs:'the approved export manifest, load file, image set, native-file directory, field specification, and counsel instruction',output:'a preflight record of counts, paths, delimiters, identifiers, missing references, test result, and review disposition',owner:'discovery counsel or the litigation technology lead',stop:'counts differ, identifiers repeat, files are absent, fields need interpretation, or the package would be released',image:'/sep3-heroes/expert-witness-conflict-intake-register.png'},
  {slug:'law-firm-offshore-probate-asset-document-register',title:'Probate asset document registers with offshore legal support',excerpt:'Index supplied asset records while counsel and fiduciaries control ownership, valuation, distribution, and legal treatment.',work:'probate asset document registration',inputs:'the approved estate inventory, supplied statements, title records, correspondence, valuation documents, and counsel categories',output:'a register of artifact, stated owner, visible date, identifier, source, category, uncertainty, and reviewer decision',owner:'probate counsel or the authorized fiduciary',stop:'ownership conflicts, values differ, an asset is newly disclosed, classification is unclear, or distribution is discussed',image:'/sep3-heroes/trademark-specimen-intake-inventory.png'},
  {slug:'offshore-legal-support-nda-return-status-tracker',title:'NDA return-status trackers with offshore legal support',excerpt:'Track approved NDA versions and return events while counsel controls terms, authority, acceptance, and disclosure.',work:'NDA return-status tracking',inputs:'the counsel-approved NDA, recipient list, circulation record, returned document, signature event, and version notice',output:'a status tracker linking each recipient to document version, delivery, return, signature state, exception, and owner review',owner:'commercial counsel or the designated contracts manager',stop:'terms change, a signer differs, pages are missing, authority is questioned, or information would be disclosed',image:'/sep3-heroes/mediation-logistics-confirmation-log.png'},
  {slug:'law-firm-offshore-appellate-citation-source-check',title:'Appellate citation source checks with offshore legal support',excerpt:'Compare attorney-selected citations with supplied sources while appellate counsel controls propositions and argument.',work:'appellate citation source checking',inputs:'the attorney-approved draft, cited authorities, record extracts, citation guide, source copies, and review instruction',output:'a check log recording citation location, source link, quoted text match, visible discrepancy, and reviewer disposition',owner:'the appellate attorney',stop:'a source is unavailable, the proposition needs analysis, authorities conflict, record meaning is uncertain, or text would be revised',image:'/sep3-heroes/regulatory-comment-letter-source-packet.png'},
];

const sections = (t:Topic, i:number) => [
  {heading:`Define ${t.work} in writing`,body:`Published September 4, 2026. Start with one named matter, a current instruction, and a narrow permission set. The brief should identify ${t.owner} as the reviewer and state that the support role may prepare factual records but may not make legal or client-facing decisions. Workflow ${i+1} should have its own identifier so a later reviewer can reconstruct the handoff without relying on memory.`},
  {heading:'Keep the source set visible',body:`Use only ${t.inputs}. Record the location and version of each input before extracting information. If two approved sources differ, preserve both and describe the difference plainly. Do not select the convenient version or search outside the authorized systems to fill a gap.`},
  {heading:'Prepare a reviewable record',body:`The expected work product is ${t.output}. Each entry needs an attributable source, preparer, observed state, open question, and next owner. A blank field should remain blank when the source does not answer it. Guessing makes a tidy record less trustworthy.`},
  {heading:'Stop at the decision boundary',body:`Stop when ${t.stop}. Route the source and one precise question to ${t.owner}. Keep prepared, reviewed, approved, and released as separate states. Administrative completion does not establish legal sufficiency, compliance, privilege, or authority.`},
  {heading:'Test a small first batch',body:`Use a closed or redacted example before live work, then review a small representative batch. Include ordinary items and at least one exception. Classify corrections by source, version, access, instruction, field, or decision boundary so the firm can repair the process instead of relying on a vague accuracy score.`},
  {heading:'Protect matter information',body:`Use named accounts, matter-limited folders, approved devices, and approved transfer channels. Keep client facts out of general coordination notes. Unexpected access, a wrong recipient, or material in an unapproved location should pause the task and enter the firm's incident or access-review path.`},
  {heading:'Close with owner evidence',body:`Close the item only after ${t.owner} records a disposition. Link corrections to the earlier observation instead of overwriting history. Remove temporary access when the assignment ends, retain only the evidence required by firm policy, and revisit the workflow when its system, source, client instruction, or risk changes.`},
];

export const september4BlogPosts = topics.map((topic,index)=>({slug:topic.slug,title:topic.title,excerpt:topic.excerpt,published:'2026-09-04' as const,modified:'2026-09-04',minutes:9,featuredImage:topic.image,sections:sections(topic,index)}));
