type Topic = {slug:string;title:string;excerpt:string;task:string;sources:string;record:string;reviewer:string;pause:string;image:string;detail:string};

const topics:readonly Topic[]=[
 {slug:'offshore-legal-support-litigation-hold-acknowledgment-log',title:'A practical litigation-hold acknowledgment log for offshore legal support',excerpt:'Track delivery and acknowledgment evidence without deciding who must receive a hold or whether preservation is adequate.',task:'litigation-hold acknowledgment tracking',sources:'the attorney-approved recipient list, issued notice, delivery events, acknowledgment replies, and current matter instruction',record:'recipient, notice version, sent time, delivery evidence, response state, follow-up owner, and reviewer note',reviewer:'the supervising litigation attorney',pause:'a recipient is absent, an address conflicts, the notice changes, delivery fails, or preservation advice is requested',image:'/aug21-heroes/offshore-legal-support-retention-hold-question-log.png',detail:'One recipient replies from a different address. Preserve both addresses and route the mismatch instead of merging the identities.'},
 {slug:'law-firm-offshore-deposition-exhibit-custody-register',title:'Building a deposition exhibit custody register with an offshore team',excerpt:'Keep exhibit source, version, movement, and return details visible while counsel controls selection and use.',task:'deposition exhibit custody registration',sources:'the counsel-selected exhibit set, source folder, exhibit labels, transfer receipts, session notes, and return instruction',record:'exhibit label, source filename, version, sender, recipient, transfer time, return state, and exception',reviewer:'deposition counsel',pause:'a label repeats, a file changes, custody evidence is missing, an exhibit is added, or use at the deposition must be decided',image:'/aug21-heroes/offshore-legal-support-hearing-record-ledger.png',detail:'A PDF labeled Exhibit 12 has a different page count from the approved source. Record the count difference and leave the approved file unchanged.'},
 {slug:'offshore-legal-support-contract-redline-receipt-ledger',title:'Contract redline receipt ledgers that keep versions straight',excerpt:'Log incoming redlines and their provenance while lawyers retain clause analysis, negotiation, and acceptance.',task:'contract redline receipt logging',sources:'the approved counterparty list, received message, attached redline, comparison copy, document identifier, and lawyer instruction',record:'sender, received time, filename, document version, comparison base, visible comments, assigned reviewer, and status',reviewer:'the responsible commercial lawyer',pause:'the sender is unexpected, attachments disagree, the base version is unclear, language needs interpretation, or a response is proposed',image:'/aug21-heroes/law-firm-offshore-support-amendment-notice-log.png',detail:'A counterparty sends two files called final. Keep both original filenames and message links; do not choose the operative draft.'},
 {slug:'law-firm-offshore-records-request-follow-up-docket',title:'A records-request follow-up docket for offshore legal support',excerpt:'Organize request, receipt, and follow-up facts without judging legal sufficiency or contacting a custodian without approval.',task:'records-request follow-up docketing',sources:'the approved request, recipient details, delivery proof, response correspondence, received files, and follow-up schedule',record:'request identifier, recipient, sent event, response event, supplied file set, stated gap, next owner, and authorized follow-up date',reviewer:'the matter attorney or records manager',pause:'scope is disputed, a recipient changes, protected material appears, a deadline needs calculation, or new outreach is needed',image:'/aug21-heroes/offshore-legal-support-evidence-request-matrix.png',detail:'The response refers to three attachments but contains two. Note the missing attachment exactly as observed and route the gap.'},
 {slug:'offshore-legal-support-entity-name-verification-worksheet',title:'Entity-name verification worksheets for transactional support',excerpt:'Compare supplied names across approved records while transaction counsel decides identity, authority, and drafting changes.',task:'entity-name verification',sources:'the lawyer-named entity record, formation document, good-standing record, signature block, closing list, and source date',record:'displayed name, source, jurisdiction field, visible identifier, source date, discrepancy, and reviewer disposition',reviewer:'transaction counsel',pause:'names or identifiers conflict, a source is stale, authority is uncertain, or any document text would be changed',image:'/aug21-heroes/legal-support-offshore-party-name-register.png',detail:'The formation record includes a comma that the signature block omits. Record the exact strings and sources without normalizing either one.'},
 {slug:'law-firm-offshore-privilege-review-batch-control-sheet',title:'Privilege-review batch control sheets with clear legal boundaries',excerpt:'Track supplied batches and review states while authorized lawyers make every privilege and production decision.',task:'privilege-review batch administration',sources:'the approved collection manifest, batch assignment, review protocol, platform counts, reviewer export, and counsel disposition',record:'batch identifier, assigned count, access time, returned count, exception count, reviewer, disposition, and export link',reviewer:'privilege counsel or the discovery lead',pause:'counts differ, family relationships are unclear, access expands, a coding rule requires interpretation, or material would be produced',image:'/aug23-heroes/privileged-folder-permissions.png',detail:'A batch returns 499 records against an assigned count of 500. Keep the batch open and route the single-record difference.'},
 {slug:'offshore-legal-support-closing-condition-evidence-index',title:'Closing-condition evidence indexes for offshore legal support',excerpt:'Connect lawyer-approved conditions to supplied evidence without deciding satisfaction, waiver, or closing readiness.',task:'closing-condition evidence indexing',sources:'the counsel-approved conditions list, transaction checklist, supplied certificates, consents, receipts, and status instruction',record:'condition label, cited requirement, evidence filename, source location, received time, observed gap, reviewer, and disposition',reviewer:'the deal lawyer or closing manager',pause:'evidence conflicts, a condition changes, satisfaction is uncertain, a waiver appears, or closing status must be declared',image:'/aug21-heroes/offshore-legal-support-production-readiness-board.png',detail:'A certificate is present but unsigned. Record the signature state as observed and leave satisfaction to the deal lawyer.'},
 {slug:'law-firm-offshore-client-consent-receipt-register',title:'Client consent receipt registers that preserve the original evidence',excerpt:'Record approved consent requests and returned evidence while the firm decides wording, validity, and reliance.',task:'client consent receipt registration',sources:'the lawyer-approved request, recipient record, delivery event, returned message or document, version history, and matter instruction',record:'recipient, request version, delivery time, return source, signature state, stated limits, reviewer, and disposition',reviewer:'the responsible lawyer',pause:'identity differs, wording changes, authority is uncertain, conditions appear, or reliance on the consent must be decided',image:'/aug21-heroes/legal-support-offshore-court-message-register.png',detail:'A reply says agreed but omits the attached form. Preserve the reply and flag the missing form; do not characterize the reply as consent.'},
 {slug:'offshore-legal-support-expert-invoice-document-check',title:'Document checks for expert invoices in offshore legal support',excerpt:'Check invoice packages against supplied administrative criteria while lawyers and finance approve substance and payment.',task:'expert invoice document checking',sources:'the engagement record, approved billing instructions, invoice, expense receipts, time detail, and matter coding guide',record:'invoice identifier, billing period, supplied pages, receipt links, visible arithmetic flag, code field, exception, and owner',reviewer:'the matter lawyer and authorized finance owner',pause:'rates require interpretation, work descriptions raise privilege concerns, support is absent, coding is unclear, or payment is requested',image:'/aug21-heroes/offshore-legal-support-vendor-evidence-log.png',detail:'An expense line refers to a receipt that is not attached. Record the line and missing support without rejecting or approving the charge.'},
 {slug:'law-firm-offshore-service-address-source-register',title:'Service-address source registers for litigation support teams',excerpt:'Preserve attorney-selected address sources and checks without choosing a service address or directing service.',task:'service-address source registration',sources:'the attorney-selected party list, approved address sources, returned service material, correspondence, and current instruction',record:'party label, exact displayed address, source link, access date, returned event, difference note, and reviewer decision',reviewer:'the supervising litigation lawyer',pause:'sources disagree, identity is uncertain, an address is incomplete, service rules matter, or another attempt is proposed',image:'/aug21-heroes/legal-support-offshore-party-name-register.png',detail:'Two approved sources show different suite numbers. Copy both exactly, record their dates, and route the conflict.'},
 {slug:'offshore-legal-support-regulatory-filing-receipt-log',title:'Regulatory filing receipt logs for supervised offshore support',excerpt:'Tie approved filings to submission and receipt evidence while counsel controls content, timing, and legal effect.',task:'regulatory filing receipt logging',sources:'the approved filing copy, submission instruction, portal event, payment record, confirmation, and agency correspondence',record:'filing identifier, approved version, submitter, event time, confirmation number, receipt file, exception, and reviewer state',reviewer:'regulatory counsel or the authorized filing owner',pause:'the approved version differs, the portal rejects a field, timing is uncertain, fees change, or resubmission is needed',image:'/sep3-heroes/regulatory-comment-letter-source-packet.png',detail:'The portal confirmation time differs from the local upload log. Preserve both timestamps and their time zones.'},
 {slug:'law-firm-offshore-settlement-payment-evidence-ledger',title:'Settlement payment evidence ledgers with firm-side approval',excerpt:'Organize approved payment evidence and status facts without directing funds or deciding compliance with settlement terms.',task:'settlement payment evidence logging',sources:'the executed agreement supplied by counsel, approved payment schedule, authorized confirmation, bank reference, correspondence, and owner instruction',record:'payment label, stated amount, scheduled date, confirmation source, visible reference, receipt state, exception, and reviewer',reviewer:'settlement counsel and the authorized finance owner',pause:'instructions change, account details appear unexpectedly, amounts conflict, receipt is missing, or funds would be moved',image:'/sep3-heroes/settlement-document-execution-status-board.png',detail:'A confirmation shows the expected amount but a different reference. Record the mismatch without opening links or changing payment instructions.'},
];

const sections=(t:Topic,i:number)=>[
 {heading:`Set the boundary for ${t.task}`,body:`Published September 7, 2026. Start with a named matter and a written instruction that identifies ${t.reviewer}. The support worker may prepare an administrative record from approved material. Legal interpretation, client advice, approval, and release remain with the firm. Give this workflow the identifier S7-${String(i+1).padStart(2,'0')} so its evidence can be traced without relying on inbox memory.`},
 {heading:'Work from a closed source set',body:`The permitted inputs are ${t.sources}. Capture each source location, visible version, and access date before doing the check. Do not browse for a substitute or quietly repair a discrepancy. A source gap is a fact for the record, not permission to widen the assignment.`},
 {heading:'Build the working record',body:`Use these fields: ${t.record}. Write what the source shows in plain language. Keep blanks when the approved material is silent. The record should let ${t.reviewer} find the same item and reproduce the observation without a private explanation from the preparer.`},
 {heading:'Handle the awkward case',body:`${t.detail} This is where a useful workflow differs from a tidy spreadsheet. Preserve the inconvenient evidence and assign one precise question. Never overwrite the earlier state after the reviewer answers; add the disposition as a later event.`},
 {heading:'Know when to pause',body:`Pause when ${t.pause}. Send the relevant source references, the observed difference, and the requested decision to ${t.reviewer}. Prepared, reviewed, approved, and released are separate states. A checked box cannot collapse those decisions into one.`},
 {heading:'Pilot and review',body:`Test the process on a small batch that includes ordinary records and at least one known exception. Review for wrong source, stale version, missing field, permission overreach, and weak disposition evidence. Count each category separately. A single accuracy percentage hides the difference between a clerical correction and a question that belongs to counsel.`},
 {heading:'Protect client and matter data',body:`Use named accounts, matter-limited permissions, approved devices, and firm-approved transfer paths. Put links or identifiers in the tracker when copying sensitive text is unnecessary. If material appears in the wrong location or reaches the wrong person, stop and follow the firm's incident path.`},
 {heading:'Close with evidence',body:`Close the record after ${t.reviewer} gives a documented disposition and the preparer links any correction to its earlier observation. Remove temporary access at assignment end and retain material only under firm policy. Recheck the workflow when a system, client instruction, reviewer, or source changes.`},
];

export const september7BlogPosts=topics.map((topic,index)=>({slug:topic.slug,title:topic.title,excerpt:topic.excerpt,published:'2026-09-07' as const,modified:'2026-09-07',minutes:8,featuredImage:topic.image,sections:sections(topic,index)}));
