type Topic = {
  slug: string; title: string; excerpt: string; subject: string; source: string;
  output: string; owner: string; stop: string; metric: string;
};

const topics: readonly Topic[] = [
  { slug: 'offshore-legal-support-deposition-exhibit-inventory', title: 'Deposition exhibit inventories with offshore legal support', excerpt: 'Build a source-linked exhibit inventory while litigation counsel controls selection, use, and objections.', subject: 'deposition exhibit inventory preparation', source: 'the approved exhibit folder, deposition notice, matter index, and counsel instructions', output: 'an inventory of supplied files, versions, labels, page counts, and unresolved gaps', owner: 'the supervising litigation attorney', stop: 'a document is privileged, a version conflicts, a proposed exhibit is outside the approved set, or legal relevance must be decided', metric: 'records matched to an approved source version' },
  { slug: 'law-firm-offshore-subpoena-response-tracking', title: 'Subpoena response tracking for offshore legal support', excerpt: 'Track authorized response events and dependencies without interpreting obligations or calculating legal deadlines.', subject: 'subpoena response administration', source: 'the attorney-approved matter record, subpoena copy, docket entries, correspondence, and response plan', output: 'an event log showing source dates, assigned actions, dependencies, status, and attorney dispositions', owner: 'the responsible attorney or docketing manager', stop: 'service is disputed, scope changes, a deadline requires calculation, responsive material is unclear, or a third party requests advice', metric: 'events carrying a source, owner, and disposition' },
  { slug: 'offshore-legal-support-entity-name-verification-register', title: 'Entity-name verification registers for offshore legal support', excerpt: 'Compare supplied entity names with approved records while counsel decides identity and legal significance.', subject: 'entity-name verification', source: 'the approved client intake, formation record, contract draft, and designated public registry result', output: 'a comparison preserving each spelling, identifier, jurisdiction, retrieval date, and discrepancy', owner: 'the transaction attorney or corporate paralegal lead', stop: 'identifiers conflict, an entity appears inactive, the jurisdiction differs, or identity cannot be established mechanically', metric: 'name comparisons with reproducible provenance' },
  { slug: 'law-firm-offshore-litigation-hold-acknowledgment-log', title: 'Litigation-hold acknowledgment logs with offshore support', excerpt: 'Record approved notice and acknowledgment events while lawyers retain hold scope and release decisions.', subject: 'litigation-hold acknowledgment logging', source: 'the counsel-approved recipient list, notice version, delivery record, reminder instruction, and acknowledgment response', output: 'a recipient-level ledger of notice version, delivery, acknowledgment, exception, and escalation', owner: 'the responsible lawyer or records manager', stop: 'a recipient disputes scope, delivery fails, employment status differs, a new custodian appears, or release is requested', metric: 'acknowledgments tied to the correct notice version' },
  { slug: 'offshore-legal-support-court-filing-receipt-reconciliation', title: 'Court filing receipt reconciliation with offshore legal support', excerpt: 'Reconcile approved filing submissions and receipts while authorized professionals decide procedural effect.', subject: 'court filing receipt reconciliation', source: 'the approved filing package, submission confirmation, court receipt, docket entry, and filer instruction', output: 'a comparison of document names, timestamps, confirmation identifiers, fees, and receipt status', owner: 'the filing attorney or docketing specialist', stop: 'the court rejects a filing, document names differ, timestamps conflict, fees change, or procedural interpretation is needed', metric: 'submitted items reconciled to official receipt evidence' },
  { slug: 'legal-support-offshore-client-consent-record-index', title: 'Client consent record indexes for offshore legal support', excerpt: 'Index approved consent records and versions without determining whether consent is legally sufficient.', subject: 'client consent record indexing', source: 'the firm-approved consent form, signature record, communication archive, matter identifier, and version register', output: 'an index linking each supplied consent artifact to its matter, version, date shown, source, and review state', owner: 'the responsible attorney or privacy owner', stop: 'a signature is missing, versions conflict, scope is unclear, consent is withdrawn, or sufficiency must be judged', metric: 'indexed artifacts with matter and version provenance' },
  { slug: 'offshore-legal-support-privilege-review-batch-control', title: 'Privilege-review batch controls for offshore legal support', excerpt: 'Control approved review batches and technical handoffs while counsel makes every privilege determination.', subject: 'privilege-review batch administration', source: 'the counsel-approved review protocol, batch manifest, review platform export, and decision-owner instructions', output: 'a batch control sheet showing population, assignment, technical status, exceptions, and counsel completion evidence', owner: 'the discovery attorney or privilege-review lead', stop: 'coding guidance is ambiguous, family relationships break, a document falls outside scope, or privilege judgment is requested', metric: 'batch populations reconciled before and after review' },
  { slug: 'law-firm-offshore-contract-obligation-data-entry', title: 'Contract obligation data entry with offshore legal support', excerpt: 'Enter attorney-approved obligation fields with source citations while legal interpretation remains with counsel.', subject: 'contract obligation data entry', source: 'the executed agreement, approved field definition, amendment set, and attorney-marked source provision', output: 'a structured record linking each approved value to document, version, section, and reviewer', owner: 'the commercial attorney or contracts manager', stop: 'terms conflict, an amendment changes the provision, a field requires interpretation, or the executed version is uncertain', metric: 'approved fields carrying exact provision citations' },
  { slug: 'offshore-legal-support-matter-closing-document-checklist', title: 'Matter-closing document checklists with offshore legal support', excerpt: 'Check approved closing artifacts and ownership while counsel determines whether a matter may close.', subject: 'matter-closing document preparation', source: 'the approved closing policy, matter system, final work-product list, billing status, and records instructions', output: 'a checklist of located artifacts, source links, unresolved exceptions, retention classification, and owner response', owner: 'the matter attorney or records manager', stop: 'work remains open, a hold applies, ownership is missing, retention is unclear, or closure approval is requested', metric: 'closing requirements supported by accessible evidence' },
  { slug: 'legal-support-offshore-regulatory-correspondence-index', title: 'Regulatory correspondence indexes for offshore legal support', excerpt: 'Index authorized correspondence by source and event while lawyers control regulatory interpretation and response.', subject: 'regulatory correspondence indexing', source: 'the approved regulator communication set, delivery records, attachments, matter index, and counsel taxonomy', output: 'a chronology of sender, recipient, date shown, received time, attachment set, topic label, and review state', owner: 'the regulatory attorney or compliance counsel', stop: 'a response is requested, a deadline is unclear, attachments are missing, confidentiality markings differ, or classification needs judgment', metric: 'communications linked to complete attachment sets' },
  { slug: 'offshore-legal-support-settlement-payment-status-ledger', title: 'Settlement payment status ledgers with offshore legal support', excerpt: 'Record approved payment-status evidence while authorized firm personnel control amounts, release, and legal conclusions.', subject: 'settlement payment status administration', source: 'the executed settlement record, attorney-approved payment schedule, finance confirmation, and written status instruction', output: 'a restricted ledger showing scheduled event, approved amount reference, evidence state, exception, and decision owner', owner: 'the responsible attorney and authorized finance controller', stop: 'amounts conflict, instructions change, account details appear in an unapproved channel, payment is late, or release is proposed', metric: 'status entries supported by approved finance evidence' },
  { slug: 'law-firm-offshore-witness-contact-attempt-register', title: 'Witness contact-attempt registers with offshore legal support', excerpt: 'Log counsel-approved contact attempts and outcomes without interviewing witnesses or giving legal guidance.', subject: 'witness contact-attempt logging', source: 'the attorney-approved contact instruction, supplied contact details, communication template, and channel record', output: 'a factual log of authorized attempt time, channel, template version, delivery state, response category, and escalation', owner: 'the supervising attorney or investigator', stop: 'identity is uncertain, a witness asks a substantive question, contact details change, consent is disputed, or the approved script no longer fits', metric: 'authorized attempts with attributable channel evidence' },
];

const makeSections = (t: Topic, index: number) => [
  { heading: 'Set the operating boundary', body: `Published September 2, 2026. ${t.subject} starts with a written scope, approved systems, and a named reviewer. The scope should separate factual preparation from decisions reserved to ${t.owner}. Batch ${index + 1} uses its own task identifier and acceptance record.` },
  { heading: 'Identify controlling inputs', body: `The controlling inputs are ${t.source}. Record where each input came from, when it was accessed, and which version was used. If two authorized sources differ, preserve both observations and route the conflict instead of choosing one silently.` },
  { heading: 'Create the work product', body: `The expected output is ${t.output}. Each entry should name its preparer, source reference, status, exception if any, next owner, and review disposition. This evidence lets another authorized person reconstruct the administrative step.` },
  { heading: 'Reserve the decision gate', body: `${t.owner} owns acceptance and every legal or client-facing decision. Prepared, reviewed, approved, and released are separate states. A completed administrative check does not establish legal sufficiency, compliance, privilege, or outcome.` },
  { heading: 'Use explicit stop rules', body: `Stop when ${t.stop}. Keep the record unchanged, state the uncertainty in neutral language, and route one precise question to the owner. Urgency does not expand authority, access, or the permitted source set.` },
  { heading: 'Review a bounded pilot', body: `Test the routine on a small representative cohort before increasing volume. Review normal items and exceptions against their sources. Classify corrections by source, version, field, access, instruction, escalation, or unauthorized action so managers can improve the routine.` },
  { heading: 'Protect confidential material', body: `Use individual accounts, least-privilege access, approved devices, and approved transfer channels. Prefer a controlled source reference over copying client facts into coordination notes. Report mistaken access or recipients immediately and preserve the event trail.` },
  { heading: 'Measure evidence, not impressions', body: `Track ${t.metric}, exception-routing time, correction type, reviewer response, and final disposition. Report the cohort and denominator. Speed without source fidelity is not a quality measure, and a local sample is not a universal performance claim.` },
  { heading: 'Close and recertify', body: `Closure requires the owner's recorded disposition and a named next action for anything unresolved. Link corrections to the earlier state, remove access when the assignment ends, and recertify the routine when its source, system, template, risk, or reviewer changes.` },
];

export const september2BlogPosts = topics.map((topic, index) => ({
  slug: topic.slug, title: topic.title, excerpt: topic.excerpt,
  published: '2026-09-02' as const, modified: '2026-09-02', minutes: 9,
  sections: makeSections(topic, index),
}));
