type Topic={slug:string;title:string;excerpt:string;task:string;inputs:string;fields:string;owner:string;stop:string;example:string;image:string};

const topics:readonly Topic[]=[
 {slug:'offshore-legal-support-demand-letter-exhibit-register',title:'Building a demand-letter exhibit register with offshore legal support',excerpt:'Organize counsel-approved exhibits and source references while the responsible lawyer controls legal assertions, valuation, and release.',task:'demand-letter exhibit registration',inputs:'the counsel-approved draft, exhibit list, supplied records, correspondence, and current written instruction',fields:'exhibit label, source filename, visible date, page range, draft reference, observed gap, reviewer, and disposition',owner:'the responsible lawyer',stop:'a source conflicts, an exhibit is missing, damages must be characterized, a legal assertion changes, or release is requested',example:'The draft cites an invoice total that differs from the supplied invoice. Record both values and route the mismatch without editing the demand.' ,image:'/aug23-heroes/document-version-ledgers.png'},
 {slug:'law-firm-offshore-immigration-filing-receipt-index',title:'An immigration filing-receipt index for offshore legal support',excerpt:'Connect attorney-approved submissions to agency receipts and case records without calculating status, eligibility, or deadlines.',task:'immigration filing-receipt indexing',inputs:'the approved filing copy, delivery evidence, agency receipt, matter record, and attorney instruction',fields:'beneficiary label, filing version, submission event, receipt identifier, notice date as displayed, source link, exception, and reviewer',owner:'immigration counsel',stop:'names differ, the receipt does not match the filing, a response date needs calculation, status needs interpretation, or outreach is proposed',example:'The receipt abbreviates a beneficiary name differently from the filing. Preserve both source strings and ask counsel whether the records match.',image:'/aug21-heroes/legal-support-offshore-party-name-register.png'},
 {slug:'offshore-legal-support-deposition-transcript-correction-log',title:'Logging deposition transcript corrections with offshore support',excerpt:'Track witness-supplied corrections and source pages while litigation counsel decides form, significance, and submission.',task:'deposition transcript correction logging',inputs:'the certified transcript, supplied errata, witness communication, exhibit list, and counsel instruction',fields:'page and line, transcript text, supplied correction, stated reason, source message, received time, open question, and reviewer',owner:'litigation counsel',stop:'the cited line is absent, wording is ambiguous, an explanation is requested, timing must be assessed, or the correction would be submitted',example:'An errata entry cites page 84, line 11, but the phrase appears on line 12. Log the discrepancy rather than moving the citation.',image:'/sep3-heroes/deposition-errata-return-tracker.png'},
 {slug:'law-firm-offshore-closing-deliverables-custody-log',title:'Closing-deliverables custody logs for law firm offshore teams',excerpt:'Trace executed documents, originals, copies, and transfer receipts while deal counsel controls completeness and legal effect.',task:'closing-deliverables custody logging',inputs:'the counsel-approved closing list, executed documents, delivery messages, repository events, and custodian instructions',fields:'deliverable identifier, version, signature state as displayed, current custodian, transfer event, receipt evidence, exception, and reviewer',owner:'deal counsel',stop:'versions compete, an original is unlocated, execution is unclear, a recipient changes, or legal completeness must be stated',example:'A PDF appears executed, but the closing list requests an original. Record the PDF and the unresolved original-custody requirement separately.',image:'/sep3-heroes/settlement-document-execution-status-board.png'},
 {slug:'offshore-legal-support-public-records-request-correspondence-log',title:'Public-records request correspondence logs for offshore legal support',excerpt:'Preserve approved requests, agency messages, fee notices, and deliveries while counsel controls scope and response decisions.',task:'public-records correspondence logging',inputs:'the approved request, delivery proof, agency correspondence, fee notice, produced files, and lawyer instruction',fields:'request identifier, agency, message date, stated status, fee amount as displayed, delivery reference, open question, and owner',owner:'the supervising lawyer',stop:'scope is questioned, an exemption is cited, a deadline needs interpretation, payment is requested, or a response must be negotiated',example:'An agency labels its delivery final while its message lists one pending search. Preserve both statements and route the inconsistency.',image:'/aug21-heroes/offshore-legal-support-evidence-request-matrix.png'},
 {slug:'law-firm-offshore-nda-obligation-source-table',title:'Preparing NDA obligation source tables with offshore legal support',excerpt:'Map counsel-selected clauses to operational fields without interpreting enforceability, scope, breach, or remedies.',task:'NDA obligation source-table preparation',inputs:'the approved agreement set, amendment list, party index, counsel-defined fields, and review instruction',fields:'agreement identifier, clause reference, party text, stated period, notice detail, amendment source, uncertainty, and reviewer',owner:'commercial counsel',stop:'agreements conflict, a term is undefined, applicability is uncertain, interpretation is needed, or advice would be given',example:'An amendment changes a section number without restating the text. Link both instruments and leave the resulting obligation to counsel.',image:'/aug23-heroes/document-version-ledgers.png'},
 {slug:'offshore-legal-support-legal-hold-custodian-response-register',title:'A legal-hold custodian response register for offshore support',excerpt:'Record approved notices and acknowledgments while counsel controls preservation scope, follow-up, and legal conclusions.',task:'legal-hold custodian response registration',inputs:'the counsel-approved notice, custodian list, delivery events, acknowledgments, exception messages, and current instruction',fields:'custodian as supplied, notice version, delivery event, acknowledgment time, stated issue, follow-up owner, and disposition',owner:'preservation counsel',stop:'identity is uncertain, delivery fails, a custodian raises a scope question, data loss is reported, or new directions are proposed',example:'A custodian acknowledges the notice but says a named device was replaced. Record the statement verbatim and escalate without investigating the device.',image:'/aug21-heroes/offshore-legal-support-retention-hold-question-log.png'},
 {slug:'law-firm-offshore-settlement-payment-evidence-ledger',title:'Settlement payment evidence ledgers for supervised offshore support',excerpt:'Connect counsel-approved payment terms to administrative evidence while authorized owners control compliance and disbursement.',task:'settlement payment evidence logging',inputs:'the executed agreement, counsel-approved milestone list, bank or escrow evidence supplied by the firm, correspondence, and instruction',fields:'milestone label, stated amount, due date as supplied, event evidence, payer and recipient labels, exception, owner, and disposition',owner:'settlement counsel and the authorized finance owner',stop:'terms conflict, a date needs calculation, account details change, funds movement is requested, or satisfaction must be declared',example:'A receipt shows the expected amount but a different reference number. Preserve the receipt and ask the authorized owners to reconcile it.',image:'/aug23-heroes/billing-exception-queues.png'},
 {slug:'offshore-legal-support-expert-file-materials-index',title:'Indexing expert-file materials with offshore legal support',excerpt:'Organize counsel-approved expert materials and transmission evidence without deciding reliance, admissibility, or disclosure.',task:'expert-file materials indexing',inputs:'the approved expert request, supplied materials, transmittal messages, version list, and attorney instruction',fields:'item identifier, source, version, sent date, recipient as supplied, acknowledgment, observed gap, and reviewer',owner:'litigation counsel',stop:'materials appear privileged, versions conflict, a recipient is unexpected, scope changes, or substantive selection is requested',example:'A draft report appears in the folder but not on the approved transmittal. Keep it quarantined from the packet and notify counsel.',image:'/sep3-heroes/expert-witness-conflict-intake-register.png'},
 {slug:'law-firm-offshore-records-retention-disposition-queue',title:'Records-retention disposition queues for law firm offshore teams',excerpt:'Prepare source-linked disposition records while the firm decides holds, retention periods, transfer, and deletion.',task:'records-retention disposition queue preparation',inputs:'the firm-approved schedule, matter inventory, hold status supplied by counsel, system reports, and written disposition instruction',fields:'record class, matter identifier, schedule source, hold state as supplied, proposed administrative action, evidence link, exception, and approver',owner:'records counsel or the authorized records manager',stop:'a hold may apply, classification is uncertain, schedules conflict, deletion is proposed without approval, or ownership is unclear',example:'A closed matter meets a schedule period but the hold field is blank. Leave disposition pending and route the missing control.',image:'/aug23-heroes/matter-closeout-records.png'},
 {slug:'offshore-legal-support-service-of-process-proof-index',title:'Service-of-process proof indexes for offshore legal support',excerpt:'Link counsel-approved service instructions to returned affidavits and delivery evidence without deciding validity or deadline effect.',task:'service-of-process proof indexing',inputs:'the approved service packet, process-server messages, returned proof, delivery evidence, court record supplied by counsel, and instruction',fields:'party label, document set, server, attempt event, returned proof, filing state as displayed, discrepancy, and reviewer',owner:'litigation counsel',stop:'party names differ, service details conflict, validity is questioned, a deadline needs calculation, or a filing would be made',example:'The affidavit lists the correct address but a different suite from the instruction. Record both values and request counsel review.',image:'/sep3-heroes/legal-mail-service-proof-packet.png'},
 {slug:'law-firm-offshore-board-resolution-version-register',title:'Board-resolution version registers for offshore legal teams',excerpt:'Trace drafts, approvals, signatures, and attachments while corporate counsel controls authority, validity, and final assembly.',task:'board-resolution version registration',inputs:'the counsel-approved draft set, board materials, approval messages, signature pages, attachments, and instruction',fields:'resolution identifier, version, sender, approval event, signature-page reference, attachment set, conflict, and reviewer',owner:'corporate counsel',stop:'two versions are marked final, authority is unclear, signatures differ, an attachment is missing, or assembly is requested',example:'An approval email names version four while its attachment filename says version three. Preserve both artifacts and route the conflict.',image:'/sep3-heroes/board-consent-signature-collection-tracker.png'},
];

const sections=(t:Topic,i:number)=>[
 {heading:`Define the ${t.task} lane`,body:`Published September 9, 2026. Assign control ID S9-B${String(i+1).padStart(2,'0')} and name ${t.owner} before work begins. Offshore support may prepare an administrative record from approved sources. Legal analysis, advice, approval, and external release remain with the firm.`},
 {heading:'Lock the source set',body:`Use only ${t.inputs}. Record where each item came from, its visible version, and when it was accessed. A missing source stays missing; do not substitute another document or repair a conflict silently.`},
 {heading:'Create a traceable working record',body:`Capture ${t.fields}. Write observations in neutral language and preserve earlier values when a later instruction changes the record. Another authorized reviewer should be able to find the same source and reconstruct the handoff.`},
 {heading:'Handle the awkward item',body:`${t.example} This protects the source trail and places the unresolved decision with ${t.owner}, instead of making the queue appear artificially complete.`},
 {heading:'Use an explicit stop rule',body:`Pause when ${t.stop}. Send the relevant source links, the observed difference, and one precise question to ${t.owner}. Keep prepared, reviewed, approved, and released as separate states.`},
 {heading:'Pilot and review the routine',body:`Test a small, defined batch with ordinary records and at least one known exception. Review source choice, version accuracy, field accuracy, access scope, escalation, and disposition separately. Keep the denominator and review period visible; the sample is not a universal performance claim.`},
 {heading:'Protect client information',body:`Use named accounts, matter-limited access, approved devices, and firm-approved transfer paths. Prefer source links and identifiers over copied confidential text. Stop and follow the firm's incident path if content appears in an unexpected location or reaches an unintended recipient.`},
 {heading:'Close with an attributable decision',body:`Close an item only after ${t.owner} records its disposition and any correction links to the earlier observation. Remove temporary access when instructed and retain the record under firm policy. Reassess the routine when its task, system, source, instruction, reviewer, or client requirement changes.`},
];

export const september9BlogPosts=topics.map((topic,index)=>({slug:topic.slug,title:topic.title,excerpt:topic.excerpt,published:'2026-09-09' as const,modified:'2026-09-09',minutes:8,featuredImage:topic.image,sections:sections(topic,index)}));
