type Topic = {
  slug: string; title: string; excerpt: string; subject: string; source: string;
  output: string; owner: string; stop: string; boundary: string;
};

const topics: readonly Topic[] = [
  { slug: 'offshore-legal-support-medical-record-chronology-intake', title: 'Medical-record chronology intake with offshore legal support', excerpt: 'Organize authorized medical records by source and date while counsel controls relevance, causation, and case strategy.', subject: 'medical-record chronology intake', source: 'the firm-approved record set, provider identity, page metadata, and written chronology instructions', output: 'a dated event table linked to the exact source page, with gaps and illegible entries called out', owner: 'the supervising litigation attorney or nurse reviewer', stop: 'a diagnosis is unclear, records conflict, a new provider appears, or an entry requires clinical or legal interpretation', boundary: 'The worker records what the authorized source says and does not infer causation, severity, prognosis, or damages.' },
  { slug: 'law-firm-offshore-conflict-search-input-quality-check', title: 'Conflict-search input quality checks for offshore legal support', excerpt: 'Check names, entities, roles, and source provenance before an authorized conflicts team runs and resolves a search.', subject: 'conflict-search input preparation', source: 'the approved intake form, supplied party list, corporate relationships, and matter identifiers', output: 'a normalized candidate list that preserves original spellings, aliases supplied by the requester, roles, and unresolved identity questions', owner: 'the firm conflicts lawyer or designated conflicts analyst', stop: 'an alias is inferred, two people may share an identity, a relationship is unclear, or a potential match appears', boundary: 'The support role prepares search inputs but never clears a conflict, evaluates a match, or opens a matter.' },
  { slug: 'offshore-legal-support-discovery-production-volume-reconciliation', title: 'Discovery production volume reconciliation with offshore support', excerpt: 'Reconcile approved production counts, ranges, and transfer evidence without deciding completeness or discovery compliance.', subject: 'discovery production volume reconciliation', source: 'the approved production manifest, export report, transfer receipt, Bates range, and exception messages', output: 'a source-linked comparison of expected files, delivered files, page ranges, errors, and reviewer disposition', owner: 'the discovery attorney or litigation-support manager', stop: 'counts differ, a range overlaps, an export fails, a file is inaccessible, or scope appears to have changed', boundary: 'Administrative reconciliation can expose discrepancies but cannot establish responsiveness, privilege, completeness, or compliance.' },
  { slug: 'law-firm-client-funds-instruction-verification-queue', title: 'Client-funds instruction verification queues with offshore support', excerpt: 'Route payment instructions through a controlled verification record while authorized firm personnel approve every funds decision.', subject: 'client-funds instruction verification administration', source: 'the firm-approved request, known contact record, payment-system reference, and independent verification procedure', output: 'a locked queue showing the request source, verification state, exception, approver, and release status without exposing unnecessary account data', owner: 'the firm finance controller or attorney authorized for client funds', stop: 'instructions change, contact details differ, urgency is used to bypass review, or verification cannot be completed', boundary: 'The worker may record and route facts but may not validate entitlement, alter banking details, approve, release, or promise a payment.' },
  { slug: 'offshore-legal-support-contract-signature-page-matching', title: 'Contract signature-page matching with offshore legal support', excerpt: 'Match returned signature pages to approved document versions while counsel controls execution status and legal effect.', subject: 'contract signature-page matching', source: 'the attorney-approved execution copy, version identifier, returned pages, envelope record, and signer information', output: 'a version-linked signature inventory showing received pages, apparent signers, dates shown, and open mismatches', owner: 'the transaction attorney or authorized closing coordinator', stop: 'a page maps to the wrong version, a signer differs, a date is missing, counterparts conflict, or authority is questioned', boundary: 'The support role identifies documentary matches and discrepancies but does not decide due execution, authority, enforceability, or closing readiness.' },
  { slug: 'legal-support-offshore-public-record-retrieval-log', title: 'Public-record retrieval logs for offshore legal support', excerpt: 'Document approved searches, query terms, results, and access limits while lawyers decide relevance and legal use.', subject: 'public-record retrieval logging', source: 'the written research request, approved public database, search parameters, result page, and retrieval timestamp', output: 'a reproducible search log with jurisdiction, query, date, located records, unavailable records, and source links', owner: 'the requesting attorney or research manager', stop: 'identity is ambiguous, access terms are unclear, paid data is requested, a sealed record appears, or scope must expand', boundary: 'A retrieval log reports what a bounded search found and does not establish identity, accuracy, completeness, or legal significance.' },
  { slug: 'offshore-legal-support-trust-account-document-index', title: 'Trust-account document indexes with offshore legal support', excerpt: 'Index authorized trust-account documents and review evidence while finance owners retain reconciliation and disbursement authority.', subject: 'trust-account document indexing', source: 'the approved statement set, deposit and disbursement records, matter references, and reviewer instructions', output: 'a period-based index linking each authorized document to its account period, matter reference, and review state', owner: 'the trust-account supervisor, controller, or responsible lawyer', stop: 'an amount conflicts, a matter reference is absent, an unexpected account appears, or a transaction needs classification', boundary: 'The worker organizes authorized evidence and does not reconcile balances, select classifications, move funds, or certify compliance.' },
  { slug: 'law-firm-offshore-legal-mail-service-evidence-register', title: 'Legal-mail service evidence registers with offshore support', excerpt: 'Preserve approved mailings, tracking events, receipts, and returned items without characterizing legal service.', subject: 'legal-mail service evidence registration', source: 'the approved document version, recipient instruction, carrier record, receipt, returned item, and firm correspondence', output: 'an event chronology linking each package, address as instructed, carrier status, receipt, and unresolved delivery question', owner: 'the responsible attorney or docketing owner', stop: 'an address changes, delivery is disputed, a package returns, dates conflict, or alternate service is proposed', boundary: 'Carrier events are recorded in their original terms; only counsel decides whether service was effective or what response follows.' },
  { slug: 'offshore-legal-support-nda-request-intake-register', title: 'NDA request intake registers for offshore legal support', excerpt: 'Capture approved request facts, parties, forms, and deadlines while counsel controls drafting positions and approval.', subject: 'NDA request intake', source: 'the requester submission, approved party records, firm template library, stated purpose, and counsel instructions', output: 'an intake record showing parties as supplied, requested form, purpose, source documents, timing, and missing facts', owner: 'the commercial attorney or contracts manager', stop: 'a new counterparty appears, nonstandard language is requested, governing law changes, or a legal position is needed', boundary: 'Support staff may route a complete factual request but may not select terms, negotiate, advise, or approve signature.' },
  { slug: 'legal-support-offshore-records-destruction-approval-packet', title: 'Records-destruction approval packets with offshore support', excerpt: 'Prepare source-linked retention and hold evidence while authorized owners decide whether destruction may proceed.', subject: 'records-destruction approval packet preparation', source: 'the approved retention schedule, system inventory, matter status, hold register, and written owner instructions', output: 'a proposed population inventory with schedule reference, exclusions, unresolved holds, reviewer, and approval evidence', owner: 'the records manager, responsible lawyer, privacy owner, or other authorized decision maker', stop: 'a hold is unclear, schedules conflict, ownership is missing, a system scope changes, or client records cannot be classified', boundary: 'The worker prepares evidence and never authorizes deletion, resolves a hold, changes retention rules, or destroys records.' },
  { slug: 'offshore-legal-support-expert-witness-materials-transfer-log', title: 'Expert-witness materials transfer logs with offshore support', excerpt: 'Track approved materials, versions, recipients, and transfer receipts while counsel controls expert communications and disclosure strategy.', subject: 'expert-witness materials transfer logging', source: 'the attorney-approved transfer list, source files, recipient identity, secure-channel instruction, and delivery receipt', output: 'a file-level manifest showing version, source, approved recipient, transfer event, receipt, and exceptions', owner: 'the retaining attorney or designated litigation-support lead', stop: 'a recipient differs, privileged markings appear, files are added, delivery fails, or substantive communication is requested', boundary: 'The support lane proves an administrative transfer trail and does not decide what an expert should receive, consider, disclose, or say.' },
  { slug: 'law-firm-offshore-appeal-record-assembly-checklist', title: 'Appeal-record assembly checklists with offshore legal support', excerpt: 'Assemble approved record components and source references while appellate counsel controls designation and procedural judgment.', subject: 'appeal-record assembly', source: 'the attorney-approved designation, docket entries, filed versions, transcript records, exhibits, and clerk communications', output: 'a component checklist linked to docket source, filed date, version, page range, and unresolved availability issue', owner: 'appellate counsel or the firm docketing specialist', stop: 'the designation is unclear, a filing is missing, versions conflict, a deadline question arises, or supplementation is proposed', boundary: 'The worker checks supplied components and never decides the appellate record, calculates deadlines, interprets rules, or submits materials.' },
];

const makeSections = (t: Topic, index: number) => [
  { heading: 'Define the assignment', body: `Published September 1, 2026. ${t.subject} begins with a written matter scope, named systems, allowed records, and a firm-side reviewer. ${t.boundary} The assignment should identify the permitted administrative action and the exact event that requires a pause.` },
  { heading: 'Use the controlling sources', body: `The approved inputs are ${t.source}. Preserve the source identity, retrieval time, and version. When records disagree, retain both observations and flag the conflict. Do not silently select the value that appears newest or most convenient.` },
  { heading: 'Build a reviewable record', body: `The expected work product is ${t.output}. Include a stable work-item identifier, preparer, timestamp, source reference, status, exception, next owner, and disposition. A later reviewer should be able to reconstruct the work without relying on private chat or memory.` },
  { heading: 'Keep decisions with the firm', body: `${t.owner} owns the decision gate. Preparation, approval, and external release are separate states. A completed checklist means the defined administrative checks occurred; it does not prove legal sufficiency, professional compliance, or a client outcome.` },
  { heading: 'Stop on changed conditions', body: `Pause when ${t.stop}. Preserve the item as found, write one narrow factual question, route it to ${t.owner}, and record the handoff time. An urgent label does not authorize the worker to expand access, infer an answer, or bypass review.` },
  { heading: 'Pilot the routine', body: `Start with one approved example and a small live cohort. Review every item against its source, including clean items and exceptions. Classify corrections by wrong source, missing field, version conflict, unauthorized change, late escalation, or access issue. The firm can widen sampling only after the same task and source pattern is stable.` },
  { heading: 'Protect client information', body: `Use named accounts, least-privilege permissions, approved devices, and approved transfer channels. Avoid copying sensitive facts into coordination fields when a secure source link is enough. Unexpected access, a wrong-matter opening, or a mistaken recipient requires an immediate factual report and preservation of the event trail.` },
  { heading: 'Measure the handoff', body: `For cohort ${index + 1}, measure source fidelity, required-field completion, exception routing time, reviewer response, correction reason, and final disposition separately. A fast completion without source evidence is not a quality result. Reviewers should also inspect whether precise pauses were handled correctly.` },
  { heading: 'Close with evidence', body: `Closure requires a visible reviewer disposition, any correction linked to the earlier state, and a named next owner for unresolved work. Remove access when the assignment ends. The operating record should show what was requested, what happened, what remains uncertain, and who accepted the handoff.` },
];

export const september1BlogPosts = topics.map((topic, index) => ({
  slug: topic.slug, title: topic.title, excerpt: topic.excerpt,
  published: '2026-09-01' as const, modified: '2026-09-01', minutes: 9,
  sections: makeSections(topic, index),
}));
