type Section = { heading: string; body: string };
type NewPost = { slug: string; title: string; excerpt: string; minutes: number; published: '2026-08-18'; sections: Section[] };

/* The August 18 batch is kept in its own source file so date binding and review are obvious. */
const makePost = (slug: string, title: string, excerpt: string, focus: string, workflow: string, boundary: string, checks: string, example: string): NewPost => {
  const paragraphs = [
    `Start with the actual ${focus} queue rather than an abstract job title. The firm should identify where each item arrives, which matter or client identifier travels with it, what a finished preparation looks like, and which person owns the next decision. For offshore legal support, the point is not to move responsibility out of the firm. It is to make repeatable preparation visible, consistent, and easy for a lawyer or manager to review. Before access is granted, collect two or three approved examples, mark sensitive fields, and write down the stop condition. If the source is missing, conflicting, or unexpectedly urgent, the worker records the gap and pauses. That small discipline prevents a neat-looking output from hiding an unexamined assumption.`,
    `A workable ${workflow} has a clear intake, preparation, review, and closeout path. At intake, record the requestor, matter, source location, received time, requested result, and owner. During preparation, preserve the source, use the current firm-approved format, and distinguish copied facts from notes or questions. The reviewer should be able to compare the output with the source without asking the worker to reconstruct what happened. Review is not a ceremonial sign-off: it is where the firm checks substance, confidentiality, client promises, and any unusual circumstance. At closeout, record the disposition, unresolved items, rework reason, and next owner. A queue is healthy when another person can understand its state without relying on private chat history.`,
    `The role boundary matters most when ${boundary}. Offshore support may gather, label, sort, format, reconcile against an approved checklist, and report what is absent. It should not decide legal meaning, privilege, strategy, eligibility, liability, filing sufficiency, settlement position, or what advice a client should receive. The worker also should not silently repair a contradictory record by choosing the version that seems most plausible. A better response is to preserve both sources, describe the conflict neutrally, and route one precise question to the named reviewer. The firm retains supervision, client communication, legal judgment, and final release. This division makes the role safer and also improves training because the worker knows what a complete handoff contains.`,
    `For quality control, measure ${checks} at the level of individual work, not only at the level of volume. A manager can sample whether the right source was used, whether identifiers and dates were retained, whether missing information was marked, whether permissions matched the task, and whether escalation happened promptly. Track rework by reason: omitted field, wrong source, formatting defect, unclear instruction, or reviewer change. Those categories tell the firm whether to coach the person, repair the process, or narrow the scope. Review early work daily, then change the cadence only after the same task type is consistently understandable and exceptions reach the right owner. Never turn a low error count into a claim that legal risk has disappeared; the scorecard is a control signal, not a legal conclusion.`,
    `Consider ${example}. The worker receives an approved request and two source files, but one carries a different date and the second has an incomplete identifier. The correct output is not a confident merged record. It is a prepared item that links both files, states exactly where they differ, names the missing field, and sends the question to the firm contact. If the reviewer confirms which source controls, that instruction becomes part of the record and can improve the next example. If the request changes scope, reaches a new recipient, or requires a legal conclusion, the worker stops even when the queue is busy. Concrete examples like this are more useful than broad promises because they show how the role behaves under ordinary ambiguity.`,
    `The operating setup should also account for confidentiality. Use named accounts, least-access permissions, matter-specific folders where practical, and a documented route for a suspected wrong-file or wrong-recipient event. Training examples should be redacted when the task can be learned without live client information. Keep source and working copies distinct, avoid downloading material that the task does not require, and remove access when the assignment changes. The firm should decide retention, monitoring, incident response, and contractual requirements with appropriate professional advice. Offshore location is not a substitute for those controls, and a control is not real merely because it appears in a policy. The manager should be able to show who reviews the work and how an exception becomes visible.`,
    `A sensible pilot adds one lane at a time. Write the role brief in the language of outputs: what arrives, what is prepared, what evidence accompanies it, who reviews it, and what must never be released without approval. Test the instructions against a clean example and an intentionally incomplete example. During the first week, review every output and keep a short question log. At the end of the pilot, decide whether the task is ready to continue, needs a revised checklist, or should remain with the firm. Adding a second lane is justified by stable quality and review capacity, not by a desire to fill idle time. For LegalServicesOffshore.com readers, this is the practical value of offshore legal support: a disciplined operating lane that helps a legal team work through its queue while the firm keeps the decisions that matter.`
  ];
  const headings = ['Define the work before access', 'Use a traceable handoff', 'Keep legal judgment with the firm', 'Check quality and exceptions', 'Work through an ambiguous example', 'Protect the matter record', 'Pilot, review, and expand carefully'];
  return { slug, title, excerpt, minutes: 9, published: '2026-08-18', sections: headings.map((heading, i) => ({ heading, body: paragraphs[i] })) };
};

export const august18BlogPosts: NewPost[] = [
  makePost('offshore-legal-support-client-portal-message-log', 'Client-portal message logging with offshore legal support', 'Organize portal messages, attachments, acknowledgments, and open questions while the firm controls advice and response approval.', 'client-portal message logging', 'portal-message logging workflow', 'a portal message contains a request that could be read as legal advice or a promise', 'source fidelity, attachment matching, response status, and escalation time', 'a client uploads a revised document after the original request was assigned'),
  makePost('law-firm-offshore-support-entity-name-normalization', 'Entity-name normalization support for law firms', 'Reconcile spelling and identifier variations for search and indexing without deciding whether two entities are legally the same.', 'entity-name normalization', 'name-reconciliation workflow', 'similar names, abbreviations, or registration identifiers could change an identity decision', 'source retention, match rationale, unresolved variants, and reviewer disposition', 'one corporate record uses a trading name while a filing uses a registered name'),
  makePost('offshore-legal-support-appointment-confirmation-record', 'Appointment-confirmation records for offshore legal support', 'Track approved scheduling details and confirmation evidence without promising availability, outcomes, or legal advice.', 'appointment-confirmation records', 'appointment-confirmation workflow', 'a caller asks for advice, an urgent response, or a commitment outside the approved script', 'calendar accuracy, time-zone clarity, approved wording, and escalation speed', 'a prospective client replies with facts that change the requested appointment type'),
  makePost('legal-support-offshore-document-version-reconciliation', 'Document-version reconciliation with offshore support', 'Compare named versions, source dates, and change notes while counsel decides which document is operative.', 'document-version reconciliation', 'version-reconciliation workflow', 'two versions appear complete but differ in a clause, signature, exhibit, or effective date', 'version identity, source links, comparison coverage, and unresolved-change routing', 'a signed PDF and a later editable file have the same filename'),
  makePost('offshore-legal-support-subpoena-service-log', 'Subpoena-service logging for offshore legal support', 'Record service facts, documents, recipients, and source evidence while counsel controls validity, response duties, and strategy.', 'subpoena-service logging', 'service-log workflow', 'a service record appears incomplete or someone asks whether a response deadline has started', 'service-source matching, date transcription, missing-field flags, and attorney handoff', 'a process server receipt lists a date but omits the method or recipient detail'),
  makePost('law-firm-offshore-support-client-identity-checklist', 'Client-identity checklist support for law firms', 'Prepare identity-check records from approved documents without deciding eligibility, fraud risk, or whether a matter may be accepted.', 'client-identity checklist support', 'identity-check workflow', 'documents conflict, appear expired, or raise a question about who may act for an organization', 'document identity, expiry capture, exception wording, and secure handling', 'the individual’s name differs across an ID, intake form, and authorization letter'),
  makePost('offshore-legal-support-court-notice-routing', 'Court-notice routing with offshore legal support', 'Route received court notices to the correct firm owner with source details intact, without calculating deadlines or giving advice.', 'court-notice routing', 'notice-routing workflow', 'a notice looks urgent, names an unfamiliar matter, or includes a date that could be mistaken for a deadline', 'recipient accuracy, source preservation, timestamp, and escalation response', 'a notice arrives in a general inbox after the assigned attorney is out'),
  makePost('legal-support-offshore-deadline-reminder-source-card', 'Source cards for legal deadline reminders', 'Create source-linked reminder cards from firm-approved dates while deadline interpretation stays with counsel.', 'deadline-reminder source cards', 'source-card workflow', 'a date is supplied without a rule, time zone, triggering event, or confirmation that it controls', 'source citation, date transcription, uncertainty labels, and review ownership', 'an order gives a date but the team has not confirmed how the period is calculated'),
  makePost('offshore-legal-support-client-document-request-tracker', 'Client-document request tracking with offshore support', 'Track requested records, received files, reminders, and gaps without deciding what evidence is legally sufficient.', 'client-document request tracking', 'document-request workflow', 'a client sends a substitute record or asks whether the material is enough for the matter', 'request wording, received-file identity, follow-up history, and reviewer disposition', 'a requested statement arrives as screenshots with no visible account period'),
  makePost('law-firm-offshore-support-agreement-signature-register', 'Agreement-signature registers for law firm support', 'Maintain signature status, version identity, delivery evidence, and missing pages while the firm controls execution and authority.', 'agreement-signature registers', 'signature-register workflow', 'the signer, version, authority, or completion status cannot be established from the source', 'version matching, signature-page checks, delivery evidence, and approval status', 'a counterparty returns a signed page from an earlier agreement draft'),
  makePost('offshore-legal-support-courier-chain-of-custody-log', 'Courier chain-of-custody logs for offshore legal support', 'Record transfers, package identifiers, timestamps, and receipt evidence without certifying authenticity or evidentiary effect.', 'courier chain-of-custody logging', 'transfer-log workflow', 'a package is delayed, opened, misaddressed, or recorded with conflicting transfer times', 'identifier continuity, timestamp source, handoff owner, and incident escalation', 'a delivery receipt is signed by a building desk rather than the named recipient'),
  makePost('legal-support-offshore-client-communication-index', 'Client-communication indexing with offshore support', 'Build a searchable index of approved communications while attorneys retain advice, commitments, and response decisions.', 'client-communication indexing', 'communication-index workflow', 'a message contains a substantive question, complaint, threat, or request for a new commitment', 'sender and recipient identity, attachment linkage, response owner, and open-state accuracy', 'a short text message refers to a matter but does not identify the requested action'),
  makePost('offshore-legal-support-document-translation-source-register', 'Translation source registers for legal support teams', 'Track original files, language labels, requested translations, and reviewer questions without treating a draft as approved legal meaning.', 'translation source registers', 'translation-register workflow', 'a term is ambiguous, the source is incomplete, or a recipient might rely on an unreviewed translation', 'source preservation, language certainty, version linkage, and reviewer sign-off', 'a scanned bilingual form contains a handwritten term absent from the typed copy'),
  makePost('law-firm-offshore-support-inspection-request-log', 'Inspection-request logs with offshore law firm support', 'Organize inspection requests, locations, contacts, and outcomes while the firm decides scope, rights, and next action.', 'inspection-request logging', 'inspection-log workflow', 'a location refuses access, proposes a substitute, or asks the support worker to interpret the request', 'request identity, approved wording, response evidence, and owner assignment', 'the requested site offers access to only part of the listed records'),
  makePost('offshore-legal-support-medical-record-request-tracker', 'Medical-record request tracking for offshore legal support', 'Track authorizations, providers, request dates, productions, and missing periods without drawing medical or legal conclusions.', 'medical-record request tracking', 'medical-record workflow', 'a provider returns partial records or the worker is asked whether the production is complete', 'authorization identity, provider response, date-range coverage, and escalation quality', 'a production includes billing pages but no clinical notes for the same period'),
  makePost('legal-support-offshore-corporate-filing-calendar-log', 'Corporate-filing calendar logs with offshore support', 'Maintain source-linked filing entries and owner handoffs while counsel decides obligations, jurisdictions, and deadline meaning.', 'corporate-filing calendar logs', 'filing-calendar workflow', 'a filing entry lacks a governing source or spans more than one jurisdiction', 'source date, jurisdiction label, owner, reminder state, and exception disposition', 'a company’s internal calendar and a government notice show different dates'),
  makePost('offshore-legal-support-insurance-notice-register', 'Insurance-notice registers for offshore legal support', 'Index notice sources, policy references, recipients, and follow-up status without deciding coverage, timeliness, or liability.', 'insurance-notice registers', 'notice-register workflow', 'a notice could affect coverage or asks the worker to characterize a claim position', 'notice identity, policy linkage, recipient, follow-up owner, and source accuracy', 'an insurer’s acknowledgment refers to a claim number not found in the matter file'),
  makePost('law-firm-offshore-support-decision-log-administration', 'Decision-log administration for law firm teams', 'Record authorized decisions, source instructions, owners, and effective versions without making the decisions yourself.', 'decision-log administration', 'decision-log workflow', 'a chat message conflicts with the approved instruction or does not identify an authorized decision-maker', 'decision wording, authority source, effective date, superseded entries, and auditability', 'a manager asks for a process change before the written approval is updated'),
  makePost('offshore-legal-support-client-consent-expiry-tracker', 'Client-consent expiry tracking with offshore support', 'Monitor consent dates, scope, renewals, and evidence while the firm determines legal sufficiency and permitted use.', 'client-consent expiry tracking', 'consent-tracking workflow', 'consent is conditional, expired, limited to one recipient, or silent about a changed purpose', 'scope transcription, expiry calculation source, renewal status, and release control', 'a client approved one document release but a later request adds another recipient'),
  makePost('legal-support-offshore-matter-owner-roster', 'Matter-owner roster maintenance for offshore support', 'Keep responsible attorney, manager, backup, and escalation contacts current without assigning legal responsibility by assumption.', 'matter-owner roster maintenance', 'owner-roster workflow', 'a matter has conflicting owners, an absent reviewer, or a request that crosses practice teams', 'source authority, effective dates, contact verification, and reassignment evidence', 'an out-of-office reply names a temporary contact but the matter system still shows the prior owner'),
  makePost('offshore-legal-support-remote-workspace-access-register', 'Remote-workspace access registers for legal support', 'Track user, workspace, permission, approval, and removal evidence while the firm owns access policy and security decisions.', 'remote-workspace access registers', 'access-register workflow', 'a worker needs broader access, a shared account appears, or a role changes before permissions are reviewed', 'named-account accuracy, approval source, least-access review, and removal timing', 'a new matter folder is copied from a template that carries an inherited permission'),
  makePost('law-firm-offshore-support-client-referral-log', 'Client-referral logs for law firm support teams', 'Record referral source, consent, routing, and follow-up status without promising acceptance, suitability, or a legal outcome.', 'client-referral logging', 'referral-log workflow', 'a referral includes sensitive facts or asks the support worker to recommend a lawyer or service', 'consent evidence, routing accuracy, contact status, and escalation notes', 'a referral partner sends a prospective client’s records before the firm confirms receipt rules'),
];

