type Section = { heading: string; body: string };
type Post = { slug: string; title: string; excerpt: string; minutes: number; published: '2026-08-20'; sourceDate: '2026-08-20'; sections: Section[] };

const common = (focus: string, detail: string): Section[] => [
  { heading: 'Define the administrative question', body: `A useful offshore legal support workflow begins with a question that can be answered from identified records: ${focus}. The request should name the matter, source system, requested period, expected output, reviewer, and stop condition. A worker should not have to infer whether the assignment is preparation, comparison, follow-up, or a decision. Write the requested result in observable terms, such as an indexed set, a dated exception list, or a draft built from approved fields. That precision protects the firm from a broad instruction becoming unauthorized legal work and gives the reviewer a fair way to inspect what was done.` },
  { heading: 'Start with a controlled source set', body: `Before work begins, record which materials govern ${focus}. Preserve the supplied version, identifier, date received, and location. If a source is missing, locked, duplicated, or inconsistent, log the condition instead of finding an unofficial substitute. Offshore legal support is strongest when provenance remains visible: a reviewer can trace each prepared line back to the record that supplied it. Keep working copies separate from originals and do not overwrite a source to make the output look complete. The firm decides whether a source is authoritative, current, sufficient, or safe to disclose.` },
  { heading: 'Use a narrow first lane', body: `Pilot ${focus} with one repeatable task and a small approved sample. Select examples that include a normal record, a missing field, a duplicate, and an exception that requires escalation. The point of a pilot is to test the instruction and reviewer route, not to prove a result about legal quality. Give the worker a clear input boundary and a defined handoff. If the sample reveals that every item requires interpretation, redesign the lane or keep it with the firm. A narrow lane is easier to supervise than a role described as general legal help.` },
  { heading: 'Make exceptions more useful than guesses', body: `The output for ${focus} should show what was found, what could not be confirmed, and who owns the next decision. Use neutral labels such as missing source, conflicting identifier, unclear instruction, restricted access, or reviewer question. Do not convert “not located” into “does not exist,” and do not turn a received file into a conclusion that it is sufficient. A precise exception saves attorney time because it identifies the exact item and the evidence already checked. Escalation is a completed support action when the role has reached its boundary.` },
  { heading: 'Keep the role boundary explicit', body: `For ${focus}, support staff may collect, organize, compare, format, label, and route approved information. The firm retains legal advice, strategy, privilege, conflict decisions, deadline calculations, filing approval, settlement authority, trust-account actions, and final client communication. Put those limits beside the checklist rather than in a distant policy. A worker should know what to do when a client asks a new question, when a document changes the apparent issue, or when a task needs wider access. The correct response is to preserve the question and use the named escalation path.` },
  { heading: 'Design the handoff around evidence', body: `A reviewer receiving ${focus} needs the request, source list, prepared output, exceptions, version information, and a specific decision request. Avoid a long narrative that mixes source facts with interpretation. State which checks were completed and which were not possible. Record the handoff time and recipient using the firm’s approved system. The reviewer can then accept, correct, return, or redirect the work without reconstructing the process from chat messages. A handoff is not approval; it is a controlled transfer of preparation to the person who owns judgment.` },
  { heading: 'Protect information while work moves', body: `Access for ${focus} should follow the minimum data and action required. Use named accounts, matter-specific permissions, approved storage, and separate read and write rights where the tools allow it. Do not copy sensitive records into a broad channel to resolve a simple question. If a wrong matter, unexpected recipient, or unapproved permission appears, stop and report the visible facts. The firm decides containment, notification, remediation, and legal significance. Offshore legal support should improve access discipline, not create a second uncontrolled repository.` },
  { heading: 'Measure the process, not a legal result', body: `A manager can review ${focus} through measures such as source-link completeness, missing-field rate, rework reason, escalation timeliness, reviewer turnaround, and unresolved-item age. Define each measure before collecting it and keep examples of what is excluded. Do not present task volume as proof of legal quality, client outcome, compliance, or savings. A backlog may show reviewer capacity or an intentional hold. Use a small sample to find unclear instructions and recurring source failures, then change the checklist through an authorized owner with a visible effective date.` },
  { heading: 'Rehearse the difficult handoff', body: `Test ${focus} with a record that has two similar names, an amended version, an incomplete attachment, and a request that crosses into legal judgment. The worker should identify the conflict, preserve both sources, pause the affected step, and route one precise question. The reviewer should be able to tell whether the issue came from the source, the instruction, the system, or the output. Rehearsal is valuable because ordinary edge cases expose hidden assumptions. Keep the test result with the workflow version and use it to refine training examples.` },
  { heading: 'Close with an authorized disposition', body: `Do not close ${focus} merely because the worker produced a file or sent a reminder. The final status should say whether the item was accepted for review, returned for correction, held for missing information, redirected, withdrawn, or closed by a named owner. Preserve the original request, source references, corrections, and unresolved questions. LegalServicesOffshore.com’s practical boundary is simple: offshore support creates a reliable administrative record and a clearer queue; the law firm remains responsible for professional judgment, supervision, confidentiality, and release.` },
];

const specs = [
  ['offshore-legal-support-intake-escalation-matrix', 'Intake escalation matrices for offshore legal support', 'Turn intake signals into a factual routing matrix while the firm keeps conflicts, advice, urgency, and acceptance decisions.', 'new inquiry routing and escalation'],
  ['law-firm-offshore-support-matter-folder-governance', 'Matter-folder governance with offshore legal support', 'Keep matter folders findable, permissioned, and source-linked without allowing administrative cleanup to change the record.', 'matter-folder naming, access, and version control'],
  ['offshore-legal-support-hearing-preparation-source-board', 'Hearing-preparation source boards with offshore support', 'Organize supplied hearing details, documents, and open questions while counsel controls deadlines and advocacy.', 'hearing-preparation source tracking'],
  ['legal-support-offshore-client-identity-resolution-log', 'Client-identity resolution logs for offshore legal support', 'Record identity questions and approved evidence without deciding representation, conflicts, or the legal relationship.', 'client-identity discrepancy handling'],
  ['offshore-legal-support-records-request-coverage-map', 'Records-request coverage maps for offshore legal support', 'Show which requested records arrived, which sources were checked, and which gaps need a firm decision.', 'records-request coverage and gap mapping'],
  ['law-firm-offshore-support-amendment-version-register', 'Agreement-amendment version registers with offshore support', 'Connect amendments, notices, and executed versions while counsel interprets effect and obligations.', 'agreement amendment version control'],
  ['offshore-legal-support-disclosure-packet-checklist', 'Disclosure-packet checklists for offshore legal support', 'Prepare a traceable packet check while attorneys decide scope, privilege, redaction, and release.', 'disclosure-packet completeness checking'],
  ['legal-support-offshore-court-correspondence-index', 'Court-correspondence indexes for offshore legal support', 'Keep court messages, attachments, recipients, and handoffs reviewable without calculating legal deadlines.', 'court correspondence indexing'],
  ['offshore-legal-support-vendor-records-reconciliation', 'Vendor-record reconciliation for offshore legal support', 'Compare approved vendor records and matter references while authorized staff decide payment, dispute, and release.', 'vendor-record reconciliation'],
  ['law-firm-offshore-support-client-call-fact-log', 'Client-call fact logs with offshore legal support', 'Capture supplied call facts and follow-up questions without giving advice or promising an outcome.', 'client-call factual logging'],
  ['offshore-legal-support-retention-exception-register', 'Retention-exception registers for offshore legal support', 'Track retention instructions and missing records while the firm owns legal holds and disposition decisions.', 'retention exception tracking'],
  ['legal-support-offshore-review-capacity-board', 'Review-capacity boards for offshore legal support', 'Show prepared work waiting for review without treating queue movement as legal approval or quality proof.', 'review-capacity and handoff management'],
] as const;

export const august20BlogPosts: Post[] = specs.map(([slug, title, excerpt, focus]) => ({
  slug, title, excerpt, minutes: 11, published: '2026-08-20', sourceDate: '2026-08-20', sections: common(focus, title),
}));
