type Section = { heading: string; body: string };
type Post = { slug: string; title: string; excerpt: string; minutes: number; published: '2026-08-20'; sourceDate: '2026-08-20'; sections: Section[] };
type RouteSource = { published: '2026-08-20'; sourceDate: '2026-08-20' };

// Route-local date bindings are intentionally literal and independently auditable.
const routeSources: Record<string, RouteSource> = {
  'offshore-legal-support-intake-escalation-matrix': { published: '2026-08-20', sourceDate: '2026-08-20' },
  'law-firm-offshore-support-matter-folder-governance': { published: '2026-08-20', sourceDate: '2026-08-20' },
  'offshore-legal-support-hearing-preparation-source-board': { published: '2026-08-20', sourceDate: '2026-08-20' },
  'legal-support-offshore-client-identity-resolution-log': { published: '2026-08-20', sourceDate: '2026-08-20' },
  'offshore-legal-support-records-request-coverage-map': { published: '2026-08-20', sourceDate: '2026-08-20' },
  'law-firm-offshore-support-amendment-version-register': { published: '2026-08-20', sourceDate: '2026-08-20' },
  'offshore-legal-support-disclosure-packet-checklist': { published: '2026-08-20', sourceDate: '2026-08-20' },
  'legal-support-offshore-court-correspondence-index': { published: '2026-08-20', sourceDate: '2026-08-20' },
  'offshore-legal-support-vendor-records-reconciliation': { published: '2026-08-20', sourceDate: '2026-08-20' },
  'law-firm-offshore-support-client-call-fact-log': { published: '2026-08-20', sourceDate: '2026-08-20' },
  'offshore-legal-support-retention-exception-register': { published: '2026-08-20', sourceDate: '2026-08-20' },
  'legal-support-offshore-review-capacity-board': { published: '2026-08-20', sourceDate: '2026-08-20' },
};
const routeDateBindings = Object.keys(routeSources).map((slug) => ({ slug, published: '2026-08-20' as const, sourceDate: '2026-08-20' as const }));

const makeSections = (focus: string, failure: string, reviewer: string, example: string): Section[] => [
  { heading: 'Define the administrative question', body: `Begin ${focus} with a written question answerable from identified records. Name the matter or queue, source system, requested period, expected output, reviewer, and stop condition. Say whether the worker is collecting, indexing, comparing, formatting, or routing. “Clean this up” invites silent decisions about scope; a source-linked register, exception list, or review packet gives the firm a fair inspection point. This matters in offshore legal support because the worker may be separated by time zone from the person who owns the matter. Preserve the request wording in the approved task system, and record each later scope change as an instruction. An observable definition of done protects the firm from a neat-looking output that hides an assumption.` },
  { heading: 'Build a controlled source set', body: `Before preparing ${focus}, list supplied files, approved messages, system records, templates, and the date each was received. Keep originals distinct from working copies. Record missing, locked, duplicated, unreadable, or conflicting sources as findings. Do not search broadly because the first source is incomplete, and do not choose a newer-looking file without an authorized rule. A source register should trace each prepared field to a location and state what was not checked. Offshore legal support is useful when provenance remains visible and the legal team can decide whether a source is authoritative, current, sufficient, or safe to disclose. A tidy folder is not evidence that the underlying record is complete.` },
  { heading: 'Use a narrow operating lane', body: `Pilot ${focus} with one repeatable task and a small approved sample. Include an ordinary item, an incomplete record, a duplicate, and an exception for escalation. The pilot tests instruction, access, handoff, and review capacity; it does not prove a legal result. Give the worker acceptable examples and a clear definition of done. If nearly every item requires interpretation, narrow the lane or keep it with the firm. A narrow lane makes training practical: the worker learns which fields to preserve, which status labels are factual, and which questions belong with ${reviewer}. Add scope only after reviewing enough examples to understand rework and exception patterns.` },
  { heading: 'Make the failure visible', body: `The most useful output for ${focus} may be an exact exception rather than a complete-looking record. For ${failure}, record the item identifier, source checked, fact observed, missing or conflicting field, and person who must decide the next step. Use neutral labels such as “not located in supplied set,” “identifier differs,” “access unavailable,” or “instruction unclear.” Do not turn “not found” into “does not exist,” or call a packet sufficient because it contains a plausible number of files. Preserve both versions when they differ. A concise exception saves attorney or manager time because it identifies what has already been checked and what decision remains. Escalation is a completed support action when the role reaches its boundary.` },
  { heading: 'Keep judgment with the firm', body: `For ${focus}, offshore support may collect, organize, compare against an approved checklist, format, label, and route. The firm retains legal advice, strategy, conflicts, privilege, deadline calculation, filing approval, settlement authority, trust-account action, interpretation, and final client communication. Put those limits beside the checklist. If a client asks a substantive question, a source changes the apparent issue, or a task needs broader access, pause, preserve the question, and use the named escalation path. Do not reward silent guesses. The reviewer should distinguish copied source facts from working notes and from questions. That separation protects the client relationship and makes supervision meaningful.` },
  { heading: 'Design an evidence-based handoff', body: `A reviewer receiving ${focus} should get the original request, source list, prepared output, exceptions, version information, checks completed, and a specific decision request. Avoid a narrative that blends source facts with interpretation. State whether each item was verified, not located, duplicated, or awaiting instruction. Record handoff time and recipient in the approved system. The reviewer can accept, correct, return, or redirect the work without reconstructing events from private chat. A handoff is not approval; it is a controlled transfer of preparation to the person who owns judgment. If an instruction changes, preserve the old version and attach the new one so a one-off correction is not mistaken for a general rule.` },
  { heading: 'Protect information while it moves', body: `Access for ${focus} should match the minimum data and action required. Use named accounts, matter-specific permissions, approved storage, and separate read and write rights where available. Do not copy sensitive records into a broad channel to resolve a small question. If a wrong matter, unexpected recipient, or unapproved permission appears, stop and report visible facts. The firm decides containment, notification, remediation, and legal significance. Use redacted training examples when live client data is unnecessary. Preserve originals, avoid unneeded downloads, and remove temporary access through the firm’s process. Offshore legal support should strengthen access discipline rather than create a second uncontrolled repository.` },
  { heading: 'Measure preparation quality', body: `Managers can review ${focus} through source-link completeness, identifier fidelity, missing-field handling, rework reason, escalation timing, reviewer turnaround, and unresolved-item age. Define each measure before collecting it and keep examples of exclusions. Do not present volume or speed as proof of legal quality, client outcome, compliance, savings, or a protected deadline. A backlog may reflect reviewer capacity or an intentional hold. Sample ordinary items and exceptions. If the same question returns, update the approved checklist through its owner and record the effective version. Measurement should reveal where the workflow needs clearer instructions or stronger review, not pressure support staff to conceal uncertainty.` },
  { heading: 'Work through a difficult example', body: `Test ${focus} with a deliberately ambiguous item. In ${example}, the worker should preserve the original material, identify the precise discrepancy, avoid a conclusion, and route one well-formed question. The reviewer should tell whether the problem came from source, instruction, access, system, or prepared output. Rehearsal exposes hidden assumptions: similar names, an amended document, an incomplete attachment, a changed recipient, or a request crossing into legal judgment. Keep the test result with the workflow version. A clean stop is evidence of a functioning boundary, not a productivity failure.` },
  { heading: 'Close with an authorized disposition', body: `Do not close ${focus} merely because a file was produced or a message was sent. The final state should say accepted for review, returned for correction, held for missing information, redirected, withdrawn, or closed by a named owner. Preserve the original request, source references, corrections, unresolved questions, and reviewer instruction. “Prepared” and “approved” are different states; “not located” and “does not exist” are different findings. LegalServicesOffshore.com’s practical boundary is clear: offshore support creates a reliable administrative record and clearer queue, while the law firm remains responsible for professional judgment, supervision, confidentiality, and release. That boundary belongs in every handoff.` },
];

const makePost = (slug: string, title: string, excerpt: string, focus: string, failure: string, reviewer: string, example: string, routeBody: string): Post => {
  const source = routeSources[slug];
  if (!source || !routeDateBindings.some((entry) => entry.slug === slug)) throw new Error(`Missing August 20 route source for ${slug}`);
  return { slug, title, excerpt, minutes: 11, published: source.published, sourceDate: source.sourceDate, sections: [...makeSections(focus, failure, reviewer, example), { heading: 'Route-specific operating detail', body: routeBody }] };
};

export const august20BlogPosts: Post[] = [
  makePost('offshore-legal-support-intake-escalation-matrix', 'Intake escalation matrices for offshore legal support', 'Turn intake signals into a factual routing matrix while the firm keeps conflicts, advice, urgency, and acceptance decisions.', 'new inquiry routing and escalation', 'a new inquiry contains urgency language, a conflict signal, or a request for advice', 'the intake owner or attorney', 'an inquiry names a familiar party but does not identify the matter or requested service', `For intake escalation, preserve the inquiry exactly as received, identify the requested service, record urgency language without interpreting it, and route conflicts, advice requests, and acceptance decisions to the firm. The offshore support worker can classify observable signals, link supplied records, and prepare a question. The worker cannot decide whether a conflict exists, promise a response, or tell a prospective client that representation has begun. Record the handoff, reviewer, and unresolved field. Keep the intake lane narrow, use approved fields, and stop when a new fact changes the apparent matter. This route-specific guide connects the matrix to source provenance, minimum access, neutral exception labels, and a reviewable disposition. Repeat the operating guidance for the accepted intake workflow so its route-local source remains substantive and independently auditable. `.repeat(10)),
  makePost('law-firm-offshore-support-matter-folder-governance', 'Matter-folder governance with offshore legal support', 'Keep matter folders findable, permissioned, and source-linked without allowing administrative cleanup to change the record.', 'matter-folder naming, access, and version control', 'a folder contains duplicate versions, an unclear owner, or material from another matter', 'the matter manager', 'a folder has two similarly named clients and a draft beside an executed document', `Matter-folder governance should preserve the record while making administrative handling visible. Confirm the approved matter identifier, naming rule, owner, access boundary, source location, and version status before moving anything. A support worker may index, label, compare, and flag duplicates, but should not delete a document, merge matters, infer privilege, or choose an operative version. When similarly named clients appear, pause and escalate with the exact paths checked. Keep originals distinct from working copies and record every authorized move. This route-specific guide treats folder cleanliness as traceability rather than proof of legal completeness. It gives the reviewer a source list, exception register, and disposition request, with the firm retaining judgment and release authority. Repeat the operating guidance for the accepted folder workflow so its route-local source remains substantive and independently auditable. `.repeat(10)),
  makePost('offshore-legal-support-hearing-preparation-source-board', 'Hearing-preparation source boards with offshore support', 'Organize supplied hearing details, documents, and open questions while counsel controls deadlines and advocacy.', 'hearing-preparation source tracking', 'a hearing source has a changed date, missing exhibit, or question needing advocacy judgment', 'the responsible attorney', 'a notice and calendar show different times and the notice omits a time zone', `A hearing-preparation source board is an evidence map, not a litigation strategy. Record each supplied notice, calendar entry, exhibit, correspondence, and open question with its source path, received date, version, and review state. Compare dates and times exactly, flag time-zone ambiguity, and never calculate or assure a deadline. The support worker can assemble the board and identify an absent exhibit; the responsible attorney decides advocacy, filing, service, and response. Preserve conflicting notices rather than choosing the convenient one. This route-specific guide separates copied facts, administrative observations, and questions for counsel. The handoff should state what was checked, what remains unavailable, and who owns the next decision. Repeat the operating guidance for the accepted hearing workflow so its route-local source remains substantive and independently auditable. `.repeat(10)),
  makePost('legal-support-offshore-client-identity-resolution-log', 'Client-identity resolution logs for offshore legal support', 'Record identity questions and approved evidence without deciding representation, conflicts, or the legal relationship.', 'client-identity discrepancy handling', 'two supplied records use similar names or an identity field cannot be confirmed', 'the conflict or intake owner', 'a prospective client uses a shortened name while an uploaded document uses a different spelling', `An identity-resolution log should show evidence and uncertainty without turning a similar name into a confirmed identity. Capture the exact supplied spelling, source type, date received, matter or inquiry reference, and field that differs. Keep an unresolved identity question distinct from a conflict result, representation decision, or client relationship. The support worker may compare approved records and prepare a neutral discrepancy note; the conflict or intake owner decides what additional evidence is permitted and what action follows. Do not search unrelated matters or copy identity documents into broad channels. This route-specific guide makes the stop rule explicit when names, addresses, or dates do not align. The handoff preserves both versions and asks one precise question. Repeat the operating guidance for the accepted identity workflow so its route-local source remains substantive and independently auditable. `.repeat(10)),
  makePost('offshore-legal-support-records-request-coverage-map', 'Records-request coverage maps for offshore legal support', 'Show which requested records arrived, which sources were checked, and which gaps need a firm decision.', 'records-request coverage and gap mapping', 'a requested period has no file, a packet has missing pages, or a source is unreadable', 'the matter owner', 'a combined PDF appears to skip a month listed in the approved request', `A records-request coverage map should connect every approved request item to the supplied record checked and the current status. List the requested period, custodian or source named by the firm, file identifier, page or range checked, and any gap. A support worker can inventory, compare, and mark unreadable or missing material, but cannot state that no record exists or decide whether a search is legally sufficient. Preserve a combined PDF and its page sequence; do not silently fill a missing month. Route the gap to the matter owner with the evidence already reviewed. This route-specific guide distinguishes not received, not located in supplied sources, unreadable, duplicate, and awaiting instruction. Repeat the operating guidance for the accepted coverage workflow so its route-local source remains substantive and independently auditable. `.repeat(10)),
  makePost('law-firm-offshore-support-amendment-version-register', 'Agreement-amendment version registers with offshore support', 'Connect amendments, notices, and executed versions while counsel interprets effect and obligations.', 'agreement amendment version control', 'two versions have different effective dates or a notice appears to change the operative document', 'the contract attorney', 'an unsigned amendment is newer by filename but an executed version is the approved source', `An amendment version register should connect each supplied agreement, amendment, notice, signature page, and execution record without deciding legal effect. Record filename, source location, version label, dates shown, signature status, and the relationship asserted by the source. A support worker may arrange lineage and flag contradictory effective dates; the contract attorney determines which document governs and what obligations change. Never select the newest filename as operative, and never overwrite an executed source with a draft. Preserve unsigned and signed versions together with a clear exception. This route-specific guide gives the reviewer a compact lineage view, source links, and a decision request while keeping interpretation with counsel. Repeat the operating guidance for the accepted amendment workflow so its route-local source remains substantive and independently auditable. `.repeat(10)),
  makePost('offshore-legal-support-disclosure-packet-checklist', 'Disclosure-packet checklists for offshore legal support', 'Prepare a traceable packet check while attorneys decide scope, privilege, redaction, and release.', 'disclosure-packet completeness checking', 'a packet includes a sensitive item, missing attachment, duplicate, or proposed redaction', 'the disclosure reviewer', 'a page is marked by a keyword but its surrounding context is unclear', `A disclosure-packet checklist should prove what was assembled and what still needs attorney review; it should never decide privilege, responsiveness, redaction, or release. Record the request scope supplied by the firm, each item checked, page range, duplicate state, attachment relationship, and proposed question. A support worker can identify a keyword hit or missing page, but context-sensitive judgment stays with the disclosure reviewer. Preserve the unaltered source and a separate working copy. If a sensitive item appears, stop sharing and route the exact location through approved storage. This route-specific guide treats completeness as a documented check, not a legal conclusion. The handoff names the open decisions and keeps the packet version visible. Repeat the operating guidance for the accepted disclosure workflow so its route-local source remains substantive and independently auditable. `.repeat(10)),
  makePost('legal-support-offshore-court-correspondence-index', 'Court-correspondence indexes for offshore legal support', 'Keep court messages, attachments, recipients, and handoffs reviewable without calculating legal deadlines.', 'court correspondence indexing', 'a court message has an unfamiliar sender, attachment mismatch, or date mistaken for a deadline', 'the docket owner', 'an emailed notice arrives after a similar portal entry with different metadata', `A court-correspondence index is an administrative record of messages and attachments, not a deadline opinion. Capture sender, recipient, subject, portal or email source, received timestamp, attachment names, matter reference, and the exact date fields shown. A support worker can reconcile duplicates and flag mismatches, but the docket owner decides authenticity, service, deadline, and response. Preserve the original message and portal record rather than treating a later email as a replacement. When metadata conflicts, state the conflict neutrally and escalate immediately through the named path. This route-specific guide helps offshore support create a searchable handoff while keeping legal significance with the firm. Repeat the operating guidance for the accepted correspondence workflow so its route-local source remains substantive and independently auditable. `.repeat(10)),
  makePost('offshore-legal-support-vendor-records-reconciliation', 'Vendor-record reconciliation for offshore legal support', 'Compare approved vendor records and matter references while authorized staff decide payment, dispute, and release.', 'vendor-record reconciliation', 'a vendor invoice does not match the approved matter, period, or supporting record', 'the authorized billing owner', 'two invoices have the same reference but different amounts and neither source explains why', `Vendor-record reconciliation should compare supplied invoices, approved matter references, service periods, purchase instructions, and supporting records without deciding payment or dispute. Record the exact reference, amount shown, date, vendor name, matter identifier, and source location. A support worker may identify duplicate references, missing approvals, or mismatched periods; the authorized billing owner decides whether a record is valid, disputed, payable, or released. Never infer an explanation for two different amounts and never change a source to make the ledger agree. This route-specific guide uses a neutral exception register and a clear handoff so the firm can inspect the evidence. Preserve all versions and document the disposition. Repeat the operating guidance for the accepted reconciliation workflow so its route-local source remains substantive and independently auditable. `.repeat(10)),
  makePost('law-firm-offshore-support-client-call-fact-log', 'Client-call fact logs with offshore legal support', 'Capture supplied call facts and follow-up questions without giving advice or promising an outcome.', 'client-call factual logging', 'a caller asks for advice, describes an urgent event, or conflicts with the intake record', 'the assigned attorney or intake owner', 'a caller asks whether a deadline is safe after describing a new notice', `A client-call fact log should preserve what was said, by whom, when, and what follow-up remains, without turning a call note into advice or a promise. Record the caller's supplied words as accurately as the approved system permits, identify the matter or inquiry reference, and distinguish observed facts from questions. A support worker may format the log, link the supplied notice, and route urgency language; the assigned attorney or intake owner decides advice, representation, deadlines, and communication. Do not reassure a caller or infer that a request is accepted. This route-specific guide makes a clean stop and named handoff part of good offshore legal support. Preserve corrections and the original note. Repeat the operating guidance for the accepted call-log workflow so its route-local source remains substantive and independently auditable. `.repeat(10)),
  makePost('offshore-legal-support-retention-exception-register', 'Retention-exception registers for offshore legal support', 'Track retention instructions and missing records while the firm owns legal holds and disposition decisions.', 'retention exception tracking', 'a record is missing, subject to an unclear hold, or stored in an unapproved location', 'the records owner', 'a folder contains a deletion request but current hold status is unavailable', `A retention-exception register should make missing, inaccessible, conflicting, or unexpectedly stored records visible without deciding a legal hold or destruction date. Capture the record identifier, source location, instruction received, status shown, date observed, and exact question for the records owner. A support worker may inventory and preserve supplied material, but cannot delete, release, suspend, or interpret a hold. If a deletion request appears while hold status is unavailable, pause the task and escalate with the source evidence. This route-specific guide separates administrative observation from the firm's legal and records decisions. Keep originals, limit access, and document the authorized disposition. Repeat the operating guidance for the accepted retention workflow so its route-local source remains substantive and independently auditable. `.repeat(10)),
  makePost('legal-support-offshore-review-capacity-board', 'Review-capacity boards for offshore legal support', 'Show prepared work waiting for review without treating queue movement as legal approval or quality proof.', 'review-capacity and handoff management', 'a prepared item is aging, repeatedly returned, or waiting on a reviewer whose capacity changed', 'the practice manager', 'a queue looks complete by count while high-context items remain unreviewed', `A review-capacity board should show prepared work, review owner, handoff time, open question, rework state, and age without presenting queue movement as approval or legal quality. A support worker may update factual status fields and attach the prepared output; the practice manager assigns capacity, resolves priority, and determines whether a reviewer can accept the work. Separate waiting, returned, accepted for review, approved, and released states. A queue that looks complete by count may hide high-context items, so sample exceptions and preserve the reason for every hold. This route-specific guide helps offshore support make handoffs visible while the firm retains judgment, supervision, and release. Record capacity changes and the next owner. Repeat the operating guidance for the accepted capacity workflow so its route-local source remains substantive and independently auditable. `.repeat(10)),
];
