type Topic = {
  slug: string;
  title: string;
  excerpt: string;
  lens: string;
  input: string;
  output: string;
  owner: string;
  risk: string;
  first: string;
  review: string;
  question: string;
};

const topics: Topic[] = [
  { slug: 'offshore-legal-support-deadline-source-checks', title: 'Deadline source checks for offshore legal support', excerpt: 'Create a factual date register from approved notices and orders while the firm retains deadline calculation and response decisions.', lens: 'deadline source checks', input: 'orders, notices, docket entries, and firm-approved calendar instructions', output: 'a dated register with source links, timezone notes, and unresolved conflicts', owner: 'the docket owner or attorney', risk: 'a copied date being mistaken for a calculated legal deadline', first: 'one matter with a small set of already-reviewed source documents', review: 'compare every date to its source and explain any mismatch before release', question: 'Which source controls when two documents show different dates?' },
  { slug: 'law-firm-offshore-support-intake-routing-matrix', title: 'Intake routing matrices for law-firm offshore support', excerpt: 'Turn approved intake signals into a visible route without letting administrative triage become legal advice or an acceptance decision.', lens: 'intake routing matrices', input: 'approved call notes, web inquiries, conflict fields, and urgency signals', output: 'a route record showing the receiving owner, missing facts, and time sent', owner: 'the intake manager or designated attorney', risk: 'an administrative label being treated as a promise or legal assessment', first: 'a redacted sample of each intake category the firm actually receives', review: 'sample routes for accuracy, tone, speed, and escalation discipline', question: 'What exact fact sends an inquiry to a human reviewer immediately?' },
  { slug: 'legal-support-offshore-document-version-ledgers', title: 'Document-version ledgers for legal support offshore', excerpt: 'Keep drafts, approved copies, and superseded files traceable while attorneys decide which language is authoritative.', lens: 'document-version ledgers', input: 'firm-approved filenames, document metadata, amendment notices, and source folders', output: 'a lineage log connecting each working copy to its source and status', owner: 'the matter manager and substantive reviewer', risk: 'a newer-looking file being used without confirming approval', first: 'one document type with a known folder and clear version examples', review: 'inspect the lineage, status labels, and source preservation on every sample', question: 'Who can mark a draft approved, and what evidence supports that status?' },
  { slug: 'offshore-legal-support-discovery-custodian-index', title: 'Discovery custodian indexes with offshore legal support', excerpt: 'Organize custodian information and collection questions without deciding relevance, responsiveness, privilege, or production scope.', lens: 'discovery custodian indexes', input: 'approved custodian lists, collection notes, mailbox names, and source-system exports', output: 'a searchable index with collection state, gaps, and exact source references', owner: 'the discovery lead or supervising attorney', risk: 'a missing source being silently treated as a complete collection', first: 'a closed sample collection with a known expected inventory', review: 'check identity fields, source coverage, duplicates, and exception wording', question: 'What collection instruction is missing before this item can move forward?' },
  { slug: 'law-firm-offshore-support-client-update-digests', title: 'Client-update digests prepared with offshore law firm support', excerpt: 'Assemble factual progress notes for review while lawyers retain control of advice, expectations, and every client-facing promise.', lens: 'client-update digests', input: 'approved matter notes, completed-task records, dates, and open questions', output: 'a concise internal digest with sources and a separate review queue', owner: 'the supervising attorney or client-team manager', risk: 'a neutral status note sounding like advice, certainty, or a guarantee', first: 'one matter where the firm already has an approved update format', review: 'remove inference, check dates, and confirm each sentence has a source', question: 'Which statement requires attorney wording rather than administrative summarizing?' },
  { slug: 'legal-support-offshore-billing-exception-queues', title: 'Billing exception queues for offshore legal support', excerpt: 'Find missing fields and inconsistent entries while the firm controls billability, write-offs, invoice release, and client communications.', lens: 'billing exception queues', input: 'time entries, matter codes, billing rules, approved narratives, and invoice calendars', output: 'an exception queue that names the exact field or source needing review', owner: 'the billing manager or responsible attorney', risk: 'a cleanup edit changing the lawyer’s meaning or billing judgment', first: 'a prior invoice batch with known examples of accepted and rejected entries', review: 'measure false flags, missed gaps, and whether original entries remain preserved', question: 'Is this a formatting defect, or does resolving it require a billing decision?' },
  { slug: 'offshore-legal-support-privileged-folder-permissions', title: 'Privileged-folder permission reviews for offshore legal support', excerpt: 'Review access lists against approved matter roles while the firm decides privilege, confidentiality, and incident response.', lens: 'privileged-folder permission reviews', input: 'named-user lists, matter assignments, folder groups, and access requests', output: 'a review sheet showing expected access, observed access, and escalation state', owner: 'the firm’s security or matter administrator', risk: 'removing or granting access without preserving the authorized decision', first: 'a non-production access export and an approved role matrix', review: 'confirm every exception has an owner, timestamp, evidence, and next action', question: 'What documented instruction permits this person to see this matter?' },
  { slug: 'law-firm-offshore-support-legal-research-request-logs', title: 'Legal-research request logs for offshore law-firm support', excerpt: 'Track research assignments, source boundaries, and review questions without presenting administrative research as legal advice.', lens: 'legal-research request logs', input: 'attorney questions, jurisdiction limits, source lists, and requested delivery dates', output: 'a research log separating retrieved material from attorney analysis', owner: 'the assigning attorney', risk: 'a search result being presented as a conclusion or current legal answer', first: 'a narrow question with a defined jurisdiction and approved source set', review: 'check citations, scope, date, and the boundary between finding and interpretation', question: 'What part of this request must be answered or rewritten by counsel?' },
  { slug: 'offshore-legal-support-hearing-preparation-checklists', title: 'Hearing-preparation checklists with offshore legal support', excerpt: 'Assemble logistics and approved materials while counsel controls argument, witness preparation, and courtroom decisions.', lens: 'hearing-preparation checklists', input: 'hearing notices, approved exhibit lists, logistics instructions, and contact details', output: 'a readiness checklist with sources, confirmations, and open items', owner: 'the hearing attorney or litigation manager', risk: 'a logistics checklist being mistaken for a complete legal preparation plan', first: 'one past hearing packet with its final approved checklist', review: 'verify source dates, participants, exhibits, technology, and unresolved items', question: 'Which open item is logistical, and which requires a substantive decision?' },
  { slug: 'legal-support-offshore-matter-closeout-records', title: 'Matter-closeout records for legal support offshore', excerpt: 'Prepare a factual closeout packet for review without deciding retention, client notice, trust treatment, or the end of legal responsibility.', lens: 'matter-closeout records', input: 'approved closeout instructions, open-task lists, file inventories, and correspondence logs', output: 'a closeout packet showing completed checks, gaps, and proposed owners', owner: 'the matter owner and records administrator', risk: 'an administrative checklist being treated as authorization to close a matter', first: 'a completed matter with a known disposition and retained source set', review: 'sample packet completeness, unresolved tasks, and access changes before closure', question: 'Who authorizes the matter’s final status and what remains outside this checklist?' },
  { slug: 'law-firm-offshore-support-translation-intake-registers', title: 'Translation-intake registers for offshore legal support', excerpt: 'Track language needs, source documents, and reviewer questions while qualified reviewers control meaning and legal use.', lens: 'translation-intake registers', input: 'original documents, language observations, client instructions, and translation requests', output: 'a register preserving originals, requested scope, status, and reviewer ownership', owner: 'the attorney and qualified language reviewer', risk: 'an informal summary being labeled a complete or certified translation', first: 'a small set of documents with known language and review outcomes', review: 'check source preservation, page counts, status labels, and ambiguity notes', question: 'Who is qualified and authorized to approve the translated meaning?' },
  { slug: 'offshore-legal-support-vendor-evidence-trackers', title: 'Vendor-evidence trackers for offshore legal support', excerpt: 'Organize certificates, invoices, contacts, and delivery records while the firm decides contractual sufficiency and dispute position.', lens: 'vendor-evidence trackers', input: 'contracts, purchase records, vendor messages, certificates, and delivery confirmations', output: 'an evidence tracker with source dates, requested items, and exceptions', owner: 'the contract owner or supervising attorney', risk: 'an absent document being interpreted as a breach or admission', first: 'one vendor relationship with a complete historical folder', review: 'test source links, status definitions, date handling, and escalation notes', question: 'What does the agreement require, and who is authorized to interpret that requirement?' },
];

function sections(t: Topic) {
  return [
    { heading: `Why ${t.lens} needs a narrow lane`, body: `A useful offshore legal support role begins with a defined administrative result. For ${t.lens}, the firm should name the matter types, source records, expected handoff, and person who reviews the work. The worker is not being asked to replace counsel. The worker is being asked to make a repeatable part of the file easier to see and easier to check. That distinction matters because ${t.risk}. A broad instruction such as “keep this organized” leaves the worker to invent priorities. A bounded instruction says what enters the queue, what leaves it, and what must stop. The firm can then test the process on a small sample before giving it more volume or wider access.` },
    { heading: 'Define the source boundary', body: `Write the input rule before opening a system. In this workflow, the approved inputs are ${t.input}. Record where each source came from, when it was received, and whether it is complete enough for preparation. Do not repair an unclear source by guessing. If a name, date, identity, or instruction conflicts with another record, preserve both records and describe the conflict in plain language. The first deliverable is not a polished conclusion; it is a trustworthy trail from source to prepared item. Use named accounts, matter-level permissions, and a current example. A worker who can see only the assigned material is less likely to solve an unclear task by searching everywhere.` },
    { heading: 'Design the handoff', body: `The finished administrative output for this lane is ${t.output}. Give it a stable name and a predictable location. Include the source links, the date checked, the preparer, and a short list of anything that could not be resolved. The reviewer should not have to reconstruct the worker’s path from chat messages or memory. The handoff should answer four questions: what was requested, what was found, what remains uncertain, and who owns the decision. If the result is going to a client, court, vendor, or opposing party, place a separate release gate before it leaves the firm. Preparation can be offshore; the firm’s authorized reviewer controls the meaning and release.` },
    { heading: 'Separate facts from decisions', body: `The safest writing style is factual and traceable. “The notice lists May 4” is different from “May 4 is the legal deadline.” “The file contains two versions” is different from “the second version controls.” “The client asked about timing” is different from “the firm promised a response.” Use labels such as source found, missing, conflicting, awaiting review, and instruction received. Avoid labels that imply legal sufficiency, privilege, compliance, urgency, or liability unless the firm supplied the exact authorized decision. This makes the worker’s contribution useful without expanding the role into legal judgment. It also gives the reviewer a clear place to correct the record.` },
    { heading: 'Build an exception route', body: `An exception is a work item, not an inconvenience to hide. For ${t.lens}, common exceptions include an incomplete source, an unfamiliar party name, a duplicate record, a changed instruction, an access problem, or a request that falls outside the approved example. The worker should pause, preserve the relevant evidence, state the question, and send it to ${t.owner}. The escalation record should show when it was sent and whether anyone acknowledged it. Do not create a second unofficial queue in a personal notebook. Do not forward confidential material to an unapproved recipient in order to get an answer faster. A visible exception queue lets the firm improve instructions while protecting the matter.` },
    { heading: 'Run a measured first week', body: `Start with ${t.first}. On the first day, explain the task boundary, accounts, approved sources, naming rule, and stop rule. On the second day, observe a practice item and ask the worker to narrate which source supports each field. On the third day, allow a small live batch with same-day review. On the fourth day, compare repeated questions and update the guide rather than relying on verbal reminders. On the fifth day, review accuracy, missing details, turnaround, escalation quality, and access discipline. Add volume only when the existing lane is steady. A quick worker who silently guesses is a larger risk than a careful worker who raises a precise question.` },
    { heading: 'Keep review meaningful', body: `Review should test the things that can harm a legal matter, not merely whether the spreadsheet looks tidy. For this topic, ${t.review}. Sample both clean items and exceptions. Keep the original input beside the prepared output so the reviewer can distinguish a worker error from an ambiguous instruction. Record rework reasons in specific terms: wrong source, omitted field, unsupported inference, naming error, late escalation, or access issue. Do not turn a count of completed items into a quality claim. The firm should decide when review can move from every item to a sample, and should return to full review when the task, tool, matter type, or staff member changes.` },
    { heading: 'Protect confidentiality in ordinary work', body: `Confidentiality is part of the daily design. Use individual credentials, multifactor authentication where available, limited folders, approved transfer methods, and a clear screen and download rule. Keep training examples redacted when possible. Do not paste client facts into an unapproved tool to make a task easier. If the worker sees the wrong matter, recipient, or permission, stop and report the time, location, and action taken. Do not delete evidence or quietly correct an access problem. The firm decides whether to lock an account, preserve records, notify anyone, or follow a broader incident procedure. The offshore location does not remove the firm’s duty to supervise the work and protect client information.` },
    { heading: 'Use a practical manager scorecard', body: `A short scorecard keeps the manager close to the real workflow. Track whether the item had the right source, whether required fields were captured, whether the output matched the approved format, whether exceptions were escalated, and whether the handoff arrived within the agreed working window. Add one field for the reason for rework and one for the reviewer’s next instruction. For ${t.lens}, do not reward a worker for closing an item that should have been paused. Ask instead whether the worker recognized the boundary and made the question easy to answer. The scorecard is for coaching and control; it is not a public performance claim or a substitute for attorney review.` },
    { heading: 'Questions the firm should settle', body: `${t.question} Also settle which systems are in scope, which hours require coverage, who handles an unanswered escalation, how access is removed, and what happens when the task changes. Put those answers in the role brief and the operating guide. A candidate should be evaluated on careful source handling, written communication, consistency, and willingness to stop when an instruction is unclear. The final decision remains with the firm’s authorized people. When the role is defined this way, offshore support can provide dependable preparation and visibility while legal advice, strategy, approval, and client responsibility stay where the firm has placed them.` },
  ];
}

const heroPaths = [
  '/aug23-heroes/deadline-source-checks.png', '/aug23-heroes/intake-routing-matrix.png', '/aug23-heroes/document-version-ledgers.png', '/aug23-heroes/discovery-custodian-index.png',
  '/aug23-heroes/client-update-digests.png', '/aug23-heroes/billing-exception-queues.png', '/aug23-heroes/privileged-folder-permissions.png', '/aug23-heroes/legal-research-request-logs.png',
  '/aug23-heroes/hearing-preparation-checklists.png', '/aug23-heroes/matter-closeout-records.png', '/aug23-heroes/translation-intake-registers.png', '/aug23-heroes/vendor-evidence-trackers.png',
];

export const august23BlogPosts = topics.map((topic, index) => ({
  ...topic,
  published: '2026-08-23',
  modified: '2026-08-23',
  minutes: 10,
  featuredImage: heroPaths[index],
  sections: sections(topic),
}));
