type Topic = {
  slug: string; title: string; excerpt: string; task: string; inputs: string;
  output: string; owner: string; stop: string; example: string;
};

const topics: readonly Topic[] = [
  { slug: 'offshore-legal-support-subpoena-intake-register', title: 'Building a subpoena intake register with offshore legal support', excerpt: 'A controlled way to record subpoena receipt facts while counsel retains response, objection, and deadline decisions.', task: 'subpoena intake registration', inputs: 'the received document, delivery record, matter number, and firm-approved intake fields', output: 'a source-linked register entry that preserves the received wording and unresolved fields', owner: 'the supervising litigation attorney', stop: 'the recipient, matter, service details, or requested action is unclear', example: 'A subpoena arrives by email with two attachments and no matter number. The worker records the sender, received time, filenames, and missing matter reference, then routes the packet without calculating a response date.' },
  { slug: 'law-firm-offshore-support-engagement-letter-routing', title: 'Engagement letter routing for law-firm offshore support', excerpt: 'Prepare engagement packets without letting an administrative workflow decide acceptance, scope, or legal terms.', task: 'engagement letter routing', inputs: 'an approved template, attorney instructions, contact details, and matter-opening status', output: 'a versioned draft packet and approval queue', owner: 'the responsible attorney or intake partner', stop: 'a requested term differs from the approved instruction or the conflict decision is missing', example: 'The approved template names one client, but the intake record lists two possible entities. The worker preserves both records and asks which entity belongs in the draft instead of choosing one.' },
  { slug: 'offshore-legal-calendar-change-evidence-log', title: 'A calendar change evidence log for offshore legal support', excerpt: 'Keep calendar edits traceable when dates, time zones, or instructions change.', task: 'calendar change logging', inputs: 'firm-approved calendar instructions, source notices, event identifiers, and time-zone labels', output: 'a before-and-after change record with the instruction source', owner: 'the docketing owner or assigned attorney', stop: 'two sources conflict or an instruction requires a deadline calculation', example: 'A hearing notice shows local court time while the matter calendar displays another zone. The worker records both displays and pauses the edit for the docketing owner.' },
  { slug: 'legal-support-offshore-redaction-request-queue', title: 'Managing a redaction request queue with offshore legal support', excerpt: 'Separate candidate marking and file preparation from privilege, disclosure, and final redaction approval.', task: 'redaction request administration', inputs: 'the approved request, source file, stated criteria, and reviewer assignment', output: 'a working copy with candidate locations and a review record', owner: 'the attorney or authorized disclosure reviewer', stop: 'the criteria require legal interpretation or the source version cannot be confirmed', example: 'A request asks for account numbers to be marked, but one string could be a matter identifier. The worker flags the location and leaves the classification to the reviewer.' },
  { slug: 'offshore-litigation-support-deposition-exhibit-index', title: 'Deposition exhibit indexing with offshore litigation support', excerpt: 'Create a reliable exhibit index while counsel controls selection, use, and evidentiary judgments.', task: 'deposition exhibit indexing', inputs: 'the approved exhibit set, filenames, visible labels, and attorney instructions', output: 'an index linking each label to the supplied file and version', owner: 'the examining attorney or litigation lead', stop: 'a label is duplicated, a file is missing, or the requested order is uncertain', example: 'Two PDFs display the same exhibit number but have different page counts. The worker retains both filenames, records the mismatch, and requests direction.' },
  { slug: 'offshore-legal-support-signature-packet-control', title: 'Signature packet control for offshore legal support', excerpt: 'Prepare signature packets with firm-owned authority over signers, sequence, content, and release.', task: 'signature packet preparation', inputs: 'the approved final document, signer list, routing instruction, and release approval', output: 'a locked packet checklist with version, recipients, and status', owner: 'the transaction attorney or designated closer', stop: 'the final version, signer authority, delivery address, or signing order is uncertain', example: 'The routing sheet names a signer whose title differs from the signature block. The worker records the discrepancy and does not send the packet.' },
  { slug: 'law-firm-offshore-support-client-document-receipt-log', title: 'Client document receipt logs for law-firm offshore support', excerpt: 'Record what a client supplied without implying review, completeness, or legal acceptance.', task: 'client document receipt logging', inputs: 'the approved inbox or portal event, filenames, timestamps, and matter identifier', output: 'a receipt log that states what was observed and what was not reviewed', owner: 'the matter manager or assigned attorney', stop: 'the matter cannot be confirmed, a file is unreadable, or the sender asks a legal question', example: 'A client uploads three files against a five-item request. The worker records the three observed files and two unmatched request items without stating that the production is incomplete.' },
  { slug: 'offshore-legal-support-conflict-search-preparation', title: 'Conflict search preparation for offshore legal support', excerpt: 'Normalize supplied names and sources without making a conflict determination.', task: 'conflict search preparation', inputs: 'approved intake names, entity roles, alternate spellings, and the permitted index', output: 'a source-preserving search worksheet and candidate results', owner: 'the conflicts attorney or authorized conflicts team', stop: 'identity is ambiguous, the search scope expands, or a result needs legal evaluation', example: 'An intake form uses initials while an attachment has a full name. The worker preserves both strings and reports the search results separately instead of merging the identities.' },
  { slug: 'legal-support-offshore-court-filing-receipt-reconciliation', title: 'Court filing receipt reconciliation with offshore support', excerpt: 'Compare filing receipts to authorized submissions without treating a portal status as legal acceptance.', task: 'filing receipt reconciliation', inputs: 'the authorized submission copy, portal receipt, transaction identifier, and matter record', output: 'a comparison showing observed receipt status and any mismatch', owner: 'the filing attorney or docketing specialist', stop: 'the receipt is absent, rejected, ambiguous, or linked to a different version', example: 'The portal receipt filename matches the filing but its page count differs from the authorized copy. The worker preserves both records and escalates the mismatch.' },
  { slug: 'offshore-legal-support-invoice-narrative-exception-log', title: 'Invoice narrative exception logs for offshore legal support', excerpt: 'Route incomplete or inconsistent billing narratives while the firm retains billing judgment and approval.', task: 'invoice narrative exception logging', inputs: 'approved time entries, billing rules, matter identifiers, and reviewer instructions', output: 'an exception list with the source entry and precise question', owner: 'the billing attorney or finance reviewer', stop: 'a correction would change legal meaning, time worked, rate, or client treatment', example: 'A narrative uses an internal abbreviation not allowed by the supplied billing guide. The worker flags it and requests approved wording rather than inventing a description.' },
  { slug: 'law-firm-offshore-support-data-room-access-register', title: 'Data room access registers for law-firm offshore support', excerpt: 'Document access requests and observed permissions without granting authority or probing unrelated material.', task: 'data room access registration', inputs: 'approved access requests, user identity, stated purpose, folder scope, and owner decision', output: 'an attributable access register with request, approval, change, and removal states', owner: 'the matter owner or access administrator', stop: 'approval is missing, effective access exceeds scope, or an unexpected folder is visible', example: 'A guest approved for one folder can see a second folder name. The worker records the observation, stops testing, and sends it to the access owner.' },
  { slug: 'offshore-legal-support-records-hold-acknowledgment-tracker', title: 'Records hold acknowledgment tracking with offshore legal support', excerpt: 'Track acknowledgments and reminders without interpreting preservation duties or releasing a hold.', task: 'records hold acknowledgment tracking', inputs: 'the authorized recipient list, issued notice, delivery records, and response states', output: 'a tracker of sent, delivered, acknowledged, unresolved, and escalated states', owner: 'the legal hold owner or supervising attorney', stop: 'a recipient disputes scope, reports missing data, or asks whether material may be deleted', example: 'A recipient acknowledges the notice but says an old device is unavailable. The worker records both facts and routes the preservation question to the hold owner.' },
];

const sections = (t: Topic) => [
  { heading: `Define the ${t.task} lane`, body: `On August 31, 2026, a firm considering ${t.task} should start with a written lane, not a broad job title. The worker may use ${t.inputs}. The expected handoff is ${t.output}. That description tells the worker what a finished administrative task looks like and gives the reviewer something concrete to inspect. It does not transfer legal judgment. ${t.owner} remains responsible for decisions, approval, and any external communication. Put the permitted source locations, required fields, naming rule, working hours, and reviewer in one short operating guide. If the firm cannot identify the source or owner, the item is not ready for offshore processing.` },
  { heading: 'Preserve the source before changing a working copy', body: `The worker should record the matter identifier, source location, visible version or received time, and the instruction used. Original material stays unchanged. Any renamed, annotated, or reformatted file is a working copy linked back to that source. A clean filename is not proof that a document is current, final, complete, or approved. When two records disagree, keep both and describe the conflict in neutral terms. This small discipline prevents an attractive output from hiding a weak input. It also lets a second reviewer reconstruct the handoff without relying on memory or a private chat message.` },
  { heading: 'Make the stop rule usable', body: `The clearest stop condition for this lane is: ${t.stop}. The worker should not solve that uncertainty by searching unrelated matters, guessing which record controls, or selecting the result that closes the queue fastest. The item should move to an exception state with the source, observed fact, missing information, and one narrow question. A useful escalation says what happened and what authority is needed. It does not bury the problem in a general request for review. Managers should treat a correct pause as good work, because the purpose of the queue is reliable preparation rather than cosmetic completion.` },
  { heading: 'Keep legal decisions with the firm', body: `Offshore legal support can transcribe supplied facts, compare records against explicit criteria, organize files, prepare a draft from an approved template, and maintain a status log. It should not decide privilege, legal sufficiency, strategy, liability, a response deadline, client advice, filing content, retention, or whether a person has authority. Those limits belong beside the allowed examples in the role brief. If a routine field could affect a client right or the firm's position, the worker records the source and routes the decision. The firm should also specify who acts when the primary reviewer is unavailable, so an urgent exception does not drift between inboxes.` },
  { heading: 'Use a reviewable handoff', body: `A useful handoff has five parts: the item identity, the approved instruction, the source used, the action taken, and the unresolved state. The reviewer should be able to accept, correct, or return it without asking the worker to rebuild the history. Status labels should describe evidence, such as received, not located in reviewed folder, prepared for review, returned for correction, or awaiting owner decision. Labels such as cleared, compliant, complete, or approved should appear only when the authorized owner supplied that disposition. Corrections should add a new attributable event rather than overwrite the earlier observation.` },
  { heading: 'Apply access and confidentiality controls', body: `Give the worker an individual account and only the folders and functions needed for ${t.task}. Use the firm's approved authentication, device, transfer, and communication rules. Redact training examples where practical. Do not copy client facts into an unapproved tool or personal account. If the worker sees the wrong matter, an unexpected permission, or a recipient outside the instruction, work should stop. Record the time, location, and action already taken, then notify the named owner. The firm decides containment, access changes, preservation, notification, and any client communication.` },
  { heading: 'Test the lane with representative work', body: `${t.example} This is the kind of example a firm should include in training because it exposes the boundary, not just the happy path. Begin with a small set that includes a clean item, a missing field, a conflicting source, a changed instruction, and a request outside scope. Review every item at first. Record error categories separately, including wrong source, missing field, unsupported change, late escalation, and access issue. A raw completion count cannot show whether the worker protected the boundary. Expand volume only when the firm can explain the exceptions and the reviewer still has enough time to inspect them.` },
  { heading: 'Set a practical first-week routine', body: `On the first day, confirm the role brief, accounts, examples, and stop rule. On the second, let the worker observe a reviewed item and explain the source trail back to the manager. On the third, assign a small live batch with same-day review. Use the fourth day to revise unclear instructions and add an example for any repeated question. On the fifth, review accuracy, source handling, escalation quality, access discipline, and turnaround within the agreed window. The result should be a better-defined lane, not an assumption that one quiet week proves the process is safe.` },
  { heading: 'Manager checklist for August 31, 2026', body: `Before releasing this lane, confirm that the allowed task and prohibited decisions are written, the source systems are named, each account is attributable, working copies preserve originals, and ${t.owner} accepts the review duty. Confirm the backup escalation path, access removal process, correction history, and review sample. Ask whether an outsider could reconstruct one item from instruction through disposition. If the answer depends on memory, rebuild the record. ${t.task} is suitable for supervised support only when preparation stays separate from judgment and uncertainty remains visible.` },
];

export const august31BlogPosts = topics.map((topic) => ({
  ...topic,
  published: '2026-08-31',
  modified: '2026-08-31',
  minutes: 9,
  featuredImage: '/blog-thumbnails/blog-default.svg',
  sections: sections(topic),
}));
