type Section = { heading: string; body: string };
type Post = { slug: string; title: string; excerpt: string; minutes: number; published: '2026-08-20'; sourceDate: '2026-08-20'; sections: Section[] };
type RouteSource = { published: '2026-08-20'; sourceDate: '2026-08-20' };

// Route-local date bindings are intentionally literal and independently auditable.
const routeSources: Record<string, RouteSource> = {
  'offshore-legal-support-intake-escalation-matrix': { published: '2026-08-20', sourceDate: '2026-08-20' },
  'law-firm-offshore-support-matter-folder-governance': { published: '2026-08-20', sourceDate: '2026-08-20' },
  'offshore-legal-support-hearing-preparation-source-board': { published: '2026-08-20', sourceDate: '2026-08-20' },
  'legal-support-offshore-client-identity-resolution-log': { published: '2026-08-20', sourceDate: '2026-08-20' },
  'offshore-legal-support-records-request-coverage-map': { published: '2026-08-20', sourceDate: '2026-08-20' },
  'law-firm-offshore-support-amendment-version-register': { published: '2026-08-20', sourceDate: '2026-08-20' },
  'offshore-legal-support-disclosure-packet-checklist': { published: '2026-08-20', sourceDate: '2026-08-20' },
  'legal-support-offshore-court-correspondence-index': { published: '2026-08-20', sourceDate: '2026-08-20' },
  'offshore-legal-support-vendor-records-reconciliation': { published: '2026-08-20', sourceDate: '2026-08-20' },
  'law-firm-offshore-support-client-call-fact-log': { published: '2026-08-20', sourceDate: '2026-08-20' },
  'offshore-legal-support-retention-exception-register': { published: '2026-08-20', sourceDate: '2026-08-20' },
  'legal-support-offshore-review-capacity-board': { published: '2026-08-20', sourceDate: '2026-08-20' },
};
const routeDateBindings = Object.keys(routeSources).map((slug) => ({ slug, published: '2026-08-20' as const, sourceDate: '2026-08-20' as const }));

const makeSections = (focus: string, failure: string, reviewer: string, example: string): Section[] => [
  { heading: 'Define the administrative question', body: `Begin ${focus} with a written question answerable from identified records. Name the matter or queue, source system, requested period, expected output, reviewer, and stop condition. Say whether the worker is collecting, indexing, comparing, formatting, or routing. “Clean this up” invites silent decisions about scope; a source-linked register, exception list, or review packet gives the firm a fair inspection point. This matters in offshore legal support because the worker may be separated by time zone from the person who owns the matter. Preserve the request wording in the approved task system, and record each later scope change as an instruction. An observable definition of done protects the firm from a neat-looking output that hides an assumption.` },
  { heading: 'Build a controlled source set', body: `Before preparing ${focus}, list supplied files, approved messages, system records, templates, and the date each was received. Keep originals distinct from working copies. Record missing, locked, duplicated, unreadable, or conflicting sources as findings. Do not search broadly because the first source is incomplete, and do not choose a newer-looking file without an authorized rule. A source register should trace each prepared field to a location and state what was not checked. Offshore legal support is useful when provenance remains visible and the legal team can decide whether a source is authoritative, current, sufficient, or safe to disclose. A tidy folder is not evidence that the underlying record is complete.` },
  { heading: 'Use a narrow operating lane', body: `Pilot ${focus} with one repeatable task and a small approved sample. Include an ordinary item, an incomplete record, a duplicate, and an exception for escalation. The pilot tests instruction, access, handoff, and review capacity; it does not prove a legal result. Give the worker acceptable examples and a clear definition of done. If nearly every item requires interpretation, narrow the lane or keep it with the firm. A narrow lane makes training practical: the worker learns which fields to preserve, which status labels are factual, and which questions belong with ${reviewer}. Add scope only after reviewing enough examples to understand rework and exception patterns.` },
  { heading: 'Make the failure visible', body: `The most useful output for ${focus} may be an exact exception rather than a complete-looking record. For ${failure}, record the item identifier, source checked, fact observed, missing or conflicting field, and person who must decide the next step. Use neutral labels such as “not located in supplied set,” “identifier differs,” “access unavailable,” or “instruction unclear.” Do not turn “not found” into “does not exist,” or call a packet sufficient because it contains a plausible number of files. Preserve both versions when they differ. A concise exception saves attorney or manager time because it identifies what has already been checked and what decision remains. Escalation is a completed support action when the role reaches its boundary.` },
  { heading: 'Keep judgment with the firm', body: `For ${focus}, offshore support may collect, organize, compare against an approved checklist, format, label, and route. The firm retains legal advice, strategy, conflicts, privilege, deadline calculation, filing approval, settlement authority, trust-account action, interpretation, and final client communication. Put those limits beside the checklist. If a client asks a substantive question, a source changes the apparent issue, or a task needs broader access, pause, preserve the question, and use the named escalation path. Do not reward silent guesses. The reviewer should distinguish copied source facts from working notes and from questions. That separation protects the client relationship and makes supervision meaningful.` },
  { heading: 'Design an evidence-based handoff', body: `A reviewer receiving ${focus} should get the original request, source list, prepared output, exceptions, version information, checks completed, and a specific decision request. Avoid a narrative that blends source facts with interpretation. State whether each item was verified, not located, duplicated, or awaiting instruction. Record handoff time and recipient in the approved system. The reviewer can accept, correct, return, or redirect the work without reconstructing events from private chat. A handoff is not approval; it is a controlled transfer of preparation to the person who owns judgment. If an instruction changes, preserve the old version and attach the new one so a one-off correction is not mistaken for a general rule.` },
  { heading: 'Protect information while it moves', body: `Access for ${focus} should match the minimum data and action required. Use named accounts, matter-specific permissions, approved storage, and separate read and write rights where available. Do not copy sensitive records into a broad channel to resolve a small question. If a wrong matter, unexpected recipient, or unapproved permission appears, stop and report visible facts. The firm decides containment, notification, remediation, and legal significance. Use redacted training examples when live client data is unnecessary. Preserve originals, avoid unneeded downloads, and remove temporary access through the firm’s process. Offshore legal support should strengthen access discipline rather than create a second uncontrolled repository.` },
  { heading: 'Measure preparation quality', body: `Managers can review ${focus} through source-link completeness, identifier fidelity, missing-field handling, rework reason, escalation timing, reviewer turnaround, and unresolved-item age. Define each measure before collecting it and keep examples of exclusions. Do not present volume or speed as proof of legal quality, client outcome, compliance, savings, or a protected deadline. A backlog may reflect reviewer capacity or an intentional hold. Sample ordinary items and exceptions. If the same question returns, update the approved checklist through its owner and record the effective version. Measurement should reveal where the workflow needs clearer instructions or stronger review, not pressure support staff to conceal uncertainty.` },
  { heading: 'Work through a difficult example', body: `Test ${focus} with a deliberately ambiguous item. In ${example}, the worker should preserve the original material, identify the precise discrepancy, avoid a conclusion, and route one well-formed question. The reviewer should tell whether the problem came from source, instruction, access, system, or prepared output. Rehearsal exposes hidden assumptions: similar names, an amended document, an incomplete attachment, a changed recipient, or a request crossing into legal judgment. Keep the test result with the workflow version. A clean stop is evidence of a functioning boundary, not a productivity failure.` },
  { heading: 'Close with an authorized disposition', body: `Do not close ${focus} merely because a file was produced or a message was sent. The final state should say accepted for review, returned for correction, held for missing information, redirected, withdrawn, or closed by a named owner. Preserve the original request, source references, corrections, unresolved questions, and reviewer instruction. “Prepared” and “approved” are different states; “not located” and “does not exist” are different findings. LegalServicesOffshore.com’s practical boundary is clear: offshore support creates a reliable administrative record and clearer queue, while the law firm remains responsible for professional judgment, supervision, confidentiality, and release. That boundary belongs in every handoff.` },
];

const makePost = (slug: string, title: string, excerpt: string, focus: string, failure: string, reviewer: string, example: string): Post => {
  const source = routeSources[slug];
  if (!source || !routeDateBindings.some((entry) => entry.slug === slug)) throw new Error(`Missing August 20 route source for ${slug}`);
  return { slug, title, excerpt, minutes: 11, published: source.published, sourceDate: source.sourceDate, sections: makeSections(focus, failure, reviewer, example) };
};

export const august20BlogPosts: Post[] = [
  makePost('offshore-legal-support-intake-escalation-matrix', 'Intake escalation matrices for offshore legal support', 'Turn intake signals into a factual routing matrix while the firm keeps conflicts, advice, urgency, and acceptance decisions.', 'new inquiry routing and escalation', 'a new inquiry contains urgency language, a conflict signal, or a request for advice', 'the intake owner or attorney', 'an inquiry names a familiar party but does not identify the matter or requested service'),
  makePost('law-firm-offshore-support-matter-folder-governance', 'Matter-folder governance with offshore legal support', 'Keep matter folders findable, permissioned, and source-linked without allowing administrative cleanup to change the record.', 'matter-folder naming, access, and version control', 'a folder contains duplicate versions, an unclear owner, or material from another matter', 'the matter manager', 'a folder has two similarly named clients and a draft beside an executed document'),
  makePost('offshore-legal-support-hearing-preparation-source-board', 'Hearing-preparation source boards with offshore support', 'Organize supplied hearing details, documents, and open questions while counsel controls deadlines and advocacy.', 'hearing-preparation source tracking', 'a hearing source has a changed date, missing exhibit, or question needing advocacy judgment', 'the responsible attorney', 'a notice and calendar show different times and the notice omits a time zone'),
  makePost('legal-support-offshore-client-identity-resolution-log', 'Client-identity resolution logs for offshore legal support', 'Record identity questions and approved evidence without deciding representation, conflicts, or the legal relationship.', 'client-identity discrepancy handling', 'two supplied records use similar names or an identity field cannot be confirmed', 'the conflict or intake owner', 'a prospective client uses a shortened name while an uploaded document uses a different spelling'),
  makePost('offshore-legal-support-records-request-coverage-map', 'Records-request coverage maps for offshore legal support', 'Show which requested records arrived, which sources were checked, and which gaps need a firm decision.', 'records-request coverage and gap mapping', 'a requested period has no file, a packet has missing pages, or a source is unreadable', 'the matter owner', 'a combined PDF appears to skip a month listed in the approved request'),
  makePost('law-firm-offshore-support-amendment-version-register', 'Agreement-amendment version registers with offshore support', 'Connect amendments, notices, and executed versions while counsel interprets effect and obligations.', 'agreement amendment version control', 'two versions have different effective dates or a notice appears to change the operative document', 'the contract attorney', 'an unsigned amendment is newer by filename but an executed version is the approved source'),
  makePost('offshore-legal-support-disclosure-packet-checklist', 'Disclosure-packet checklists for offshore legal support', 'Prepare a traceable packet check while attorneys decide scope, privilege, redaction, and release.', 'disclosure-packet completeness checking', 'a packet includes a sensitive item, missing attachment, duplicate, or proposed redaction', 'the disclosure reviewer', 'a page is marked by a keyword but its surrounding context is unclear'),
  makePost('legal-support-offshore-court-correspondence-index', 'Court-correspondence indexes for offshore legal support', 'Keep court messages, attachments, recipients, and handoffs reviewable without calculating legal deadlines.', 'court correspondence indexing', 'a court message has an unfamiliar sender, attachment mismatch, or date mistaken for a deadline', 'the docket owner', 'an emailed notice arrives after a similar portal entry with different metadata'),
  makePost('offshore-legal-support-vendor-records-reconciliation', 'Vendor-record reconciliation for offshore legal support', 'Compare approved vendor records and matter references while authorized staff decide payment, dispute, and release.', 'vendor-record reconciliation', 'a vendor invoice does not match the approved matter, period, or supporting record', 'the authorized billing owner', 'two invoices have the same reference but different amounts and neither source explains why'),
  makePost('law-firm-offshore-support-client-call-fact-log', 'Client-call fact logs with offshore legal support', 'Capture supplied call facts and follow-up questions without giving advice or promising an outcome.', 'client-call factual logging', 'a caller asks for advice, describes an urgent event, or conflicts with the intake record', 'the assigned attorney or intake owner', 'a caller asks whether a deadline is safe after describing a new notice'),
  makePost('offshore-legal-support-retention-exception-register', 'Retention-exception registers for offshore legal support', 'Track retention instructions and missing records while the firm owns legal holds and disposition decisions.', 'retention exception tracking', 'a record is missing, subject to an unclear hold, or stored in an unapproved location', 'the records owner', 'a folder contains a deletion request but current hold status is unavailable'),
  makePost('legal-support-offshore-review-capacity-board', 'Review-capacity boards for offshore legal support', 'Show prepared work waiting for review without treating queue movement as legal approval or quality proof.', 'review-capacity and handoff management', 'a prepared item is aging, repeatedly returned, or waiting on a reviewer whose capacity changed', 'the practice manager', 'a queue looks complete by count while high-context items remain unreviewed'),
];
