type Section = { heading: string; body: string };
type Post = { slug: string; title: string; excerpt: string; minutes: number; published: '2026-08-21'; sourceDate: '2026-08-21'; featuredImage: string; sections: Section[] };

const closing = (subject: string, owner: string, example: string) => `For ${subject}, the offshore support role should be measured by reconstructable preparation rather than by a promise about legal outcome. Keep the original request, source register, prepared work, exception notes, reviewer instruction, and final disposition together. The ${owner} retains legal advice, strategy, privilege, conflicts, deadline decisions, filing approval, settlement authority, client promises, and release of sensitive material. A support worker can collect supplied facts, apply an approved checklist, format or index records, and make uncertainty visible. In ${example}, the correct action is to preserve the discrepancy and ask a narrow question, not to repair the record from context. That boundary makes a time-zone handoff easier to supervise and gives the firm evidence of what was actually checked.`;

const makeSections = (p: { subject: string; question: string; input: string; output: string; failure: string; reviewer: string; example: string; cadence: string; access: string; decision: string;}) : Section[] => [
  { heading: 'Start with the decision the workflow must support', body: `A law firm considering ${p.subject} should first write the question this administrative lane will answer: ${p.question}. The question must identify the matter or queue, the approved source set, the requested period, the expected output, and the person who owns the review. Avoid instructions such as “make this ready” when readiness could mean formatting, completeness, legal sufficiency, or release. State whether the offshore role is collecting, indexing, comparing, drafting from a locked template, or routing. The distinction matters because a polished packet can still contain an unreviewed assumption. Preserve the request wording in the firm’s task system, record later changes as new instructions, and define the stop condition before access is granted. ${closing(p.subject, p.reviewer, p.example)}` },
  { heading: 'Design a source register before the first item', body: `The input to ${p.subject} should be a visible register, not a folder whose contents another person must guess. Record each ${p.input}, its source location, received date, visible identifier, version, and access limitation. Keep original files separate from working copies. A duplicate, missing attachment, unreadable page, locked record, or conflicting date is an exception with a source reference; it is not permission to select the most convenient substitute. Use neutral states such as received, partially received, duplicate, not located in supplied set, awaiting instruction, and prepared for review. The register should also say what was not checked. This lets the reviewer distinguish an absent source from an incomplete search and prevents a tidy index from being mistaken for a complete matter record.` },
  { heading: 'Choose a narrow first lane', body: `A practical pilot for ${p.subject} contains one repeatable output: ${p.output}. Start with a small approved sample containing an ordinary item, a missing component, a duplicate, a conflict, and one boundary case. Give the worker a current example, field definitions, naming rules, escalation contacts, and a review timetable. Do not widen the lane because the first sample looks easy. Widen it only after the reviewer has seen how exceptions are recorded and whether the handoff survives the gap between shifts. If most items require interpretation, the correct response is to narrow the scope or return the interpretive step to the firm. The pilot is evidence about instruction quality and supervision capacity, not evidence that the role can make legal decisions.` },
  { heading: 'Make the failure state useful', body: `The hard part of ${p.subject} is usually ${p.failure}. When it occurs, record the item identifier, exact source checked, fact observed, missing or conflicting field, action already taken, and named next owner. Do not translate “not found” into “does not exist,” or turn an apparent mismatch into a corrected value without an authorized rule. A useful exception question has one decision in it: “The supplied version shows A, the comparison source shows B; which source should govern this preparation?” The reviewer can answer that question without repeating the search. Escalation is a completed support action when the role has reached its boundary. It is safer and faster than allowing a worker to hide uncertainty inside a final-looking document.` },
  { heading: 'Separate preparation from professional judgment', body: `For ${p.subject}, the support role may preserve supplied wording, sort records, compare fields, prepare a neutral chronology, apply a checklist, and route questions. It should not decide ${p.decision}. The firm retains legal advice, conflicts, privilege, strategy, deadline calculation, filing or production approval, settlement choices, trust-account action, and substantive client communication. Put the boundary beside the instructions, not only in onboarding material. If a request changes recipient, expands access, introduces a new legal issue, or asks for a conclusion, pause and retain the question exactly. The reviewer should be able to see which statements came from a source, which were mechanical checks, and which remain open. This is the control that makes offshore legal support accountable rather than merely remote.` },
  { heading: 'Build a handoff that works across time zones', body: `The ${p.reviewer} receiving ${p.subject} should get the original request, source inventory, prepared output, exceptions, version information, checks completed, access limitations, and one explicit decision request. Add the handoff date and the identity of the preparer. Avoid private shorthand, screenshots without source links, or a narrative that mixes copied facts with interpretation. A status of prepared for review is not approved, and a sent reminder is not a completed request. For ${p.cadence}, sample both ordinary work and exceptions. Preserve corrections as linked updates so a one-off instruction is not silently treated as a permanent rule. Good handoffs let a reviewer accept, return, redirect, or hold work without reconstructing events from memory or an overnight chat thread.` },
  { heading: 'Match access to the task', body: `Access for ${p.subject} should cover only ${p.access}. Use named accounts, matter-specific permissions, approved storage, and separate read and write rights where the firm’s systems allow it. Do not copy a sensitive record into a broad channel to resolve a small question. If the worker sees the wrong matter, an unexpected recipient, an unapproved export option, or a permission that is broader than the task requires, stop and record the visible fact. The firm decides containment, notification, access change, and legal significance. Support staff should not investigate beyond their approved lane simply because a system makes more records visible. Review access at the end of the pilot and whenever the task, matter, or owner changes.` },
  { heading: 'Use measures that expose rework', body: `A manager can review ${p.subject} through source-link completeness, identifier fidelity, missing-field handling, exception quality, reviewer turnaround, rework reason, and unresolved-item age. Define each measure before collecting it. Do not use volume, speed, a low return count, or an empty queue as proof of legal quality, client outcome, compliance, deadline protection, or savings. A queue can be empty because work was held, redirected, or incorrectly closed. ${p.cadence} should include a sample of accepted-looking items and a sample of failures. When the same question recurs, the process owner should revise the approved instruction and record its effective version. Measurement should reveal where the workflow needs clearer scope, stronger review, or better access controls.` },
  { heading: 'Rehearse the boundary example', body: `Use ${p.example} as a test of the workflow, not of the worker’s willingness to guess. The preparer should preserve both records, identify the precise discrepancy, cite the source locations, and route one narrow question to ${p.reviewer}. The reviewer should be able to tell whether the issue came from the source, instruction, access, system behavior, or preparation. Rehearsal also catches hidden assumptions about similar names, amended versions, time zones, attachments, or recipients. Keep the result with the workflow version. A clean stop demonstrates that the control works. If the same ambiguity appears repeatedly, change the scope or checklist through its owner rather than teaching a private workaround that future reviewers cannot inspect.` },
  { heading: 'Close with an authorized disposition', body: `Do not close ${p.subject} merely because a file was produced or a message was sent. The final state should be accepted for review, returned for correction, held for missing information, redirected, withdrawn, or closed by a named owner. Preserve the request, source references, corrections, unresolved questions, and reviewer instruction. “Not located in supplied set” is not “nonexistent”; “prepared” is not “approved”; and a date displayed on a record is not automatically a legal deadline. ${closing(p.subject, p.reviewer, p.example)}` },
];

const specs = [
  ['offshore-legal-support-client-intake-triage','How offshore legal support can triage new client intake without giving advice','Route new inquiries by approved facts and urgency signals while conflicts, eligibility, advice, and acceptance stay with the firm.','the approved intake form, call note, email, and matter reference','a caller describes an urgent event but the supplied intake lacks a reliable date or matter owner','the intake manager','a caller asks whether a deadline has already expired','daily during the pilot','the intake queue, approved scripts, and the minimum contact fields','whether the inquiry is accepted, declined, or needs attorney review'],
  ['law-firm-offshore-support-document-naming-standard','A document-naming standard that makes offshore law-firm support reviewable','Use stable matter identifiers, document dates, type labels, and version markers without changing source meaning or hiding duplicates.','the firm’s naming policy, source filename, matter identifier, document type, and version note','two files have similar names but different visible dates and page counts','the records owner','a revised agreement arrives with a filename that looks older than the original','weekly with exception sampling','approved matter folders and the naming reference','which version is authoritative and whether a document may be released'],
  ['offshore-legal-support-deadline-source-check','Source checks for legal support deadline calendars','Compare calendar entries with supplied notices and orders while attorneys decide which date controls and what response is required.','the calendar entry, notice, order, time zone, and source timestamp','a calendar date differs from the date shown in an order','the docket owner','an order is received after the calendar reminder but uses a different time zone','each business day','the approved calendar and named source records','the legally operative date and response strategy'],
  ['legal-support-offshore-redaction-prep-log','A redaction-preparation log for offshore legal support','Track proposed redactions and source locations without deciding privilege, confidentiality, responsiveness, or production.','the document identifier, page, proposed mark, reason supplied by counsel, and reviewer','a page contains mixed personal and matter information with no instruction for the boundary','the production attorney','a repeated account number appears in a page that may be responsive','per production batch','the approved review workspace and assigned document set','whether a redaction is legally required and whether the document may be released'],
  ['offshore-legal-support-matter-opening-checklist','Matter-opening checklists for offshore legal support','Turn an approved opening instruction into a traceable checklist while the firm controls conflicts, engagement, and access decisions.','the opening request, parties, matter type, assigned owner, and approved systems','the opening request names a party but lacks a confirmed conflict disposition','the matter-opening manager','the intake record and engagement letter use different entity spellings','for every new matter','the opening queue and systems explicitly listed in the request','whether the matter may be opened and who may access it'],
  ['law-firm-offshore-support-discovery-file-index','Discovery-file indexes prepared with offshore legal support','Create a source-linked index of collected files and gaps without deciding relevance, privilege, search scope, or production.','the custodian, collection batch, filename, hash or identifier when supplied, date, and source','a collection contains a duplicate identifier and an unreadable file','the discovery lead','two batches contain files with the same name but different identifiers','per collection batch','the approved collection workspace and supplied batches','which records are responsive, privileged, or ready for production'],
  ['offshore-legal-support-client-call-fact-record','Client-call fact records for offshore legal support','Capture approved call notes and follow-up tasks while advice, commitments, and case strategy remain with the firm.','the caller’s stated facts, requested follow-up, timestamp, and approved script version','a caller asks the support worker to interpret a document or promise an outcome','the supervising attorney','the caller gives a new fact that conflicts with the existing matter record','same day','the call platform, approved script, and matter record','what advice or commitment, if any, the firm should provide'],
  ['legal-support-offshore-invoice-support-register','Invoice-support registers for law firms using offshore teams','Organize approved time entries, narrative gaps, and invoice questions without deciding billability, write-offs, or client response.','the time entry, matter, timekeeper, date, narrative, and source invoice period','a narrative is duplicated or too vague to match the supplied work record','the billing manager','two entries appear to describe one task but have different time blocks','before each invoice review','the billing system fields and approved invoice workspace','whether time is billable, should be written off, or needs client communication'],
  ['offshore-legal-support-contract-version-lineage','Contract version lineage for offshore legal support','Keep executed agreements, amendments, redlines, and notices connected without deciding the operative legal meaning.','the document version, sender, received date, section reference, and source location','a redline and clean copy have matching dates but different attachment sets','the contract owner','an amendment refers to a clause that appears only in an earlier draft','at every document intake','the contract repository and named deal folder','which document governs and what obligation or risk follows'],
  ['law-firm-offshore-support-legal-research-source-log','Legal-research source logs prepared with offshore support','Record queries, source authorities, access dates, and open questions without presenting administrative research as legal advice.','the research question as supplied, source title, URL or citation, access date, and extracted passage location','a source is secondary, undated, blocked, or inconsistent with another supplied authority','the research attorney','a search result summary conflicts with the primary source it links to','per research assignment','approved research databases and public sources named by the firm','which authority controls and what conclusion counsel should draw'],
  ['offshore-legal-support-appeal-bundle-check','Appeal-bundle checks with offshore legal support','Check an approved bundle for identifiers, sequence, missing components, and source links while counsel controls designation and filing.','the notice, order, brief, exhibit, transcript, page range, and source path','the bundle includes a superseded brief and an exhibit whose page range changed','the appellate attorney','a transcript index skips a page that appears in the source PDF','per bundle revision','the approved appellate workspace and supplied record set','what belongs in the record and whether filing may proceed'],
  ['legal-support-offshore-access-review','Access-review routines for offshore legal support teams','Review role permissions against actual task needs and surface exceptions without granting, revoking, or interpreting access authority.','the worker role, system, permission, matter scope, review date, and owner','a role includes a write permission that the checklist does not require','the security or operations owner','a worker’s access remains active after the pilot task ends','monthly and on role change','the access register and named system reports','whether access should be approved, changed, suspended, or escalated'],
] as const;

export const august21BlogPosts: Post[] = specs.map(([slug, title, excerpt, input, failure, reviewer, example, cadence, access, decision]) => ({
  slug, title, excerpt, minutes: 9, published: '2026-08-21', sourceDate: '2026-08-21', featuredImage: `/aug21-heroes/${slug}.png`,
  sections: makeSections({ subject: title, question: `what information can be prepared and routed without deciding the firm’s legal position`, input, output: excerpt.toLowerCase(), failure, reviewer, example, cadence, access, decision }),
}));
