type Topic = {
  slug: string;
  published: '2026-08-31';
  title: string;
  excerpt: string;
  subject: string;
  thesis: string;
  sources: string;
  record: string;
  reviewer: string;
  reserved: string;
  risk: string;
  opening: string;
  exception: string;
  measure: string;
  close: string;
  headings: string[];
};

const topics: Topic[] = [
  {
    slug: 'offshore-legal-litigation-hold-acknowledgment-ledger',
    published: '2026-08-31',
    title: 'A litigation-hold acknowledgment ledger for offshore legal support',
    excerpt: 'Track delivery, acknowledgment, questions, and follow-up without letting an administrative ledger decide preservation scope or legal sufficiency.',
    subject: 'litigation-hold acknowledgment administration',
    thesis: 'A useful acknowledgment ledger proves what the support team observed and routed. It does not prove that a preservation duty was satisfied.',
    sources: 'the attorney-approved hold notice, recipient roster, delivery evidence, acknowledgment messages, and later written instructions',
    record: 'a recipient-level ledger linking each status to the notice version and the evidence received',
    reviewer: 'the litigation attorney or preservation lead',
    reserved: 'the trigger, scope, recipients, adequacy of preservation, release of a hold, and any remedial response',
    risk: 'a green status can be mistaken for a legal conclusion even when the underlying acknowledgment is incomplete or ambiguous',
    opening: 'Begin with the notice version, not with a blank tracking sheet. A recipient may acknowledge an outdated notice, reply through an unexpected channel, ask a substantive question, or say that a device is unavailable. Those are different facts and should not collapse into one checked box.',
    exception: 'Route bounced messages, identity mismatches, partial acknowledgments, new custodians, disputed device lists, and any request to explain the hold.',
    measure: 'Review source links, notice-version accuracy, open-question age, follow-up ownership, and whether releases came from an authorized instruction.',
    close: 'The ledger is complete when it gives counsel a reliable account of communications and unresolved facts. Counsel still decides what those facts require.',
    headings: ['Start with the controlling notice version', 'Give every recipient a traceable status', 'Keep follow-up separate from legal conclusions', 'Treat silence and ambiguity as exceptions', 'Review the ledger against evidence', 'Close only on written authority'],
  },
  {
    slug: 'law-firm-court-reporter-scheduling-packet',
    published: '2026-08-31',
    title: 'Court-reporter scheduling packets prepared with offshore support',
    excerpt: 'Assemble approved scheduling facts, service details, access needs, and confirmations while counsel controls notices and procedural decisions.',
    subject: 'court-reporter scheduling packets',
    thesis: 'Scheduling support works best when logistics are gathered once and every legal or procedural choice has a named firm owner.',
    sources: 'the approved deposition notice, participant list, location or remote-platform instruction, reporter correspondence, and counsel-approved service information',
    record: 'a scheduling packet with event identity, participant contacts, access requirements, confirmation evidence, and open questions',
    reviewer: 'the assigned paralegal or attorney',
    reserved: 'whether to notice, adjourn, reschedule, serve, waive, object, or change the manner of testimony',
    risk: 'a convenient calendar change can conflict with a notice, client instruction, or procedural requirement',
    opening: 'A reporter needs concrete logistics, but the support worker should not invent them. The packet should distinguish a date proposed in email from a date shown in an approved notice. It should also distinguish a tentative attendance response from a confirmed participant list.',
    exception: 'Pause on conflicting times, missing time zones, unapproved remote links, accessibility questions, new attendees, service questions, or a request to alter the notice.',
    measure: 'Sample packet-to-source accuracy, confirmation timestamps, recipient approval, time-zone display, and unresolved logistics before the event.',
    close: 'The packet reduces coordination noise only when it preserves the difference between arranging an event and making the decisions that govern it.',
    headings: ['Separate proposed dates from approved dates', 'Build one event identity', 'Confirm access without widening distribution', 'Use a logistics-only communication lane', 'Recheck the packet before handoff', 'Archive the final confirmation trail'],
  },
  {
    slug: 'offshore-legal-insurance-defense-assignment-intake',
    published: '2026-08-31',
    title: 'Insurance-defense assignment intake with offshore legal support',
    excerpt: 'Organize assignment letters, claim identifiers, contacts, and initial records while attorneys decide conflicts, coverage issues, and case strategy.',
    subject: 'insurance-defense assignment intake',
    thesis: 'An assignment intake record should shorten the path to attorney review without turning insurer language into a firm acceptance or coverage position.',
    sources: 'the carrier assignment, claim correspondence, pleadings supplied with the referral, contact details, and the firm-approved intake fields',
    record: 'an intake summary that preserves identifiers, received materials, requested actions, missing records, and routing history',
    reviewer: 'the conflicts owner and assigned attorney',
    reserved: 'engagement acceptance, conflicts disposition, coverage interpretation, litigation position, staffing, budgets, and communication commitments',
    risk: 'administrative intake language may be read as acceptance of the assignment or agreement with the carrier’s characterization',
    opening: 'Carrier referrals often arrive with several identifiers and an implied sense of urgency. The support lane should slow down just enough to preserve each identifier, attachment, sender, and stated request. It should never improve a sparse referral by assuming the insured, loss date, venue, or response required.',
    exception: 'Escalate unmatched party names, missing pleadings, contradictory claim numbers, uncertain service information, broad data access, and any request for a legal view.',
    measure: 'Check name fidelity, claim and matter identifiers, attachment completeness, conflict-routing time, source preservation, and unauthorized commitments.',
    close: 'A strong intake leaves the attorney with fewer clerical searches and a more exact list of choices. It does not make those choices for the firm.',
    headings: ['Preserve the referral as received', 'Map identifiers before opening a matter', 'Route conflicts before wider access', 'Describe missing material without inference', 'Hold external commitments for counsel', 'Audit the first assignment sample'],
  },
  {
    slug: 'legal-support-corporate-minute-book-gap-log',
    published: '2026-08-31',
    title: 'Corporate minute-book gap logs for offshore legal support',
    excerpt: 'Inventory approved corporate records and missing periods while lawyers decide legal status, corrective action, and reliance.',
    subject: 'corporate minute-book gap logging',
    thesis: 'A gap log is an inventory of what was and was not found within a defined search. It is not a statement that an action never occurred.',
    sources: 'the approved entity list, minute-book folders, board and shareholder materials, officer records, indexes, and written search instructions',
    record: 'a period-based inventory showing each expected record category, located source, version, and bounded search result',
    reviewer: 'the corporate lawyer or entity-management owner',
    reserved: 'corporate validity, authority, ratification, legal effect, remediation, filing decisions, and advice to the client',
    risk: 'a missing file can be reported as a missing corporate action when the search boundary was incomplete',
    opening: 'Minute books rarely become untidy in a uniform way. One entity may have signed resolutions without an index, while another has an index that points to an empty folder. The log should describe these conditions separately and name exactly where the worker looked.',
    exception: 'Flag duplicate entities, inconsistent legal names, unsigned copies, unexplained date gaps, records outside the approved repository, and requests to characterize validity.',
    measure: 'Review search boundaries, entity identity, date coverage, file-version labels, source links, and the wording used for items not located.',
    close: 'The best gap log makes further retrieval or legal review easier. It remains modest about what an administrative search can establish.',
    headings: ['Define the entity and search boundary', 'Inventory before describing gaps', 'Use careful language for missing records', 'Keep unsigned and superseded copies visible', 'Send legal-status questions to counsel', 'Record the final search disposition'],
  },
  {
    slug: 'offshore-estate-planning-execution-packet-check',
    published: '2026-08-31',
    title: 'Estate-planning execution packet checks with offshore support',
    excerpt: 'Check approved packet components, names, versions, and logistics while counsel controls advice, capacity questions, formalities, and execution.',
    subject: 'estate-planning execution packet checks',
    thesis: 'Packet preparation can remove clerical friction, but a completed checklist cannot certify that a document is valid or properly executed.',
    sources: 'the attorney-approved document list, final version instructions, client identity details supplied by the firm, scheduling notes, and execution checklist',
    record: 'a packet inventory linking every document and signature page to its approved version and open logistics question',
    reviewer: 'the drafting attorney or authorized estate-planning paralegal',
    reserved: 'advice, document selection, testamentary capacity, undue influence, witness or notary requirements, legal sufficiency, and execution approval',
    risk: 'a tidy packet may conceal a version error, identity mismatch, missing page, or unresolved execution requirement',
    opening: 'Execution packets deserve slower handling than ordinary mail merges. Similar names, revised distributions, replacement signature pages, and separate notarial materials make visual neatness unreliable. The support worker should compare every included file with the final list supplied by the firm.',
    exception: 'Stop for changed client instructions, mismatched names, uncertain final versions, missing pages, witness questions, health or capacity concerns, and requests to explain legal effect.',
    measure: 'Check version lineage, document count, page count, identity fields, open questions, access discipline, and attorney release evidence.',
    close: 'The support role can make the physical or electronic packet reviewable. The lawyer retains every judgment about advice and execution.',
    headings: ['Lock the approved document list', 'Compare identity fields without correcting them', 'Trace every signature page to a version', 'Keep scheduling logistics factual', 'Pause when circumstances change', 'Release the packet through the named reviewer'],
  },
  {
    slug: 'law-firm-immigration-document-receipt-register',
    published: '2026-08-31',
    title: 'Immigration document-receipt registers for offshore support',
    excerpt: 'Track client-supplied records, translations, versions, and gaps without deciding eligibility, evidentiary weight, or filing strategy.',
    subject: 'immigration document-receipt registration',
    thesis: 'A receipt register should tell the legal team what arrived and how it maps to an approved request, while leaving evidentiary and immigration judgments untouched.',
    sources: 'the attorney-approved request list, portal uploads, delivery messages, file metadata, translation status, and client identifiers authorized for the matter',
    record: 'a document-level register showing source, receipt time, request category, apparent date range, version, translation state, and review status',
    reviewer: 'the immigration attorney or supervising paralegal',
    reserved: 'eligibility, filing category, sufficiency, authenticity, translation acceptance, deadlines, representations, and client advice',
    risk: 'received can be confused with reviewed, sufficient, authentic, or ready to file',
    opening: 'Clients may upload several photographs of the same record, a scan with missing edges, or a translation without the source document. Those events should appear plainly in the register. Combining them into a single complete status deprives the reviewer of useful facts.',
    exception: 'Route unreadable files, unexplained identity differences, missing source-language pages, password-protected documents, unexpected sensitive data, and questions about what a client must provide.',
    measure: 'Sample source-to-register fidelity, duplicate handling, translation labels, request mapping, unresolved gaps, and access to client records.',
    close: 'The register succeeds when the legal team can review the supplied evidence without reconstructing the upload history. It must not promise a filing outcome.',
    headings: ['Create a receipt event for every delivery', 'Keep duplicates and versions distinct', 'Label translation status precisely', 'Map files to requests without judging sufficiency', 'Protect identity information in the queue', 'Prepare a gap view for attorney review'],
  },
  {
    slug: 'offshore-real-estate-closing-condition-tracker',
    published: '2026-08-31',
    title: 'Real-estate closing condition trackers with offshore legal support',
    excerpt: 'Organize approved conditions, source documents, owners, and evidence while lawyers decide satisfaction, waiver, and closing readiness.',
    subject: 'real-estate closing condition tracking',
    thesis: 'A tracker can show documentary progress, but only an authorized reviewer can decide that a condition is satisfied, waived, or no longer applicable.',
    sources: 'the executed agreement, attorney-approved closing checklist, amendments, party correspondence, delivered documents, and written reviewer instructions',
    record: 'a condition-level tracker with clause reference, requested evidence, source link, owner, received state, question, and review disposition',
    reviewer: 'the transaction attorney or closing coordinator designated by the firm',
    reserved: 'contract interpretation, satisfaction, waiver, legal sufficiency, title decisions, funds movement, execution, and authorization to close',
    risk: 'an uploaded document may appear to close a condition even though counsel has not reviewed its content or effect',
    opening: 'Closing trackers become dangerous when status colors replace language. A document may be received, under review, rejected, superseded, or accepted subject to another item. Each state should remain distinct, and every change should point to a source or reviewer instruction.',
    exception: 'Escalate conflicting amendments, unexpected parties, missing signatures, changed funding instructions, disputed status, unclear clause references, and any request to mark a legal condition complete.',
    measure: 'Inspect clause mapping, evidence links, status authority, version control, aging questions, recipient approvals, and changes near the closing date.',
    close: 'Good administration lets counsel see the transaction without treating the tracker as the transaction. Closing authority remains outside the support lane.',
    headings: ['Build from the approved closing list', 'Describe documentary states accurately', 'Link each status change to evidence', 'Separate reminders from legal positions', 'Lock down changed payment instructions', 'Require an authorized closing disposition'],
  },
  {
    slug: 'legal-support-offshore-spend-accrual-request-log',
    published: '2026-08-31',
    title: 'Legal-spend accrual request logs for offshore support',
    excerpt: 'Coordinate approved accrual requests, responses, matter identifiers, and exceptions while finance and lawyers control estimates and reporting judgments.',
    subject: 'legal-spend accrual request logging',
    thesis: 'Support staff can make an accrual cycle complete and traceable without creating estimates or deciding how financial information should be reported.',
    sources: 'the approved matter roster, finance request, timekeeper or vendor response, billing-system references, and written submission instructions',
    record: 'a cycle-specific log connecting each request, response, source period, exception, reviewer, and submitted state',
    reviewer: 'the legal-operations manager, finance owner, or responsible attorney named by the firm',
    reserved: 'the estimate, accounting treatment, materiality, write-off, client-billing choice, financial representation, and final submission',
    risk: 'a copied or stale amount can enter a report when the period, source, currency, or approving owner is unclear',
    opening: 'Accrual work is repetitive, which makes it suitable for a bounded support lane, but repetition can hide stale data. Every cycle needs its own date range and source identity. A prior response should never roll forward merely because a new response has not arrived.',
    exception: 'Route missing periods, conflicting currencies, duplicated matters, unexpected negative amounts, uncertain owners, late responses, and any request to calculate or approve an estimate.',
    measure: 'Check request coverage, period labels, source preservation, currency fields, response age, approval evidence, and late-item escalation.',
    close: 'The log should reveal who supplied each figure and what remains open. Finance and the firm decide what the figures mean and whether they may be reported.',
    headings: ['Define the reporting cycle', 'Send requests from an approved roster', 'Preserve figures exactly as supplied', 'Do not roll forward silent matters', 'Route exceptions before compilation', 'Record review and submission separately'],
  },
  {
    slug: 'offshore-deposition-exhibit-provenance-log',
    published: '2026-08-31',
    title: 'Deposition exhibit provenance logs with offshore legal support',
    excerpt: 'Trace proposed exhibits to source files, versions, labels, and preparation instructions while counsel controls use, objections, and examination strategy.',
    subject: 'deposition exhibit provenance logging',
    thesis: 'Provenance makes exhibit preparation reviewable. It does not establish admissibility, authenticity, relevance, or the sequence counsel will use.',
    sources: 'the attorney-approved candidate list, source repository, document metadata, prior labels, production references, and preparation instructions',
    record: 'a proposed-exhibit log connecting each working copy and label to its source, version, page range, and reviewer state',
    reviewer: 'the examining attorney or litigation-support lead',
    reserved: 'selection, use, order, questioning, objections, authenticity, admissibility, privilege, redaction, and final exhibit designation',
    risk: 'a clean working copy can lose the context needed to identify its source or distinguish it from another version',
    opening: 'An exhibit folder often contains documents gathered for different reasons. The support worker should never infer that presence in the folder means counsel selected the document. Candidate, prepared, reviewed, and designated are separate states that need separate authority.',
    exception: 'Pause for mismatched Bates ranges, missing pages, unclear redactions, duplicate labels, absent source files, privilege indicators, or new substantive preparation requests.',
    measure: 'Review source links, hashes or stable identifiers where used, page ranges, label uniqueness, version fidelity, reviewer disposition, and release controls.',
    close: 'A provenance log saves attorney time because it makes the preparation trail visible. Counsel retains every litigation choice.',
    headings: ['Distinguish candidates from selected exhibits', 'Preserve the source identity', 'Control working copies and labels', 'Flag page and version conflicts', 'Hold substantive choices for the attorney', 'Archive the used and unused disposition'],
  },
  {
    slug: 'law-firm-subpoena-service-return-register',
    published: '2026-08-31',
    title: 'Subpoena service-return registers for offshore legal support',
    excerpt: 'Record approved service documents, vendor updates, returns, and delivery evidence while counsel decides validity, response, and enforcement.',
    subject: 'subpoena service-return registration',
    thesis: 'A service register should preserve events and evidence without characterizing service as legally effective.',
    sources: 'the attorney-approved subpoena version, recipient information, vendor instruction, status messages, return or affidavit, delivery evidence, and court information',
    record: 'a subpoena-level chronology linking each instruction, attempt, communication, and returned document to its source',
    reviewer: 'the issuing or responding attorney and designated docket owner',
    reserved: 'validity, method, timing, objections, compliance, enforcement, deadline calculation, and representations to a court or recipient',
    risk: 'a vendor status such as delivered may be repeated as valid service without legal review of the facts',
    opening: 'The register should use the words found in the source. Attempted, delivered, refused, forwarded, and returned are observations or vendor statuses, not interchangeable legal conclusions. Keep the original document and every later correction linked to the same event history.',
    exception: 'Escalate changed addresses, recipient disputes, inconsistent dates, incomplete returns, service outside instructions, requests for alternate methods, and questions about response periods.',
    measure: 'Check subpoena-version identity, event chronology, exact vendor wording, document links, recipient data, attorney review, and unresolved attempts.',
    close: 'A precise register gives counsel the facts needed for the next decision. It should stop before stating what the service accomplished legally.',
    headings: ['Lock the approved subpoena version', 'Log attempts as events', 'Quote vendor statuses accurately', 'Attach returns without interpreting them', 'Send timing questions to the docket owner', 'Preserve corrections in the chronology'],
  },
  {
    slug: 'offshore-regulatory-filing-correspondence-index',
    published: '2026-08-31',
    title: 'Regulatory filing correspondence indexes with offshore support',
    excerpt: 'Organize approved agency messages, filing receipts, questions, and response drafts while counsel controls interpretation and submissions.',
    subject: 'regulatory filing correspondence indexing',
    thesis: 'An index can expose the full agency communication trail without deciding what an agency message requires or whether a filing is compliant.',
    sources: 'the filing copy, portal receipt, agency correspondence, approved response drafts, delivery evidence, and reviewer instructions',
    record: 'a chronological index with agency, filing identity, sender, recipient, subject, source link, requested follow-up, owner, and review state',
    reviewer: 'the regulatory attorney or compliance owner authorized by the client',
    reserved: 'legal interpretation, compliance, response strategy, amendment, certification, deadline calculation, and agency communication approval',
    risk: 'an administrative subject line or portal status can be mistaken for an agency determination',
    opening: 'Agency portals and email threads often describe the same filing differently. The index should preserve those identifiers rather than forcing them into one preferred label. It should also keep automated receipts separate from messages that contain a reviewer question or request.',
    exception: 'Route unfamiliar agency contacts, conflicting filing numbers, portal warnings, changed due dates, certification language, missing attachments, and requests for a substantive response.',
    measure: 'Review chronology, identifier mapping, receipt preservation, attachment completeness, owner assignment, response authorization, and unresolved agency questions.',
    close: 'The index reduces search time and missed handoffs. It does not convert portal data into legal advice or a compliance finding.',
    headings: ['Map every filing identity', 'Separate automated receipts from agency messages', 'Keep attachments with their communication', 'Route requested action to an owner', 'Control response drafts and recipients', 'Close the loop with submission evidence'],
  },
  {
    slug: 'legal-support-legal-opinion-reliance-materials-log',
    published: '2026-08-31',
    title: 'Legal-opinion reliance materials logs for offshore support',
    excerpt: 'Inventory approved certificates, representations, drafts, and source documents while opinion counsel controls scope, reliance, and legal analysis.',
    subject: 'legal-opinion reliance materials logging',
    thesis: 'A reliance-materials log should show what opinion counsel received and which version is under review. It must not suggest that a condition or legal conclusion has been met.',
    sources: 'the attorney-approved request list, certificates, governing documents, representations, transaction drafts, signatures, and written opinion-team instructions',
    record: 'a request-level log connecting each supplied item, version, source, date, open question, and reviewer disposition',
    reviewer: 'opinion counsel or the transaction lawyer responsible for the request',
    reserved: 'opinion scope, assumptions, qualifications, reliance, legal conclusions, document adequacy, signature authority, and release',
    risk: 'received materials may look complete while containing an unapproved draft, expired certificate, missing annex, or inconsistent representation',
    opening: 'Opinion support depends on exact versions. A certificate with the right title but the wrong date is not interchangeable with the requested certificate. The support worker should describe the mismatch and preserve both records instead of selecting the more convenient file.',
    exception: 'Escalate stale certificates, unsigned documents, inconsistent entity names, missing schedules, unapproved drafts, changed transaction terms, and every question about adequacy or reliance.',
    measure: 'Check request mapping, document date, signature state, version lineage, missing schedules, source location, reviewer notes, and release authority.',
    close: 'The log makes the document set easier for opinion counsel to inspect. Only counsel decides whether the materials support any opinion.',
    headings: ['Start from counsel’s request list', 'Treat document dates as data', 'Keep drafts and signed copies distinct', 'Describe gaps without judging adequacy', 'Record each reviewer disposition', 'Freeze the release set'],
  },
];

const paragraphs = (t: Topic) => [
  `${t.opening} ${t.thesis} On August 31, 2026, this distinction is the starting point for a controlled ${t.subject} workflow at a law firm using offshore legal support.`,
  `The approved inputs are ${t.sources}. Give the worker access only to the assigned matters and systems needed for those records. Each item should retain its original identity, source location, received time, and version. If the source is incomplete, the register should say incomplete. If two sources conflict, keep both and state the conflict without choosing which one controls. A support worker may transcribe, sort, compare, link, and flag these facts. The firm should not ask the worker to fill an empty field from memory or by searching unrelated client files.`,
  `The expected output is ${t.record}. Define the required fields before the first live item. Include a matter or transaction identifier, source reference, preparer, timestamp, status, next owner, and an open-question field. Avoid status words that imply a legal conclusion. Received, located, awaiting review, conflicting, and instruction recorded describe administrative events. Valid, sufficient, compliant, privileged, authorized, and final may carry judgments that belong elsewhere. The wording should help ${t.reviewer} see the facts without having to reverse an unsupported conclusion.`,
  `The firm retains ${t.reserved}. Put that reservation in the role brief, operating guide, and first-week coaching. ${t.risk}. The worker should never send a filing, notice, client message, vendor instruction, or third-party response unless the firm has approved the exact action, recipient, and version. Preparation and release are separate steps. An internal checklist can be complete while the related legal work is still awaiting review.`,
  `${t.exception} The worker should preserve the item, write the narrow question, assign it to ${t.reviewer}, and record the time sent. A good escalation includes the source link and explains what prevents the next administrative step. It should not contain a proposed legal answer. If no one responds within the agreed window, the queue should move to a named backup owner rather than letting the worker invent a path. Personal email, private notes, and unofficial copies should not become a second system of record.`,
  `Begin the pilot with one approved example and a deliberately small batch. On the first day, review the source boundary, output fields, permissions, and stop rule. Ask the worker to explain which source supports each populated field. On the next batch, check every item against its source and discuss each exception. Only then should the manager decide whether some clean items can move to sample review. A change in matter type, system, instruction, or assigned worker should return the lane to closer review until the new pattern is stable.`,
  `${t.measure} Count rework by reason rather than using one vague error total. Useful reasons include wrong source, missing field, version mismatch, unsupported inference, late escalation, incorrect recipient, and access problem. Review both ordinary items and exceptions. A fast queue with hidden assumptions is not healthy. Managers should value a precise stop because it protects the client file and shows that the role boundary is understood.`,
  `Confidentiality belongs inside the routine. Use individual accounts, the firm's approved authentication controls, matter-level permissions, and approved transfer methods. Redact examples when possible. Do not paste client information into an unapproved tool. If the worker opens the wrong matter, sees an unexpected permission, or sends information to the wrong recipient, the instruction is to stop and report facts promptly. The firm decides account suspension, evidence preservation, notifications, correction, and any client communication. The worker should not delete evidence or quietly repair the trail.`,
  `The handoff should tell the reviewer what was requested, what was found, which source supports the record, what remains uncertain, and who owns the next decision. Keep original records separate from working copies, and retain corrections as part of the history. A later reviewer should be able to reconstruct the administrative path without relying on chat memory. This is especially important when time zones divide the working day. The offshore team can prepare an orderly morning handoff, but urgency and deadlines still come from firm-approved rules and instructions.`,
  `${t.close} Ask the firm to settle five operational questions before volume grows: which records are allowed, who reviews exceptions, what response window applies, who acts as backup, and how access is removed when the assignment ends. Those answers turn ${t.subject} into a supervised support lane. They do not transfer professional responsibility. The offshore worker prepares a factual, traceable record; authorized firm personnel interpret, approve, communicate, and remain responsible for the client relationship.`,
];

function sections(t: Topic, topicIndex: number) {
  const body = paragraphs(t);
  const order = Array.from({ length: body.length }, (_, i) => (i * (topicIndex % 3 + 3)) % body.length);
  const uniqueOrder = [...new Set(order), ...Array.from({ length: body.length }, (_, i) => i)].slice(0, body.length);
  return uniqueOrder.map((bodyIndex, sectionIndex) => ({
    heading: sectionIndex < t.headings.length ? t.headings[sectionIndex] : ['Pilot and review method', 'Confidentiality in daily handling', 'Handoff across time zones', 'Manager questions before expansion'][sectionIndex - t.headings.length],
    body: body[bodyIndex],
  }));
}

export const august31Leg58BlogPosts = topics.map((topic, index) => ({
  slug: topic.slug,
  title: topic.title,
  excerpt: topic.excerpt,
  published: topic.published,
  modified: '2026-08-31',
  minutes: 10,
  sections: sections(topic, index),
}));
