type Topic={slug:string;title:string;excerpt:string;work:string;inputs:string;record:string;owner:string;stop:string;example:string;image:string};

const topics:readonly Topic[]=[
 {slug:'offshore-legal-support-discovery-production-receipt-ledger',title:'Discovery production receipt ledgers for offshore legal support',excerpt:'Connect counsel-approved productions to delivery and receipt evidence while lawyers control scope, objections, and compliance conclusions.',work:'discovery production receipt logging',inputs:'the approved production set, transmittal, delivery event, recipient record, and counsel instruction',record:'production identifier, volume label, sent version, channel, delivery time, receipt evidence, discrepancy, and reviewer decision',owner:'discovery counsel',stop:'the transmitted set differs, delivery fails, a recipient is unexpected, receipt is disputed, or compliance must be assessed',example:'The transfer portal shows delivery, but the transmittal lists one more volume than the portal. Preserve both records and route the count difference.',image:'/aug21-heroes/offshore-legal-support-production-readiness-board.png'},
 {slug:'law-firm-offshore-appeal-record-citation-table',title:'Appeal record citation tables prepared by offshore legal teams',excerpt:'Map counsel-selected record cites to source pages without choosing authority, argument, or the contents of a filing.',work:'appeal record citation-table preparation',inputs:'the counsel-approved record, brief draft, citation list, pagination map, and written instruction',record:'draft reference, source document, record page, PDF page, quoted text as supplied, mismatch, reviewer, and disposition',owner:'appellate counsel',stop:'pagination conflicts, quoted text differs, a document is absent, relevance is questioned, or a citation would be selected',example:'A draft cites record page 412 while the quoted line appears on PDF page 414. Record both page systems instead of changing the citation.',image:'/aug23-heroes/legal-research-request-logs.png'},
 {slug:'offshore-legal-support-insurance-coverage-correspondence-index',title:'Insurance coverage correspondence indexes for offshore legal support',excerpt:'Organize policy and claim messages by source and version while coverage counsel controls interpretation and response.',work:'coverage correspondence indexing',inputs:'the approved policy set, claim notices, carrier messages, attachments, and counsel categories',record:'message date, sender, recipient, subject, policy or claim reference, attachment set, stated position, source, and open question',owner:'coverage counsel',stop:'policy references conflict, an attachment is missing, a response is requested, a date needs interpretation, or coverage meaning is at issue',example:'A carrier message cites an endorsement that is not in the supplied policy set. Log the citation and missing source without describing its effect.',image:'/aug21-heroes/offshore-legal-support-vendor-evidence-log.png'},
 {slug:'law-firm-offshore-lease-abstract-source-check',title:'Lease abstract source checks for law firm offshore teams',excerpt:'Compare approved abstract fields with executed lease sources while real-estate counsel owns interpretation and reliance.',work:'lease abstract source checking',inputs:'the executed lease, approved amendments, current abstract, counsel-defined fields, and review instruction',record:'field label, abstract value, source clause, document version, visible value, variance, reviewer, and disposition',owner:'real-estate counsel',stop:'documents compete, a term is undefined, arithmetic is required, an amendment is missing, or legal effect must be stated',example:'The abstract says monthly notice while the source clause states a number of days. Flag the variance without converting one expression into the other.',image:'/sep3-heroes/lease-abstraction-source-note-register.png'},
 {slug:'offshore-legal-support-ip-renewal-instruction-register',title:'IP renewal instruction registers for offshore legal support',excerpt:'Track owner-approved renewal instructions and vendor acknowledgments without deciding rights, deadlines, or filing strategy.',work:'IP renewal instruction registration',inputs:'the counsel-approved portfolio list, official records supplied by the firm, vendor messages, payment evidence, and instructions',record:'asset reference, jurisdiction, instruction version, stated date, vendor acknowledgment, evidence link, exception, and owner',owner:'IP counsel',stop:'ownership differs, a date needs calculation, instructions conflict, a fee changes, or a filing action is requested',example:'A vendor acknowledges the instruction under a legacy owner name. Preserve both names and ask IP counsel to reconcile the identity.',image:'/sep3-heroes/trademark-specimen-intake-inventory.png'},
 {slug:'law-firm-offshore-witness-contact-permission-log',title:'Witness contact permission logs for law firm offshore teams',excerpt:'Record counsel-approved contact parameters and communication events while lawyers retain strategy and contact authority.',work:'witness contact permission logging',inputs:'the approved witness list, contact instruction, supplied contact details, communication record, and counsel updates',record:'witness label, approved purpose, permitted channel, instruction version, contact event, outcome as stated, restriction, and reviewer',owner:'litigation counsel',stop:'identity is uncertain, the witness raises a substantive question, permission changes, counsel status is unclear, or another contact is proposed',example:'A witness replies from a new address and asks about testimony. Record the new address and question, then stop without answering.',image:'/aug21-heroes/law-firm-offshore-support-client-update-register.png'},
 {slug:'offshore-legal-support-entity-signatory-authority-packet-index',title:'Entity signatory authority packet indexes for offshore support',excerpt:'Assemble approved organizational records and signature evidence while corporate counsel decides authority and validity.',work:'signatory authority packet indexing',inputs:'the approved entity chart, governing records, resolutions, incumbency materials, signature pages, and counsel instruction',record:'entity, document type, visible date, named person, stated office, version, signature evidence, gap, and reviewer',owner:'corporate counsel',stop:'names or offices differ, records are stale, signatures are missing, entity relationships are unclear, or authority must be concluded',example:'A resolution names a treasurer while the incumbency certificate names a chief financial officer. Preserve both titles and route the difference.',image:'/sep3-heroes/board-consent-signature-collection-tracker.png'},
 {slug:'law-firm-offshore-bankruptcy-claim-document-inventory',title:'Bankruptcy claim document inventories with offshore legal support',excerpt:'Inventory counsel-approved claim records and filing evidence without deciding priority, allowance, valuation, or response.',work:'bankruptcy claim document inventory',inputs:'the approved claim file, court records supplied by counsel, supporting documents, notices, and written categories',record:'claim reference, debtor label, creditor label, document type, visible amount, filing state as displayed, source, gap, and reviewer',owner:'bankruptcy counsel',stop:'amounts conflict, identity differs, a schedule is missing, priority is questioned, or a court response is contemplated',example:'The proof of claim and internal ledger display different totals. Log each total with its source rather than calculating a replacement.',image:'/aug23-heroes/billing-exception-queues.png'},
 {slug:'offshore-legal-support-data-room-download-manifest',title:'Data room download manifests for offshore legal transactions',excerpt:'Trace approved exports from a transaction data room while deal counsel controls scope, privilege, and distribution.',work:'data room download manifest preparation',inputs:'the approved folder scope, platform export report, downloaded files, access instruction, and recipient plan',record:'workspace, folder path, item name, platform identifier, version, download event, manifest hash if supplied, exception, and reviewer',owner:'deal counsel',stop:'scope changes, a restricted folder appears, counts differ, permissions fail, or material would be redistributed',example:'The platform report lists 98 files while the archive contains 97. Preserve the untouched archive and report the missing count.',image:'/aug23-heroes/privileged-folder-permissions.png'},
 {slug:'law-firm-offshore-medical-record-provider-gap-log',title:'Medical record provider gap logs for law firm offshore teams',excerpt:'Track requested and received provider records while qualified reviewers decide completeness, relevance, and medical meaning.',work:'medical record provider gap logging',inputs:'the approved provider list, requests, delivery records, supplied medical files, and attorney instruction',record:'provider as supplied, requested period, request event, received file, visible service dates, unreadable segment, stated gap, and owner',owner:'the responsible attorney or qualified medical reviewer',stop:'patient identity differs, a provider is new, records are unreadable, authorization is questioned, or medical interpretation is needed',example:'A delivery covers the stated period but begins mid-visit. Log the visible first page and possible missing pages without calling the set incomplete.',image:'/sep3-heroes/litigation-medical-records-chronology-intake.png'},
 {slug:'offshore-legal-support-regulatory-filing-acknowledgment-index',title:'Regulatory filing acknowledgment indexes for offshore legal support',excerpt:'Connect approved submissions with regulator receipts while counsel controls filing status, sufficiency, and follow-up.',work:'regulatory filing acknowledgment indexing',inputs:'the approved submission, delivery evidence, regulator acknowledgment, portal record supplied by counsel, and instructions',record:'filing label, submitted version, transmission event, acknowledgment identifier, displayed status, attachment, discrepancy, and reviewer',owner:'regulatory counsel',stop:'versions conflict, an identifier is absent, the portal requests action, timing needs interpretation, or acceptance must be declared',example:'The acknowledgment uses the expected identifier but shows a different attachment count. Record the difference before any follow-up.',image:'/sep3-heroes/regulatory-comment-letter-source-packet.png'},
 {slug:'law-firm-offshore-litigation-vendor-invoice-matter-check',title:'Litigation vendor invoice matter checks for offshore teams',excerpt:'Compare approved vendor invoices with matter and order records while firm owners decide payment, reasonableness, and allocation.',work:'litigation vendor invoice matter checking',inputs:'the vendor invoice, approved engagement or order, matter list, delivery evidence, and reviewer rules',record:'invoice reference, vendor, matter, service date as shown, line description, stated amount, source match, exception, and approver',owner:'litigation counsel and the authorized finance owner',stop:'matter identity differs, services lack a source, totals conflict, bank details change, or payment action is requested',example:'An invoice lists the right matter number but a service date outside the supplied order period. Flag the dates without deciding whether the charge is payable.',image:'/aug23-heroes/billing-exception-queues.png'},
];

const sections=(t:Topic,i:number)=>[
 {heading:`Set the boundary for ${t.work}`,body:`Published September 10, 2026. Use control ID S10-B${String(i+1).padStart(2,'0')} and name ${t.owner} before work starts. The offshore role prepares a source-linked administrative record. Legal analysis, approval, advice, and external action stay with the firm.`},
 {heading:'Freeze the approved inputs',body:`Work only from ${t.inputs}. Note the source location, visible version, access time, and instruction author. Do not replace a missing item or choose between conflicting records.`},
 {heading:'Build the working record',body:`Capture ${t.record}. Keep copied facts separate from observations and owner decisions. Retain the earlier value when an authorized correction arrives so another reviewer can reconstruct the handoff.`},
 {heading:'Work through one realistic exception',body:`${t.example} The record should show the exact sources involved, the observed difference, and the person who owns the decision.`},
 {heading:'Stop at the judgment line',body:`Pause when ${t.stop}. Send ${t.owner} the relevant source links and one precise question. Prepared, checked, approved, transmitted, and accepted are different states.`},
 {heading:'Test the routine on a bounded sample',body:'Choose a small cohort before work begins and include at least one known exception. Review source selection, field accuracy, version handling, access scope, escalation, and disposition separately. Publish the denominator and period with any count. A pilot result applies only to the sampled task and instructions.'},
 {heading:'Protect matter information',body:'Use named accounts, matter-limited permissions, firm-approved devices, and approved transfer paths. Put source references in the tracker instead of copying confidential text when a link is sufficient. Stop and follow the firm incident path if information appears in the wrong location.'},
 {heading:'Close with an attributable disposition',body:`Close an item only after ${t.owner} records a decision and any correction points back to the earlier observation. Remove temporary access when instructed and retain evidence under firm policy. Reopen the design review when the task, system, source, instruction, reviewer, or client requirement changes.`},
];

export const september10BlogPosts=topics.map((topic,index)=>({slug:topic.slug,title:topic.title,excerpt:topic.excerpt,published:'2026-09-10' as const,modified:'2026-09-10',minutes:8,featuredImage:topic.image,sections:sections(topic,index)}));
