export type FleetService = { slug: string; title: string; desc: string; tasks: readonly string[]; controls: readonly string[]; firstWeek: readonly string[] };
export type ResearchPost = { slug: string; title: string; excerpt: string; published: string; cluster: string; headlineStat: string; sections: readonly { heading: string; body: string }[]; sources: readonly { name: string; url: string }[]; relatedSlugs: readonly string[]; thumbnail: string; };

export const fleetServices: readonly FleetService[] = [
  { slug: 'legal-intake-support', title: 'Legal Intake Support', desc: 'Build a Philippines-based legal intake support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring legal operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'litigation-document-review', title: 'Litigation Document Review', desc: 'Build a Philippines-based litigation document review workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring legal operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'contract-administration', title: 'Contract Administration', desc: 'Build a Philippines-based contract administration workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring legal operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'legal-research-support', title: 'Legal Research Support', desc: 'Build a Philippines-based legal research support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring legal operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'case-file-management', title: 'Case File Management', desc: 'Build a Philippines-based case file management workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring legal operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'e-discovery-support', title: 'E-Discovery Support', desc: 'Build a Philippines-based e-discovery support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring legal operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'immigration-case-administration', title: 'Immigration Case Administration', desc: 'Build a Philippines-based immigration case administration workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring legal operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'real-estate-legal-support', title: 'Real Estate Legal Support', desc: 'Build a Philippines-based real estate legal support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring legal operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'corporate-records-support', title: 'Corporate Records Support', desc: 'Build a Philippines-based corporate records support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring legal operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'billing-and-time-entry-support', title: 'Billing and Time Entry Support', desc: 'Build a Philippines-based billing and time entry support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring legal operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] }
];

const researchSources = [
  { name: 'ABA Formal Opinion 477R: Securing Communication of Protected Client Information', url: 'https://www.americanbar.org/content/dam/aba/administrative/professional_responsibility/formal-opinions/477r.pdf' },
  { name: 'NIST Cybersecurity Framework 2.0', url: 'https://nvlpubs.nist.gov/nistpubs/CSWP/NIST.CSWP.29.pdf' },
  { name: 'NIST SP 800-207: Zero Trust Architecture', url: 'https://csrc.nist.gov/pubs/sp/800/207/final' },
  { name: 'FTC Safeguards Rule', url: 'https://www.ftc.gov/legal-library/browse/rules/safeguards-rule' },
  { name: 'HHS Security Rule', url: 'https://www.hhs.gov/hipaa/for-professionals/security/index.html' },
  { name: 'ICO Data Protection by Design and Default', url: 'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/accountability-and-governance/data-protection-by-design-and-default/' },
  { name: 'ICO Data Sharing Code of Practice', url: 'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/data-sharing/data-sharing-a-code-of-practice/' },
  { name: 'SRA Standards and Regulations: Confidentiality and Disclosure', url: 'https://www.sra.org.uk/solicitors/standards-regulations/code-conduct-solicitors/' },
  { name: 'Law Society Outsourcing Guidance', url: 'https://www.lawsociety.org.uk/topics/business-management/outsourcing' },
  { name: 'CISA Cloud Security', url: 'https://www.cisa.gov/topics/cloud-security' },
  { name: 'OWASP Application Logging Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html' },
  { name: 'NIST SP 800-61 Rev. 2: Computer Security Incident Handling Guide', url: 'https://csrc.nist.gov/pubs/sp/800/61/r2/final' },
] as const;

const makeResearch = (slug: string, title: string, excerpt: string, cluster: string, headlineStat: string, focus: string, relatedSlugs: readonly string[]): ResearchPost => ({
  slug, title, excerpt, cluster, headlineStat, published: '2026-08-07', relatedSlugs, thumbnail: '/research-thumbnails/research-default.svg',
  sections: [
    { heading: 'Methodology', body: `This report compares ${researchSources.length} regulator, standards, and professional-body sources against one practical question: ${focus} We separate source requirements from operating recommendations and treat attorney or firm-manager review as the final decision gate.` },
    { heading: 'Key Stats', body: `${headlineStat} The source set contains ${researchSources.length} named references; the number is a coverage count for this report, not a claim about market performance. Validate local professional, privacy, and client-contract requirements before implementation.` },
    { heading: 'Key Takeaways', body: `Start with a narrow task definition, named owner, least-privilege access, a written exception path, and an auditable review sample. Offshore support can prepare and organize work, but it should not silently expand into legal advice, judgment, or client promises.` },
    { heading: 'Control design', body: `Write the input, output, system, deadline, reviewer, and stop rule for ${focus}. Use individual accounts, approved templates, and a small first-week sample. Record what was received, what was changed, what remains uncertain, and who approved the handoff.` },
    { heading: 'Evidence and handoff', body: `Keep source notes with the work product, preserve the original client instruction, and log exceptions in plain language. A manager should be able to reconstruct the handoff without relying on a private chat or an untracked spreadsheet.` },
    { heading: 'Questions for the firm', body: `Which facts may the support role enter? Which fields require attorney review? What happens when a source conflicts, a deadline is unclear, or a client asks for advice? Who can pause the queue and who confirms the next safe step?` },
    { heading: 'FAQs', body: `Can this work be outsourced? Usually, repeatable preparation and administration can be scoped for support when confidentiality, access, supervision, and review are explicit. Can the role make a legal decision? No; route judgment, advice, filing strategy, and exceptions to the designated firm owner.` },
  ], sources: researchSources,
});

// Reviewed, source-backed original research. The templates and sitemap update automatically.
export const researchPosts: readonly ResearchPost[] = [
  makeResearch('legal-intake-support-control-benchmark', 'Legal intake support control benchmark', 'A source-backed control model for routing new legal inquiries without turning intake staff into legal advisers.', 'Hiring Controls', '12 primary sources frame the intake control checklist.', 'new legal-intake notes, routing, and escalation', ['legal-client-data-access-review', 'offshore-legal-support-quality-scorecard', 'legal-research-administration-boundaries']),
  makeResearch('offshore-legal-document-prep-review-gates', 'Offshore legal document preparation: review-gate research', 'How firms can separate formatting and checklist work from legal substance with visible approval points.', 'Workflow Design', '12 sources support a preparation-versus-judgment boundary.', 'document formatting, assembly, and checklist completion', ['legal-intake-support-control-benchmark', 'case-file-naming-and-records-cleanup', 'contract-administration-workflow']),
  makeResearch('legal-case-file-management-access-model', 'Legal case-file management access model', 'A practical access and evidence model for remote case-file organization and status maintenance.', 'Hiring Controls', '12 sources map access, logging, and incident-response controls.', 'case-file organization and approved status updates', ['legal-client-data-access-review', 'offshore-legal-support-quality-scorecard', 'legal-document-retention-workflow']),
  makeResearch('contract-administration-workflow', 'Contract administration workflow research', 'Define safe offshore contract administration around intake, metadata, renewal reminders, and counsel review.', 'Workflow Design', '12 sources support a metadata-first contract workflow.', 'contract metadata, reminders, and version handoffs', ['offshore-legal-document-prep-review-gates', 'legal-calendar-deadline-controls', 'legal-research-administration-boundaries']),
  makeResearch('legal-research-administration-boundaries', 'Where legal research administration should stop', 'Separate source gathering and citation organization from legal analysis, conclusions, and advice.', 'Hiring Controls', '12 sources reinforce traceability and a no-advice boundary.', 'source gathering, citation capture, and research-file organization', ['legal-intake-support-control-benchmark', 'offshore-legal-document-prep-review-gates', 'contract-administration-workflow']),
  makeResearch('legal-client-data-access-review', 'Legal client-data access review checklist', 'A research-backed checklist for granting, reviewing, and removing access for offshore support roles.', 'Hiring Controls', '12 sources turn access review into a repeatable control.', 'accounts, folders, and practice-system permissions', ['legal-case-file-management-access-model', 'remote-legal-support-incident-response', 'law-firm-offshore-support-scorecard']),
  makeResearch('legal-calendar-deadline-controls', 'Legal calendar and deadline control research', 'Design a support workflow that enters approved dates, flags gaps, and escalates uncertainty before it becomes a missed deadline.', 'Scope Benchmarks', '12 sources support explicit date ownership and exception routing.', 'calendar entries, deadline checks, and exception notes', ['contract-administration-workflow', 'offshore-legal-support-quality-scorecard', 'legal-case-file-management-access-model']),
  makeResearch('law-firm-offshore-support-scorecard', 'Law-firm offshore support quality scorecard', 'Choose a compact scorecard for accuracy, missing details, turnaround, rework, and escalation quality.', 'Scope Benchmarks', '12 sources inform the evidence, logging, and review fields.', 'sample review, rework tracking, and manager reporting', ['legal-client-data-access-review', 'legal-intake-support-control-benchmark', 'remote-legal-support-incident-response']),
  makeResearch('remote-legal-support-incident-response', 'Remote legal support incident-response workflow', 'Build a stop, preserve, notify, and review sequence for suspected access or confidentiality incidents.', 'Hiring Controls', '12 sources connect prevention, logging, and incident response.', 'suspected disclosure, access error, or security incident', ['legal-client-data-access-review', 'law-firm-offshore-support-scorecard', 'case-file-naming-and-records-cleanup']),
  makeResearch('case-file-naming-and-records-cleanup', 'Case-file naming and records cleanup research', 'Use naming rules, examples, sampling, and narrow access to improve records without broad file exposure.', 'Workflow Design', '12 sources support controlled records handling and traceable changes.', 'file naming, folder cleanup, and records metadata', ['legal-case-file-management-access-model', 'offshore-legal-document-prep-review-gates', 'legal-document-retention-workflow']),
  makeResearch('legal-document-retention-workflow', 'Legal document retention workflow research', 'A practical boundary for retention labels, disposition queues, and attorney-approved exceptions.', 'Workflow Design', '12 sources support documented retention decisions and exception handling.', 'retention metadata, review queues, and disposition preparation', ['case-file-naming-and-records-cleanup', 'legal-client-data-access-review', 'contract-administration-workflow']),
  makeResearch('e-discovery-support-chain-of-custody', 'E-discovery support chain-of-custody controls', 'Organize collection administration and evidence logs while reserving legal scope and privilege decisions for counsel.', 'Hiring Controls', '12 sources support preservation, provenance, and review gates.', 'collection inventories, hash records, and review handoffs', ['legal-research-administration-boundaries', 'remote-legal-support-incident-response', 'legal-case-file-management-access-model']),
  makeResearch('immigration-case-administration-controls', 'Immigration case administration controls', 'Scope document checklists, status tracking, and client follow-up while routing legal advice and eligibility questions to counsel.', 'Scope Benchmarks', '12 sources frame a documented intake and escalation boundary.', 'immigration case checklists, status updates, and follow-up', ['legal-intake-support-control-benchmark', 'legal-calendar-deadline-controls', 'law-firm-offshore-support-scorecard']),
];
export const postsPerPage = 20;
