export type FleetService = { slug: string; title: string; desc: string; tasks: readonly string[]; controls: readonly string[]; firstWeek: readonly string[] };
export type ResearchPost = { slug: string; title: string; excerpt: string; published: string; cluster: string; headlineStat: string; sections: readonly { heading: string; body: string }[]; sources: readonly { name: string; url: string }[]; relatedSlugs: readonly string[]; thumbnail: string; };

export const fleetServices: readonly FleetService[] = [
  { slug: 'legal-intake-support', title: 'Legal Intake Support', desc: 'Build a Philippines-based legal intake support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring legal operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'litigation-document-review', title: 'Litigation Document Review', desc: 'Build a Philippines-based litigation document review workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring legal operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'contract-administration', title: 'Contract Administration', desc: 'Build a Philippines-based contract administration workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring legal operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'legal-research-support', title: 'Legal Research Support', desc: 'Build a Philippines-based legal research support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring legal operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'case-file-management', title: 'Case File Management', desc: 'Build a Philippines-based case file management workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring legal operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'e-discovery-support', title: 'E-Discovery Support', desc: 'Build a Philippines-based e-discovery support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring legal operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'immigration-case-administration', title: 'Immigration Case Administration', desc: 'Build a Philippines-based immigration case administration workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring legal operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'real-estate-legal-support', title: 'Real Estate Legal Support', desc: 'Build a Philippines-based real estate legal support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring legal operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'corporate-records-support', title: 'Corporate Records Support', desc: 'Build a Philippines-based corporate records support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring legal operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'billing-and-time-entry-support', title: 'Billing and Time Entry Support', desc: 'Build a Philippines-based billing and time entry support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring legal operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] }
];

const researchSources = [
  { name: 'ABA Formal Opinion 477R: Securing Communication of Protected Client Information', url: 'https://www.americanbar.org/content/dam/aba/administrative/professional_responsibility/formal-opinions/477r.pdf' },
  { name: 'NIST Cybersecurity Framework 2.0', url: 'https://nvlpubs.nist.gov/nistpubs/CSWP/NIST.CSWP.29.pdf' },
  { name: 'NIST SP 800-207: Zero Trust Architecture', url: 'https://csrc.nist.gov/pubs/sp/800/207/final' },
  { name: 'FTC Safeguards Rule', url: 'https://www.ftc.gov/legal-library/browse/rules/safeguards-rule' },
  { name: 'HHS Security Rule', url: 'https://www.hhs.gov/hipaa/for-professionals/security/index.html' },
  { name: 'ICO Data Protection by Design and Default', url: 'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/accountability-and-governance/guide-to-accountability-and-governance/data-protection-by-design-and-by-default/' },
  { name: 'ICO Data Sharing Code of Practice', url: 'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/data-sharing/data-sharing-a-code-of-practice/' },
  { name: 'SRA Standards and Regulations: Confidentiality and Disclosure', url: 'https://www.sra.org.uk/solicitors/standards-regulations/code-conduct-solicitors/' },
  { name: 'Law Society Outsourcing Guidance', url: 'https://www.lawsociety.org.uk/topics/business-management/outsourcing' },
  { name: 'CISA Cloud Security Technical Reference Architecture', url: 'https://www.cisa.gov/sites/default/files/publications/CISA%20Cloud%20Security%20Technical%20Reference%20Architecture_Version%201.pdf' },
  { name: 'OWASP Application Logging Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html' },
  { name: 'NIST SP 800-61 Rev. 2: Computer Security Incident Handling Guide', url: 'https://csrc.nist.gov/pubs/sp/800/61/r2/final' },
] as const;

const makeResearch = (slug: string, title: string, excerpt: string, cluster: string, headlineStat: string, focus: string, relatedSlugs: readonly string[], published = '2026-08-07'): ResearchPost => ({
  slug, title, excerpt, cluster, headlineStat, published, relatedSlugs, thumbnail: '/research-thumbnails/research-default.svg',
  sections: [
    { heading: 'Methodology', body: `This report compares ${researchSources.length} regulator, standards, and professional-body sources against one practical question: ${focus} We separate source requirements from operating recommendations and treat attorney or firm-manager review as the final decision gate.` },
    { heading: 'Key Stats', body: `${headlineStat} The source set contains ${researchSources.length} named references; the number is a coverage count for this report, not a claim about market performance. Validate local professional, privacy, and client-contract requirements before implementation.` },
    { heading: 'Key Takeaways', body: `Start with a narrow task definition, named owner, least-privilege access, a written exception path, and an auditable review sample. Offshore support can prepare and organize work, but it should not silently expand into legal advice, judgment, or client promises.` },
    { heading: 'Control design', body: `Write the input, output, system, deadline, reviewer, and stop rule for ${focus}. Use individual accounts, approved templates, and a small first-week sample. Record what was received, what was changed, what remains uncertain, and who approved the handoff.` },
    { heading: 'Evidence and handoff', body: `Keep source notes with the work product, preserve the original client instruction, and log exceptions in plain language. A manager should be able to reconstruct the handoff without relying on a private chat or an untracked spreadsheet.` },
    { heading: 'Questions for the firm', body: `Which facts may the support role enter? Which fields require attorney review? What happens when a source conflicts, a deadline is unclear, or a client asks for advice? Who can pause the queue and who confirms the next safe step?` },
    { heading: 'FAQs', body: `Can this work be outsourced? Usually, repeatable preparation and administration can be scoped for support when confidentiality, access, supervision, and review are explicit. Can the role make a legal decision? No; route judgment, advice, filing strategy, and exceptions to the designated firm owner.` },
  ], sources: researchSources,
});

// Reviewed, source-backed original research. The templates and sitemap update automatically.
export const researchPosts: readonly ResearchPost[] = [
  makeResearch('legal-intake-support-control-benchmark', 'Legal intake support control benchmark', 'A source-backed control model for routing new legal inquiries without turning intake staff into legal advisers.', 'Hiring Controls', '12 primary sources frame the intake control checklist.', 'new legal-intake notes, routing, and escalation', ['legal-client-data-access-review', 'offshore-legal-support-quality-scorecard', 'legal-research-administration-boundaries']),
  makeResearch('offshore-legal-document-prep-review-gates', 'Offshore legal document preparation: review-gate research', 'How firms can separate formatting and checklist work from legal substance with visible approval points.', 'Workflow Design', '12 sources support a preparation-versus-judgment boundary.', 'document formatting, assembly, and checklist completion', ['legal-intake-support-control-benchmark', 'case-file-naming-and-records-cleanup', 'contract-administration-workflow']),
  makeResearch('legal-case-file-management-access-model', 'Legal case-file management access model', 'A practical access and evidence model for remote case-file organization and status maintenance.', 'Hiring Controls', '12 sources map access, logging, and incident-response controls.', 'case-file organization and approved status updates', ['legal-client-data-access-review', 'offshore-legal-support-quality-scorecard', 'legal-document-retention-workflow']),
  makeResearch('contract-administration-workflow', 'Contract administration workflow research', 'Define safe offshore contract administration around intake, metadata, renewal reminders, and counsel review.', 'Workflow Design', '12 sources support a metadata-first contract workflow.', 'contract metadata, reminders, and version handoffs', ['offshore-legal-document-prep-review-gates', 'legal-calendar-deadline-controls', 'legal-research-administration-boundaries']),
  makeResearch('legal-research-administration-boundaries', 'Where legal research administration should stop', 'Separate source gathering and citation organization from legal analysis, conclusions, and advice.', 'Hiring Controls', '12 sources reinforce traceability and a no-advice boundary.', 'source gathering, citation capture, and research-file organization', ['legal-intake-support-control-benchmark', 'offshore-legal-document-prep-review-gates', 'contract-administration-workflow']),
  makeResearch('legal-client-data-access-review', 'Legal client-data access review checklist', 'A research-backed checklist for granting, reviewing, and removing access for offshore support roles.', 'Hiring Controls', '12 sources turn access review into a repeatable control.', 'accounts, folders, and practice-system permissions', ['legal-case-file-management-access-model', 'remote-legal-support-incident-response', 'law-firm-offshore-support-scorecard']),
  makeResearch('legal-calendar-deadline-controls', 'Legal calendar and deadline control research', 'Design a support workflow that enters approved dates, flags gaps, and escalates uncertainty before it becomes a missed deadline.', 'Scope Benchmarks', '12 sources support explicit date ownership and exception routing.', 'calendar entries, deadline checks, and exception notes', ['contract-administration-workflow', 'offshore-legal-support-quality-scorecard', 'legal-case-file-management-access-model']),
  makeResearch('law-firm-offshore-support-scorecard', 'Law-firm offshore support quality scorecard', 'Choose a compact scorecard for accuracy, missing details, turnaround, rework, and escalation quality.', 'Scope Benchmarks', '12 sources inform the evidence, logging, and review fields.', 'sample review, rework tracking, and manager reporting', ['legal-client-data-access-review', 'legal-intake-support-control-benchmark', 'remote-legal-support-incident-response']),
  makeResearch('remote-legal-support-incident-response', 'Remote legal support incident-response workflow', 'Build a stop, preserve, notify, and review sequence for suspected access or confidentiality incidents.', 'Hiring Controls', '12 sources connect prevention, logging, and incident response.', 'suspected disclosure, access error, or security incident', ['legal-client-data-access-review', 'law-firm-offshore-support-scorecard', 'case-file-naming-and-records-cleanup']),
  makeResearch('case-file-naming-and-records-cleanup', 'Case-file naming and records cleanup research', 'Use naming rules, examples, sampling, and narrow access to improve records without broad file exposure.', 'Workflow Design', '12 sources support controlled records handling and traceable changes.', 'file naming, folder cleanup, and records metadata', ['legal-case-file-management-access-model', 'offshore-legal-document-prep-review-gates', 'legal-document-retention-workflow']),
  makeResearch('legal-document-retention-workflow', 'Legal document retention workflow research', 'A practical boundary for retention labels, disposition queues, and attorney-approved exceptions.', 'Workflow Design', '12 sources support documented retention decisions and exception handling.', 'retention metadata, review queues, and disposition preparation', ['case-file-naming-and-records-cleanup', 'legal-client-data-access-review', 'contract-administration-workflow']),
  makeResearch('e-discovery-support-chain-of-custody', 'E-discovery support chain-of-custody controls', 'Organize collection administration and evidence logs while reserving legal scope and privilege decisions for counsel.', 'Hiring Controls', '12 sources support preservation, provenance, and review gates.', 'collection inventories, hash records, and review handoffs', ['legal-research-administration-boundaries', 'remote-legal-support-incident-response', 'legal-case-file-management-access-model']),
  makeResearch('immigration-case-administration-controls', 'Immigration case administration controls', 'Scope document checklists, status tracking, and client follow-up while routing legal advice and eligibility questions to counsel.', 'Scope Benchmarks', '12 sources frame a documented intake and escalation boundary.', 'immigration case checklists, status updates, and follow-up', ['legal-intake-support-control-benchmark', 'legal-calendar-deadline-controls', 'law-firm-offshore-support-scorecard']),
  makeResearch('legal-billing-time-entry-controls', 'Legal billing and time-entry control research', 'Separate time capture, narrative cleanup, and invoice preparation from billing judgment and client communication.', 'Workflow Design', '12 sources support a reviewable time-entry workflow.', 'time capture, narrative checks, and invoice preparation', ['contract-administration-workflow', 'law-firm-offshore-support-scorecard', 'legal-client-data-access-review'], '2026-08-08'),
  makeResearch('real-estate-closing-file-checklist', 'Real-estate closing file checklist research', 'A source-backed checklist for organizing closing documents, tracking missing items, and routing exceptions to counsel.', 'Workflow Design', '12 sources support a document-completeness and exception log.', 'closing-file indexing, missing-document follow-up, and handoff notes', ['offshore-legal-document-prep-review-gates', 'case-file-naming-and-records-cleanup', 'legal-document-retention-workflow'], '2026-08-08'),
  makeResearch('corporate-records-calendar-workflow', 'Corporate records calendar workflow research', 'How support staff can maintain entity records and meeting calendars while reserving governance decisions for the client and counsel.', 'Scope Benchmarks', '12 sources frame a records-owner and approval model.', 'entity records, meeting dates, and approved filing reminders', ['legal-calendar-deadline-controls', 'contract-administration-workflow', 'legal-case-file-management-access-model'], '2026-08-08'),
  makeResearch('litigation-discovery-request-tracker', 'Litigation discovery request tracker research', 'Build a controlled tracker for requests, custodians, due dates, and production status without making relevance or privilege calls.', 'Hiring Controls', '12 sources support traceable request ownership and escalation.', 'discovery requests, custodian notes, deadlines, and production status', ['e-discovery-support-chain-of-custody', 'legal-calendar-deadline-controls', 'remote-legal-support-incident-response'], '2026-08-08'),
  makeResearch('legal-intake-conflict-check-workflow', 'Legal intake conflict-check workflow research', 'Design an intake handoff that captures approved identifiers and routes potential conflicts to the firm’s authorized reviewer.', 'Hiring Controls', '12 sources support a narrow intake record and explicit review gate.', 'party identifiers, conflict-check status, and intake escalation', ['legal-intake-support-control-benchmark', 'legal-client-data-access-review', 'immigration-case-administration-controls'], '2026-08-08'),
  makeResearch('legal-translation-handoff-controls', 'Legal translation handoff control research', 'Set boundaries for requesting, tracking, and reviewing translated legal-support materials without changing legal meaning.', 'Scope Benchmarks', '12 sources support source preservation and reviewer sign-off.', 'translation requests, source versions, terminology notes, and review handoffs', ['offshore-legal-document-prep-review-gates', 'legal-research-administration-boundaries', 'law-firm-offshore-support-scorecard'], '2026-08-08'),
  makeResearch('privacy-request-administration-workflow', 'Privacy request administration workflow research', 'Organize intake, identity-check status, search tasks, and deadline tracking while routing legal response decisions to counsel.', 'Workflow Design', '12 sources support a documented request queue and decision owner.', 'privacy requests, identity checks, search coordination, and response routing', ['legal-intake-support-control-benchmark', 'legal-calendar-deadline-controls', 'remote-legal-support-incident-response'], '2026-08-08'),
  makeResearch('legal-knowledge-base-access-model', 'Legal knowledge-base access model research', 'Create a controlled internal knowledge workflow with source ownership, review dates, and permissions that match the material.', 'Hiring Controls', '12 sources support role-based access and source traceability.', 'knowledge articles, source links, review dates, and access groups', ['legal-client-data-access-review', 'legal-research-administration-boundaries', 'corporate-records-calendar-workflow'], '2026-08-08'),
  makeResearch('employment-case-administration-controls', 'Employment case administration controls', 'Scope document collection, status updates, and hearing-date administration while keeping advice and strategy with counsel.', 'Scope Benchmarks', '12 sources support a documented case-status and escalation boundary.', 'employment case files, status fields, dates, and client follow-up', ['legal-case-file-management-access-model', 'legal-calendar-deadline-controls', 'legal-document-retention-workflow'], '2026-08-08'),
  makeResearch('legal-vendor-due-diligence-checklist', 'Legal vendor due-diligence checklist research', 'A practical review queue for vendor records, security evidence, contract status, and owner decisions.', 'Hiring Controls', '12 sources support repeatable vendor evidence collection.', 'vendor questionnaires, evidence links, contract status, and approval notes', ['legal-client-data-access-review', 'remote-legal-support-incident-response', 'contract-administration-workflow'], '2026-08-08'),
  makeResearch('legal-operations-handoff-metrics', 'Legal operations handoff metrics research', 'Measure queue completeness, rework, exception quality, and review latency without turning support metrics into unsupported promises.', 'Scope Benchmarks', '12 sources support evidence-led operational reporting.', 'handoff completeness, rework records, exception quality, and review timing', ['law-firm-offshore-support-scorecard', 'legal-calendar-deadline-controls', 'legal-research-administration-boundaries'], '2026-08-08'),
  makeResearch('legal-mailroom-routing-controls', 'Legal mailroom routing control research', 'Set a documented process for incoming legal correspondence, matter matching, date capture, and escalation of uncertain items.', 'Workflow Design', '12 sources support controlled correspondence intake.', 'mail sorting, matter matching, date capture, and exception routing', ['legal-intake-support-control-benchmark', 'legal-calendar-deadline-controls', 'legal-case-file-management-access-model'], '2026-08-08'),
  makeResearch('legal-audit-request-preparation-controls', 'Legal audit-request preparation controls', 'A source-backed workflow for collecting audit evidence, preserving provenance, and routing judgment calls to a firm owner.', 'Workflow Design', '12 authoritative sources support evidence provenance and review gates.', 'audit request intake, evidence indexing, and reviewer handoff', ['legal-vendor-due-diligence-checklist', 'legal-document-retention-workflow', 'legal-operations-handoff-metrics'], '2026-08-09'),
  makeResearch('law-firm-client-portal-administration-model', 'Law-firm client-portal administration model', 'Define safe support work for portal invitations, document routing, status fields, and access exceptions.', 'Hiring Controls', '12 sources support named access and auditable portal administration.', 'portal invitations, document routing, and access exception notes', ['legal-client-data-access-review', 'legal-intake-support-control-benchmark', 'remote-legal-support-incident-response'], '2026-08-09'),
  makeResearch('legal-subpoena-intake-triage-workflow', 'Legal subpoena intake and triage workflow', 'Organize incoming subpoenas, capture service details, and escalate deadline or jurisdiction questions without making legal determinations.', 'Scope Benchmarks', '12 sources frame date capture, ownership, and escalation controls.', 'subpoena intake, service-detail capture, deadline flags, and handoff', ['legal-mailroom-routing-controls', 'legal-calendar-deadline-controls', 'legal-intake-conflict-check-workflow'], '2026-08-09'),
  makeResearch('law-firm-template-governance-review', 'Law-firm template governance review', 'Create a controlled process for template inventories, version labels, approvals, and retirement of outdated legal-support materials.', 'Workflow Design', '12 sources support version provenance and approval ownership.', 'template inventories, version checks, approval records, and retirement queues', ['legal-knowledge-base-access-model', 'offshore-legal-document-prep-review-gates', 'legal-document-retention-workflow'], '2026-08-09'),
  makeResearch('legal-client-onboarding-document-controls', 'Legal client onboarding document controls', 'A practical document-control model for collecting approved onboarding materials and routing missing or sensitive items.', 'Hiring Controls', '12 sources support minimum-necessary collection and reviewable handoffs.', 'onboarding checklists, document status, identity fields, and exceptions', ['legal-intake-support-control-benchmark', 'legal-client-data-access-review', 'legal-document-retention-workflow'], '2026-08-09'),
  makeResearch('legal-matter-opening-checklist-research', 'Legal matter opening checklist research', 'Standardize matter-opening preparation around approved identifiers, conflict-check status, access requests, and owner sign-off.', 'Scope Benchmarks', '12 sources support a staged matter-opening checklist.', 'matter identifiers, conflict status, access setup, and opening review', ['legal-intake-conflict-check-workflow', 'legal-case-file-management-access-model', 'legal-calendar-deadline-controls'], '2026-08-09'),
  makeResearch('legal-deposition-preparation-administration', 'Deposition preparation administration controls', 'Scope scheduling, exhibit indexing, checklist updates, and logistics while keeping strategy and legal judgment with counsel.', 'Workflow Design', '12 sources support preparation records and explicit counsel review.', 'deposition logistics, exhibit indexes, checklist status, and exceptions', ['litigation-discovery-request-tracker', 'offshore-legal-document-prep-review-gates', 'legal-calendar-deadline-controls'], '2026-08-09'),
  makeResearch('legal-appeal-record-assembly-workflow', 'Legal appeal record assembly workflow', 'Organize approved record materials, citations, and deadlines with provenance controls and a clear attorney review boundary.', 'Hiring Controls', '12 sources support traceable record assembly and review ownership.', 'record indexes, citation capture, deadline tracking, and review handoff', ['legal-research-administration-boundaries', 'legal-document-retention-workflow', 'legal-calendar-deadline-controls'], '2026-08-09'),
  makeResearch('legal-policy-change-tracking-controls', 'Legal policy-change tracking controls', 'Build a source-monitoring and change-log workflow that routes interpretation and implementation decisions to authorized reviewers.', 'Scope Benchmarks', '12 sources support source ownership, review dates, and escalation.', 'source watchlists, change logs, impact flags, and reviewer routing', ['legal-knowledge-base-access-model', 'legal-operations-handoff-metrics', 'legal-research-administration-boundaries'], '2026-08-09'),
  makeResearch('law-firm-offshore-work-queue-design', 'Law-firm offshore work-queue design research', 'Design queues with defined inputs, service levels, review samples, exception states, and a stop rule for uncertain work.', 'Scope Benchmarks', '12 sources support explicit queue ownership and exception handling.', 'queue intake, priority fields, review sampling, and stop-rule escalation', ['law-firm-offshore-support-scorecard', 'legal-operations-handoff-metrics', 'remote-legal-support-incident-response'], '2026-08-09'),
  makeResearch('legal-client-communication-draft-controls', 'Legal client-communication draft controls', 'Set a safe drafting workflow for approved status updates while reserving advice, commitments, and sensitive responses for counsel.', 'Hiring Controls', '12 sources support draft provenance, approval, and communication boundaries.', 'approved status drafts, source notes, reviewer sign-off, and escalation', ['legal-intake-support-control-benchmark', 'offshore-legal-document-prep-review-gates', 'law-firm-offshore-support-scorecard'], '2026-08-09'),
];
export const postsPerPage = 20;
