export type FleetService = { slug: string; title: string; desc: string; tasks: readonly string[]; controls: readonly string[]; firstWeek: readonly string[] };
export type ResearchPost = { slug: string; title: string; excerpt: string; published: string; sections: readonly { heading: string; body: string }[]; sources?: readonly { name: string; url: string }[] };

export const fleetServices: readonly FleetService[] = [
  { slug: 'legal-intake-support', title: 'Legal Intake Support', desc: 'Build a Philippines-based legal intake support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring legal operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'litigation-document-review', title: 'Litigation Document Review', desc: 'Build a Philippines-based litigation document review workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring legal operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'contract-administration', title: 'Contract Administration', desc: 'Build a Philippines-based contract administration workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring legal operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'legal-research-support', title: 'Legal Research Support', desc: 'Build a Philippines-based legal research support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring legal operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'case-file-management', title: 'Case File Management', desc: 'Build a Philippines-based case file management workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring legal operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'e-discovery-support', title: 'E-Discovery Support', desc: 'Build a Philippines-based e-discovery support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring legal operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'immigration-case-administration', title: 'Immigration Case Administration', desc: 'Build a Philippines-based immigration case administration workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring legal operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'real-estate-legal-support', title: 'Real Estate Legal Support', desc: 'Build a Philippines-based real estate legal support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring legal operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'corporate-records-support', title: 'Corporate Records Support', desc: 'Build a Philippines-based corporate records support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring legal operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'billing-and-time-entry-support', title: 'Billing and Time Entry Support', desc: 'Build a Philippines-based billing and time entry support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring legal operations work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] }
];

// Add reviewed, source-backed original research here. The templates and sitemap update automatically.
export const researchPosts: readonly ResearchPost[] = [];
export const postsPerPage = 20;
