import type { ResearchPost } from '../fleet-data';

const sources = [
  { name: 'ABA Formal Opinion 477R', url: 'https://www.americanbar.org/content/dam/aba/administrative/professional_responsibility/formal-opinions/477r.pdf' },
  { name: 'ABA Formal Opinion 498', url: 'https://www.americanbar.org/content/dam/aba/administrative/professional_responsibility/aba-formal-opinion-498.pdf' },
  { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework' },
  { name: 'NIST SP 800-207: Zero Trust Architecture', url: 'https://csrc.nist.gov/pubs/sp/800/207/final' },
  { name: 'NIST SP 800-61 Rev. 2: Incident Handling Guide', url: 'https://csrc.nist.gov/pubs/sp/800/61/r2/final' },
  { name: 'FTC Safeguards Rule', url: 'https://www.ftc.gov/legal-library/browse/rules/safeguards-rule' },
  { name: 'ICO Data Protection by Design and Default', url: 'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/accountability-and-governance/guide-to-accountability-and-governance/data-protection-by-design-and-by-default/' },
  { name: 'ICO Data Sharing Code of Practice', url: 'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/data-sharing/data-sharing-a-code-of-practice/' },
  { name: 'SRA Code of Conduct for Solicitors', url: 'https://www.sra.org.uk/solicitors/standards-regulations/code-conduct-solicitors/' },
  { name: 'Law Society Outsourcing Guidance', url: 'https://www.lawsociety.org.uk/topics/business-management/outsourcing' },
  { name: 'CISA Cloud Security Technical Reference Architecture', url: 'https://www.cisa.gov/resources-tools/resources/cloud-security-technical-reference-architecture' },
  { name: 'OWASP Logging Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html' },
] as const;

type Study = { slug: string; title: string; excerpt: string; question: string; unit: string; finding: string; boundary: string; limitation: string; scenario: string; };

const studies: readonly Study[] = [
  { slug: 'offshore-legal-support-exception-resolution-time-research', title: 'How should law firms measure offshore support exception resolution time?', excerpt: 'A qualitative study separating worker escalation speed from the time an authorized owner takes to resolve an exception.', question: 'Can a law firm measure exception handling without rewarding premature closure or blaming support staff for reviewer delay?', unit: 'one exception from the first observable stop signal through worker routing, owner response, correction, and final disposition', finding: 'The record needs separate timestamps for detection, escalation, acknowledgment, instruction, rework, and disposition. Collapsing them into one duration hides who controlled each interval.', boundary: 'The support worker may identify the supplied stop signal, preserve the source, route a narrow question, and record responses. The worker may not resolve legal ambiguity, change a deadline, select a privileged treatment, or close the exception without authority.', limitation: 'Public governance sources do not supply a universal service level or prove that a shorter interval is safer. Matter urgency, reviewer availability, system behavior, and the nature of the decision change the meaning of elapsed time.', scenario: 'A source document conflicts with a matter field at 09:10 UTC. The worker routes the discrepancy at 09:18, the owner acknowledges it at 10:05, supplies an instruction at 13:20, and the corrected record is reviewed at 14:00. The method reports each interval rather than calling the worker response four hours and fifty minutes.' },
  { slug: 'law-firm-offshore-support-access-removal-evidence-study', title: 'What evidence proves an offshore legal support access removal was completed?', excerpt: 'Research into request, effective permission, session, and verification records when a legal-support assignment ends.', question: 'What evidence should a firm retain when removing an offshore support worker from matter systems?', unit: 'one access-removal event across the approved request, identity provider, application permissions, active sessions, shared links, and verification', finding: 'A closed ticket is evidence of workflow activity, not proof of effective removal. The strongest packet connects the named identity and scope to observed post-change capability and unresolved systems.', boundary: 'A support administrator may inventory approved accounts, record the removal request, execute an authorized mechanical step, and capture the displayed result. The role must not decide retention, investigate outside scope, delete client records, or certify security.', limitation: 'The sources support access governance but cannot show whether a particular application invalidated every token or whether an undiscovered account exists. The study does not perform penetration testing or establish compliance.', scenario: 'An identity-provider account is disabled, but a matter portal still lists the person as an active guest. The packet preserves both observations and routes the portal action instead of treating the central disablement as complete removal.' },
  { slug: 'offshore-legal-support-working-copy-provenance-research', title: 'Can working-copy provenance reduce legal-support version errors?', excerpt: 'A source-linked study of original files, working copies, authorized changes, and reviewer dispositions.', question: 'Can a provenance record make offshore document preparation easier to reconstruct without deciding which version has legal effect?', unit: 'one source file and every approved derivative used during a supervised administrative handoff', finding: 'Useful provenance records source identity, retrieval time, transformation, unchanged original, working-copy identifier, instruction, and reviewer disposition. A filename alone cannot establish approval or currency.', boundary: 'The worker may duplicate an approved source into a controlled workspace, apply mechanical formatting, record changes, and compare identifiers. The worker may not choose controlling language, reconcile substance, certify authenticity, or release the document.', limitation: 'The study uses hypothetical transformations and cannot determine evidentiary authenticity, document-management law, privilege, or whether metadata is complete. A record can preserve lineage while the underlying source remains wrong.', scenario: 'A PDF marked final is converted to an editable file for formatting. The conversion shifts a numbered paragraph. The worker retains the PDF, records the conversion and mismatch, and returns both to the owner rather than silently repairing substantive numbering.' },
  { slug: 'law-firm-offshore-support-review-sampling-design-research', title: 'Designing a defensible review sample for offshore legal support', excerpt: 'A qualitative method for sampling clean items, exceptions, changes, and higher-consequence work without making unsupported performance claims.', question: 'How can a firm sample offshore support work so that common items do not hide rare but important boundary failures?', unit: 'a defined cohort of work items classified by task type, source condition, exception state, reviewer, and period', finding: 'Random clean-item review should be paired with deliberate review of conflicts, changed instructions, new matter types, access events, and judgment-boundary stops. The denominator and selection rule must remain visible.', boundary: 'The support team may prepare the sampling frame and preserve item states. The firm owner chooses consequence categories, interprets findings, changes scope, and decides whether full review remains necessary.', limitation: 'A local sample cannot predict future performance, certify compliance, or compare vendors without matched tasks and conditions. Small cohorts may miss rare events, while targeted exception review cannot estimate an overall error rate.', scenario: 'A weekly queue contains 180 routine entries, 12 corrected entries, six escalations, and two new task variants. Reviewing ten routine items alone misses every changed condition. The proposed frame includes routine items plus all new variants and a defined subset of corrections and escalations.' },
  { slug: 'offshore-legal-support-client-portal-export-evidence-research', title: 'What should an offshore legal support portal export record preserve?', excerpt: 'Research into bounded client-portal exports where selection, transfer, and legal use remain reviewer-owned.', question: 'Can offshore legal support prepare a portal export while preserving enough evidence for a firm to review scope, source, and transfer?', unit: 'one authorized export request, including purpose, matter, filters, visible result count, export event, destination, exception, and reviewer acceptance', finding: 'The export record should distinguish requested scope, displayed filters, files produced, items not accessible, transfer destination, and reviewer acceptance. An export button does not prove completeness.', boundary: 'The worker may apply supplied filters, initiate an authorized export, inventory the resulting files, and report exceptions. The worker may not broaden scope, decide responsiveness, send material to an unapproved destination, or state that the export is complete.', limitation: 'The sources do not establish portal-specific completeness or legal production requirements. Hidden records, pagination, system limits, changed permissions, and asynchronous jobs can affect results outside the worker’s view.', scenario: 'A request names one matter and a date range. The portal displays 142 items but the downloaded archive contains 140 files and two error notices. The worker records all three counts and preserves the notices instead of labeling the export complete.' },
];

const makePost = (s: Study): ResearchPost => ({
  slug: s.slug, title: s.title, excerpt: s.excerpt, published: '2026-08-31', sourceDate: '2026-08-31', cluster: 'Legal Operations Evidence',
  headlineStat: `Research question: ${s.question}`,
  thumbnail: '/research-thumbnails/research-default.svg', relatedSlugs: [], sources,
  sections: [
    { heading: 'Research question and scope', body: `Published August 31, 2026. ${s.question} The unit of analysis is ${s.unit}. This report concerns supervised administrative support for law firms. It does not decide a legal issue, offer legal advice, or claim that an offshore arrangement is inherently safe, compliant, faster, or less expensive. The practical test is whether an authorized firm owner can reconstruct the supplied source, permitted action, uncertainty, and disposition without relying on an undocumented explanation.` },
    { heading: 'Method', body: `The study compares the twelve listed sources on protected information, remote practice, governance, least access, data sharing, outsourcing, incident handling, and logging. These authorities have different jurisdictions and purposes, so they are not treated as one legal standard. Their shared control themes are used to examine a hypothetical workflow. Each observation is separated into source fact, administrative action, exception, and owner decision. The method records negative evidence too, including a system not searched, a field not supplied, an unavailable record, or a decision not yet made. This qualitative design tests reconstructability and role boundaries. It does not calculate a population error rate or infer client outcomes.` },
    { heading: 'Finding', body: `${s.finding} The evidence favors attributable states over a single completion label. Each state should identify the matter or work item, actor, time, source, approved purpose, and next owner. Corrections add a new event instead of erasing the earlier observation. A manager can then distinguish a worker's action from a system delay or an owner decision. This matters in offshore support because time-zone and organizational handoffs can otherwise turn a small ambiguity into an unexplained final record.` },
    { heading: 'Applied scenario', body: `${s.scenario} The scenario shows why a neutral exception is useful. It preserves what the worker actually observed and leaves the next decision open to the authorized reviewer. A second reviewer should be able to reproduce the administrative comparison from the same source set. If that reviewer needs an unwritten assumption, the evidence record is incomplete. If later information resolves the issue, the new source and decision should be linked to the first observation rather than substituted for it.` },
    { heading: 'Role boundary', body: `${s.boundary} Access should follow the stated purpose and use named accounts. The operating guide should identify approved systems, fields, transformations, recipients, and stop conditions. An urgent item still needs a named decision owner. When a request crosses from mechanical preparation into interpretation, advice, approval, or external release, the item moves out of the support lane. Clear boundaries protect the worker from being measured on decisions the role cannot make and help the firm retain responsibility for professional judgment.` },
    { heading: 'Evidence fields', body: `A practical record includes the work-item identity, approved purpose, source location, displayed version or retrieval time, instruction owner, action, unchanged material, exception signal, escalation time, reviewer response, correction, and final disposition. Not every field belongs in every system, and unnecessary client information should not be copied merely to make the record look complete. The firm should select the smallest evidence set that answers who did what, from which source, under whose authority, and with what unresolved limit. Access or event logs can support that account, but a log entry does not prove the legal meaning or correctness of the action.` },
    { heading: 'Sampling and review', body: `Begin with a defined cohort and review every item until the task boundary is stable. Later sampling should include ordinary work and every materially changed condition, such as a new source, permission, matter type, template, reviewer, or exception. Classify observations by wrong source, missing field, unsupported change, stale instruction, missed escalation, access issue, or owner delay. Preserve the denominator, review period, and selection method. Do not publish a success rate from a purposive exception sample or assume that a clean small sample proves future performance.` },
    { heading: 'Limitations', body: `${s.limitation} Guidance pages may also change after the August 31, 2026 source review date. A citation shows where a principle came from; it does not certify a firm's contract, transfer, permission set, supervision, or professional obligations. Hypothetical examples cannot test a live worker, client instruction, or matter system. Firms need their own legal, privacy, security, records, and professional review for the jurisdictions and information involved.` },
    { heading: 'Conclusion', body: `The evidence supports a narrow conclusion. ${s.title.toLowerCase()} can be evaluated as a supervised administrative process when purpose, access, source provenance, stop rules, and firm-side review are explicit. The useful outcome is a record that preserves uncertainty and lets the authorized owner accept, correct, or escalate the handoff. It is not proof of compliance or a transfer of legal responsibility. LegalServicesOffshore.com readers should test one representative lane, inspect exceptions, and expand only when the firm can reconstruct both successful work and unresolved questions.` },
  ],
});

export const august31ResearchPosts: readonly ResearchPost[] = studies.map(makePost);
