import type { ResearchPost } from '../fleet-data';

const sources = [
  { name: 'ABA Formal Opinion 477R', url: 'https://www.americanbar.org/content/dam/aba/administrative/professional_responsibility/formal-opinions/477r.pdf' },
  { name: 'ABA Formal Opinion 498', url: 'https://www.americanbar.org/content/dam/aba/administrative/professional_responsibility/aba-formal-opinion-498.pdf' },
  { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework' },
  { name: 'NIST SP 800-207: Zero Trust Architecture', url: 'https://csrc.nist.gov/pubs/sp/800/207/final' },
  { name: 'ICO Data Protection by Design and Default', url: 'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/accountability-and-governance/guide-to-accountability-and-governance/data-protection-by-design-and-by-default/' },
  { name: 'Law Society Outsourcing Guidance', url: 'https://www.lawsociety.org.uk/topics/business-management/outsourcing' },
  { name: 'OWASP Logging Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html' },
] as const;

type Study = { slug: string; title: string; excerpt: string; question: string; unit: string; finding: string; limit: string; scenario: string };
const studies: readonly Study[] = [
  { slug: 'offshore-legal-support-source-conflict-aging-study', title: 'How should law firms study aging source conflicts in offshore support?', excerpt: 'A qualitative method for separating detection, owner response, source correction, and final disposition.', question: 'Can a firm measure unresolved source conflicts without treating elapsed time as worker performance?', unit: 'one conflicting field across its two sources, detection event, escalation, owner response, correction, and disposition', finding: 'Separate clocks reveal whether delay sits in detection, routing, reviewer availability, new-source retrieval, or approved correction.', limit: 'The source set provides no universal resolution target, and elapsed time cannot establish legal consequence, urgency, or work quality.', scenario: 'A matter address differs between an approved intake form and the practice system. The worker records both values at 08:20, routes the conflict at 08:27, and receives an owner instruction at 12:10. The study preserves those intervals instead of reporting a single four-hour defect.' },
  { slug: 'law-firm-offshore-support-instruction-drift-research', title: 'Detecting instruction drift in offshore legal support routines', excerpt: 'Research into versioned instructions, worker observations, exceptions, and manager recertification.', question: 'What evidence shows that a recurring support routine has drifted from its approved instruction?', unit: 'one task type across the approved instruction version, representative work items, exceptions, corrections, and manager changes', finding: 'Drift becomes visible when work records retain the instruction version and distinguish a worker departure from a stale, ambiguous, or conflicting rule.', limit: 'A documentary comparison cannot prove why behavior changed or whether a different instruction would satisfy every professional obligation.', scenario: 'A checklist still requires a field removed from the source system. Three workers leave it blank and reviewers correct the items differently. The pattern points to an instruction decision, not three identical individual failures.' },
  { slug: 'offshore-legal-support-exception-taxonomy-consistency-research', title: 'Can an exception taxonomy improve legal-support review consistency?', excerpt: 'A bounded study of reason codes, narrative evidence, reviewer agreement, and correction paths.', question: 'Can defined exception categories improve handoffs without forcing legally different events into one label?', unit: 'one escalated item classified independently by two authorized reviewers against a written reason-code guide', finding: 'A small taxonomy improves routing only when the original source, free-text uncertainty, and reviewer disposition remain available beside the code.', limit: 'Agreement on a category does not prove the underlying decision is correct, and a local taxonomy cannot be generalized across firms or matter types.', scenario: 'One reviewer labels an unavailable attachment as missing source while another calls it access blocked. Comparing the source and definitions shows whether the guide needs a sharper boundary.' },
  { slug: 'law-firm-offshore-support-permission-creep-evidence-study', title: 'Studying permission creep in offshore legal support assignments', excerpt: 'Research into task purpose, effective access, use evidence, role changes, and periodic recertification.', question: 'How can a firm detect permissions that remain technically available after the support purpose narrows?', unit: 'one named worker identity mapped across approved tasks, effective application permissions, observed use, changes, and recertification decisions', finding: 'The useful comparison joins purpose to effective capability; a role name or approved ticket alone cannot show what the account can currently reach.', limit: 'Administrative inventories may miss tokens, shared links, local copies, or application behavior and do not constitute penetration testing or a compliance certification.', scenario: 'A worker moves from intake to billing support but retains access to an intake mailbox. The review records the mismatch, owner decision, removal event, and verification without assuming misuse.' },
  { slug: 'offshore-legal-support-handoff-reconstructability-benchmark', title: 'A reconstructability benchmark for offshore legal support handoffs', excerpt: 'A qualitative benchmark testing whether another authorized reviewer can reproduce the source, action, exception, and disposition.', question: 'What minimum evidence lets a second reviewer reconstruct an administrative legal-support handoff?', unit: 'one completed or paused work item with its approved source, instruction, actor event, exception, reviewer decision, and correction history', finding: 'Reconstructability depends on connected evidence states rather than document volume: purpose, source identity, action, uncertainty, authority, and disposition.', limit: 'Reproduction of an administrative trail cannot establish source truth, legal sufficiency, privilege, advice quality, or client outcome.', scenario: 'A second reviewer receives a completed status update without the preparer. If the reviewer can locate the source, see the entered field, understand the exception, and identify approval, the handoff is reconstructable without oral memory.' },
];

const makePost = (s: Study): ResearchPost => ({
  slug: s.slug, title: s.title, excerpt: s.excerpt, published: '2026-09-01', sourceDate: '2026-09-01', cluster: 'Legal Operations Evidence',
  headlineStat: `Research question: ${s.question}`, thumbnail: '/research-thumbnails/research-default.svg', relatedSlugs: [], sources,
  sections: [
    { heading: 'Research question and scope', body: `Published September 1, 2026. ${s.question} The unit of analysis is ${s.unit}. This study concerns supervised administrative support and does not offer legal advice, certify compliance, or claim universal performance.` },
    { heading: 'Method', body: `The study compares the seven listed professional, security, privacy, outsourcing, and logging sources through a qualitative workflow test. Their different jurisdictions and purposes are kept distinct. Observations are separated into source fact, administrative action, exception, owner decision, and later correction.` },
    { heading: 'Finding', body: `${s.finding} The record should identify the matter or work item, actor, time, approved purpose, source, state, and next owner. Corrections add an attributable event instead of erasing the earlier observation.` },
    { heading: 'Applied scenario', body: `${s.scenario} A second authorized reviewer should be able to reproduce the comparison from the same approved source set. If an unwritten assumption is required, the evidence record is incomplete.` },
    { heading: 'Role boundary', body: `The worker may preserve supplied facts, apply approved mechanical steps, and route a narrow question. The firm owner retains interpretation, advice, privilege, legal sufficiency, access approval, external release, and all client-facing decisions. Changed conditions return the item to review.` },
    { heading: 'Evidence design', body: `A proportionate record connects purpose, source location and version, instruction owner, permitted action, unchanged material, exception signal, escalation time, reviewer response, correction, and disposition. It should avoid duplicating sensitive client facts when a controlled source reference is enough.` },
    { heading: 'Sampling approach', body: `Begin with a defined cohort and full review. Later samples should include ordinary work, corrections, exceptions, and every materially changed source, permission, task, template, or reviewer. Preserve the denominator and selection rule, and do not infer a population rate from purposive exception review.` },
    { heading: 'Limitations', body: `${s.limit} Public guidance does not certify a firm's contract, cross-border transfer, supervision, access design, or professional duties. The firm needs jurisdiction-specific legal, security, privacy, records, and client-instruction review.` },
    { heading: 'Conclusion', body: `The evidence supports a narrow conclusion: ${s.title.toLowerCase()} is reviewable when purpose, source provenance, role boundaries, stop rules, and owner dispositions remain visible. The benchmark is a reconstructable local record, not a promise that offshore support is inherently safe, faster, or less expensive.` },
  ],
});

export const september1ResearchPosts: readonly ResearchPost[] = studies.map(makePost);
