import type {ResearchPost} from '../fleet-data';

const sources=[
 {name:'ABA Formal Opinion 477R',url:'https://www.americanbar.org/content/dam/aba/administrative/professional_responsibility/formal-opinions/477r.pdf'},
 {name:'ABA Formal Opinion 498',url:'https://www.americanbar.org/content/dam/aba/administrative/professional_responsibility/aba-formal-opinion-498.pdf'},
 {name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'},
 {name:'NIST SP 800-53 Revision 5',url:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'},
 {name:'CISA Identity and Access Management',url:'https://www.cisa.gov/topics/cyber-threats-and-advisories/identity-and-access-management'},
 {name:'ICO Accountability Framework',url:'https://ico.org.uk/for-organisations/advice-and-services/accountability-framework/'},
 {name:'Law Society Outsourcing Guidance',url:'https://www.lawsociety.org.uk/topics/business-management/outsourcing'},
 {name:'OWASP Logging Cheat Sheet',url:'https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html'},
] as const;

type Study={slug:string;title:string;excerpt:string;question:string;unit:string;method:string;scenario:string;finding:string;limit:string};
const studies:readonly Study[]=[
 {slug:'offshore-legal-support-review-queue-age-banding-study',title:'What queue age bands reveal in offshore legal support review',excerpt:'A bounded method study of prepared work awaiting firm review, separating elapsed time from quality, urgency, and legal risk.',question:'How can age bands describe a supervised review queue without turning elapsed time into a claim about fault or matter risk?',unit:'one prepared work item from entry into attorney review until attributable disposition',method:'Compare twelve hypothetical items across under-one-day, one-to-three-day, four-to-seven-day, and over-seven-day bands. Preserve submission time, reviewer assignment, pause reason, reassignment, and disposition; do not score substantive quality.',scenario:'A four-day item was awaiting a client-supplied source, while a one-day item lacked an assigned reviewer. Their ages are observable, but their causes and significance differ.',finding:'Queue age becomes actionable only when paired with state, owner, pause reason, source availability, and a defined observation time.',limit:'Age bands cannot establish negligence, legal prejudice, urgency, worker quality, reviewer capacity, or the proper priority of a matter.'},
 {slug:'law-firm-offshore-dual-review-disagreement-research',title:'Dual-review disagreement in law firm offshore workflows',excerpt:'Research on preserving independent reviewer outcomes before reconciliation so disagreement can improve instructions instead of disappearing.',question:'What record makes two reviewers’ different outcomes useful for a bounded workflow calibration?',unit:'one administrative work item independently checked by two authorized reviewers under the same named instruction',method:'Construct eight hypothetical paired reviews. Compare instruction version, source set, field-level outcomes, uncertainty labels, reviewer rationale, reconciliation owner, and final disposition.',scenario:'One reviewer marks a party-name difference as an exception; another treats it as approved normalization. The record retains both outcomes before the owner clarifies the instruction.',finding:'Disagreement is interpretable when independent outcomes, shared inputs, rule version, disputed field, and owner resolution remain distinct.',limit:'A disagreement rate cannot identify the correct legal result, prove reviewer competence, predict future consistency, or support comparison across unlike tasks.'},
 {slug:'offshore-legal-support-permission-creep-observation-study',title:'Observing permission creep in offshore legal support assignments',excerpt:'A qualitative comparison of task changes, inherited groups, direct grants, and the evidence needed for scoped access review.',question:'Which observations distinguish a justified task permission from residual or unexplained access?',unit:'one named identity, one system entitlement, one authorized task purpose, and one observation date',method:'Model six access paths: current task grant, inherited group, direct exception, completed-task residue, dormant account, and an entitlement with unavailable ownership evidence. Compare approval, purpose, scope, and removal state.',scenario:'A worker leaves a transaction queue but retains access through a broad team group. The study records the residual path and routes removal to the system owner without opening matter content.',finding:'Permission review is reconstructable when each entitlement is joined to identity, purpose, approval source, access path, observation time, and disposition.',limit:'A point-in-time review cannot prove absence of cached files, alternate identities, active sessions, undiscovered systems, disclosure, or legal compliance.'},
 {slug:'law-firm-offshore-source-date-staleness-study',title:'Source-date staleness in recurring law firm support tasks',excerpt:'Research separating an old document from an outdated instruction and testing when source currency should become an explicit exception.',question:'What evidence helps a reviewer decide whether an older source was intentionally approved or silently carried forward?',unit:'one recurring task, its cited source, source date, assignment instruction, access event, and reviewer outcome',method:'Compare ten hypothetical records using current, superseded, undated, archived, and expressly reapproved sources. Remove the instruction or approval link in alternating cases and document what becomes unknowable.',scenario:'A two-year-old entity list is attached to a current assignment with no statement that it remains approved. The worker records its date and asks for confirmation rather than refreshing it independently.',finding:'Source age has meaning only beside purpose, instruction version, approval evidence, change history, and the date of use.',limit:'The method cannot define a universal expiry period, determine truth, infer intent, establish legal sufficiency, or decide whether a source should be replaced.'},
 {slug:'offshore-legal-support-exception-reopen-patterns-research',title:'Why closed exceptions reopen in offshore legal support records',excerpt:'A bounded study of correction evidence, changed inputs, premature closure, and repeat questions in supervised legal workflows.',question:'Which event fields distinguish a genuinely new exception from a previously unresolved issue that was marked closed?',unit:'one exception from first observation through owner disposition and any later reopening event',method:'Construct seven hypothetical histories: corrected source, changed instruction, new evidence, missing disposition, temporary workaround, duplicate report, and reintroduced old version. Compare event sequence without assigning fault.',scenario:'An owner approves a correction, but the next batch uses the earlier template. The history connects the reopened exception to version selection rather than labeling it a new factual error.',finding:'Reopen patterns become useful when observation, owner decision, correction artifact, effective version, later trigger, and current disposition are preserved as separate events.',limit:'A reopen count cannot prove causation, blame, materiality, legal harm, process maturity, or future performance.'},
];

const make=(s:Study,index:number):ResearchPost=>({slug:s.slug,title:s.title,excerpt:s.excerpt,published:'2026-09-09',sourceDate:'2026-09-09',cluster:'Legal Operations Evidence',headlineStat:`Research question: ${s.question}`,thumbnail:'/research-thumbnails/research-default.svg',relatedSlugs:studies.filter(x=>x.slug!==s.slug).slice(index%3,index%3+2).map(x=>x.slug),sources,sections:[
 {heading:'Research question and scope',body:`Published September 9, 2026. ${s.question} The unit of analysis is ${s.unit}. This is a qualitative examination of administrative evidence in a supervised legal-support workflow. It does not determine privilege, legal duties, strategy, client rights, or matter merits.`},
 {heading:'Methodology',body:`${s.method} The comparison uses the eight listed professional, standards, security, and accountability sources for principles involving supervision, protected information, access, attributable events, and review. Because the sources serve different jurisdictions and purposes, they are not combined into one legal rule. Hypothetical observations, source principles, and local recommendations remain separate.`},
 {heading:'Measurement and evidence fields',body:`For each unit, record its identifier, approved purpose, instruction version, source, actor, event time, observed state, exception, next owner, disposition, and correction link. ${s.finding} Excluded and unavailable records remain visible, and the denominator and observation period accompany any count.`},
 {heading:'Worked scenario',body:`${s.scenario} The support role preserves what approved records show and routes the narrow uncertainty. It does not infer intent, authority, legal meaning, fault, urgency, or the proper substantive outcome.`},
 {heading:'Interpretation and inference limits',body:`The evidence may show whether sampled work used attributable sources, named states, visible unknowns, and documented owner decisions. It may support another bounded review or a clearer instruction. It cannot turn an orderly record into a certification, and alternative explanations such as source quality, task mix, access design, instruction clarity, or reviewer availability must remain visible.`},
 {heading:'Limitations',body:`${s.limit} Public guidance does not certify LegalServicesOffshore.com, an offshore arrangement, or a firm's implementation. No private client files were used. This hypothetical qualitative sample cannot estimate real-world prevalence, effect size, causation, legal compliance, or performance, and it cannot resolve jurisdiction-specific privilege, transfer, retention, consent, notification, or remediation questions.`},
 {heading:'Replication protocol',body:`Before review, define the population, selection rule, state vocabulary, approved sources, reviewer, and period. Include ordinary items and known exceptions. Ask whether a second authorized reviewer can reproduce the observation and identify what remained unknown. Begin a new comparison if the task, system, instruction, permission scope, source type, or reviewer changes.`},
 {heading:'Bounded conclusion',body:`The narrow conclusion is: ${s.finding} A supervised offshore worker can preserve approved inputs, observable actions, uncertainty, and reviewer evidence. The firm retains interpretation, remediation, legal judgment, authority, and release. The useful output is a locally reconstructable record, not a broad claim about compliance, safety, quality, or legal effect.`},
]});

export const september9ResearchPosts=studies.map(make);
