import type {ResearchPost} from '../fleet-data';

const sources=[
 {name:'ABA Formal Opinion 477R',url:'https://www.americanbar.org/content/dam/aba/administrative/professional_responsibility/formal-opinions/477r.pdf'},
 {name:'ABA Formal Opinion 498',url:'https://www.americanbar.org/content/dam/aba/administrative/professional_responsibility/aba-formal-opinion-498.pdf'},
 {name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'},
 {name:'NIST SP 800-53 Revision 5',url:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'},
 {name:'CISA Identity and Access Management',url:'https://www.cisa.gov/topics/cyber-threats-and-advisories/identity-and-access-management'},
 {name:'ICO Data Protection by Design and Default',url:'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/accountability-and-governance/guide-to-accountability-and-governance/data-protection-by-design-and-by-default/'},
 {name:'Law Society Outsourcing Guidance',url:'https://www.lawsociety.org.uk/topics/business-management/outsourcing'},
 {name:'OWASP Logging Cheat Sheet',url:'https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html'},
] as const;

type Study={slug:string;title:string;excerpt:string;question:string;unit:string;method:string;scenario:string;finding:string;limit:string};
const studies:readonly Study[]=[
 {slug:'offshore-legal-support-review-queue-aging-evidence-study',title:'What does review-queue aging actually show in offshore legal support?',excerpt:'A bounded study of prepared work waiting for firm review, with separate clocks for active work and owner decisions.',question:'Can queue timestamps distinguish preparation delay from time spent waiting for an authorized firm decision?',unit:'one work item from approved assignment through preparation, review request, owner response, correction, and acceptance',method:'Compare six hypothetical records across two routine items, two returned items, one missing-source exception, and one unavailable-reviewer event. Preserve every state change and owner.',scenario:'A document index is ready Tuesday, but its assigned lawyer reviews it Friday. The record stops the preparation clock Tuesday and starts a separate review-wait interval.',finding:'Separate state clocks make handoff delay easier to inspect than one end-to-end duration, provided the states and owners are defined before measurement.',limit:'Queue age cannot prove productivity, legal quality, appropriate staffing, causation, or a universal service target.'},
 {slug:'law-firm-offshore-support-source-access-failure-research',title:'Source-access failures in law firm offshore support assignments',excerpt:'Research on missing permissions, unavailable systems, stale links, and the evidence needed to route access problems safely.',question:'Which local records help a firm study source-access failures without encouraging staff to work around controls?',unit:'one attempted access to a firm-approved source, including instruction, account, system response, help request, resolution, and reviewer disposition',method:'Apply the source set to five hypothetical access events: expired permission, stale bookmark, unavailable system, wrong matter folder, and successful restored access. Do not open client content merely to test entitlement.',scenario:'A worker can reach the document platform but not the named matter workspace. The worker records the system response and ticket, then stops instead of asking a colleague to download the files.',finding:'The useful evidence separates identity, requested resource, technical response, business authorization, remediation, and later verification.',limit:'An access log does not establish absence of misuse, security, legal compliance, or the correct permission model for another firm.'},
 {slug:'offshore-legal-support-correction-recurrence-pattern-study',title:'Studying repeated corrections in offshore legal support records',excerpt:'A qualitative look at when the same correction returns because a source, template, instruction, or review rule has not changed.',question:'How can repeated correction records point to a workflow problem without turning them into unsupported worker ratings?',unit:'one defined correction category across original work, reviewer note, revised instruction or template, later sample, and owner decision',method:'Review eight hypothetical events in four pairs. Each pair holds the task constant while varying one factor: source version, template, instruction availability, or reviewer definition.',scenario:'Three returned records omit a source-date field that the current template does not contain. The review retains the returns but routes the missing template field to the process owner.',finding:'Recurrence is interpretable only when the task, population, definition, source, and instruction version remain visible beside the count.',limit:'A small qualitative sample cannot rank staff, establish fault, estimate future error rates, or generalize across task types.'},
 {slug:'law-firm-offshore-support-handoff-context-loss-research',title:'How context gets lost in law firm offshore support handoffs',excerpt:'Research on source links, decision notes, next-owner fields, and the gaps that force a later reviewer to reconstruct work from chat.',question:'What evidence allows a second authorized person to resume a legal support task without relying on the first preparer\'s memory?',unit:'one interrupted work item across source receipt, factual action, open question, reassignment, reviewer decision, and closure',method:'Construct five handoffs with the same administrative task. Remove one field at a time: source identity, instruction version, action note, open question, or next owner. Compare what a second reviewer can reproduce.',scenario:'A preparer leaves midweek after writing "waiting for reply." The handoff has no named recipient or linked message, so the next worker cannot tell what was asked or who owns the answer.',finding:'A short handoff with an attributable source, last action, unresolved question, and named next owner carries more usable context than a long narrative without those fields.',limit:'Hypothetical handoffs do not measure actual service quality, worker judgment, confidentiality, or legal outcomes.'},
 {slug:'offshore-legal-support-approval-state-ambiguity-study',title:'Approval-state ambiguity in offshore legal support workflows',excerpt:'A study of labels such as done, reviewed, approved, and released, and the evidence needed to keep them distinct.',question:'How should a firm test whether workflow status labels correspond to observable decisions and authorized actors?',unit:'one prepared artifact as it moves through completion, review, correction, approval, release, and any later withdrawal',method:'Compare seven hypothetical status histories against written definitions. Ask whether each state has a named actor, event time, evidence link, permitted next action, and reversal path.',scenario:'A tracker says complete after the offshore worker finishes data entry, while the lawyer reads complete as permission to send. The study separates prepared from approved and records who may advance each state.',finding:'Status labels are reliable only when each label has an observable entry condition, authorized actor, allowed next action, and evidence of transition.',limit:'Clear labels do not prove that a substantive decision was correct, that a control operated everywhere, or that release complied with law and client instructions.'},
];

const make=(s:Study,index:number):ResearchPost=>({slug:s.slug,title:s.title,excerpt:s.excerpt,published:'2026-09-07',sourceDate:'2026-09-07',cluster:'Legal Operations Evidence',headlineStat:`Research question: ${s.question}`,thumbnail:'/research-thumbnails/research-default.svg',relatedSlugs:studies.filter(x=>x.slug!==s.slug).slice(index,index+2).map(x=>x.slug),sources,sections:[
 {heading:'Research question and scope',body:`Published September 7, 2026. ${s.question} The unit of analysis is ${s.unit}. This report concerns administrative evidence in a supervised legal-support workflow. It does not decide legal questions, privilege, strategy, client rights, or the merits of any matter. The firm defines the permitted sources and retains legal and client-facing decisions.`},
 {heading:'Method',body:`${s.method} The analysis compares the eight listed sources for guidance on supervision, confidentiality, access, accountable events, and review. Those materials come from different jurisdictions and control settings. They are not treated as one law or as proof that a particular design complies with every firm's duties. Source statements, study observations, and recommendations remain separate.`},
 {heading:'Evidence fields',body:`For each unit, record the work identifier, source identity, instruction version, actor, event time, observed state, exception, next owner, review response, and correction link. ${s.finding} The record should retain inconvenient states rather than rewriting them after a later decision. Items excluded from the sample remain in the denominator note so the result has context.`},
 {heading:'Worked scenario',body:`${s.scenario} The offshore support role records what approved systems show and routes one precise question. It does not infer authority, legal meaning, fault, or the correct substantive result. The named firm owner resolves the question and records the disposition as a new event.`},
 {heading:'Interpretation',body:`The evidence can show whether sampled records used named sources, current instructions, attributable actions, visible exceptions, and owner decisions. It can reveal an administrative pattern worth checking in another bounded sample. It cannot convert a clean log into a certification. Alternative explanations should stay visible, especially when delay or correction could arise from source quality, access, instruction design, or reviewer availability.`},
 {heading:'Scope and limitations',body:`${s.limit} Public guidance does not certify LegalServicesOffshore.com, any staffing model, or a firm's implementation. This documentary and hypothetical method cannot resolve jurisdiction-specific rules, cross-border transfer duties, privilege, retention, client consent, or incident obligations. The sample does not contain private client files and cannot estimate real-world frequency, effect size, or causation.`},
 {heading:'Practical local test',body:`Define the population, state labels, selection rule, and review period before inspecting outcomes. Include normal items and exceptions. Ask whether a second authorized reviewer can locate the same source, reproduce the observation, see what remained unknown, and identify the decision owner. Keep corrections as later events. Start a fresh comparison if the system, task, instruction, or access scope changes.`},
 {heading:'Bounded conclusion',body:`The study supports a narrow conclusion: ${s.finding} Offshore legal support can preserve approved inputs, factual actions, uncertainty, and review evidence. The firm retains interpretation, remediation, authority, and release. The appropriate result is a local record that another authorized person can reconstruct, not a broad claim about quality, safety, or legal compliance.`},
]});

export const september7ResearchPosts=studies.map(make);
