import type { ResearchPost } from '../fleet-data';

const sources = [
  {name:'ABA Formal Opinion 477R',url:'https://www.americanbar.org/content/dam/aba/administrative/professional_responsibility/formal-opinions/477r.pdf'},
  {name:'ABA Formal Opinion 498',url:'https://www.americanbar.org/content/dam/aba/administrative/professional_responsibility/aba-formal-opinion-498.pdf'},
  {name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'},
  {name:'NIST SP 800-207: Zero Trust Architecture',url:'https://csrc.nist.gov/pubs/sp/800/207/final'},
  {name:'ICO Data Protection by Design and Default',url:'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/accountability-and-governance/guide-to-accountability-and-governance/data-protection-by-design-and-by-default/'},
  {name:'Law Society Outsourcing Guidance',url:'https://www.lawsociety.org.uk/topics/business-management/outsourcing'},
  {name:'OWASP Logging Cheat Sheet',url:'https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html'},
] as const;

type Study={slug:string;title:string;excerpt:string;question:string;unit:string;caseNote:string;limit:string;finding:string};
const studies:readonly Study[]=[
 {slug:'offshore-legal-support-exception-reopen-rate-study',title:'What can exception reopen records show about offshore legal support?',excerpt:'A qualitative study of closed exceptions that return because evidence, ownership, or disposition remained incomplete.',question:'Can reopened exceptions reveal weak closure evidence without treating every reopened item as worker error?',unit:'one exception from first observation through routing, disposition, closure, reopening, correction, and final owner acceptance',caseNote:'A source conflict is marked resolved after a reviewer chooses a version, but the disposition does not name that version. A later preparer reopens the item rather than guessing.',limit:'Reopen counts do not establish worker ability, legal quality, causation, or a benchmark across firms.',finding:'Reopen records are most useful when they retain the prior state and classify whether source, instruction, ownership, or disposition was missing.'},
 {slug:'law-firm-offshore-support-access-removal-lag-research',title:'Studying access-removal lag in law firm offshore support',excerpt:'Research on assignment end times, removal requests, effective permissions, verification, and residual-access exceptions.',question:'What local evidence helps a firm study access removal after an offshore support assignment ends?',unit:'one named account and assignment across end instruction, removal request, system change, verification, exception, and owner closure',caseNote:'A matter assignment ends Friday, the ticket closes that afternoon, but a Monday check still shows inherited group access. The observation is routed without opening client files.',limit:'A timestamp comparison cannot prove misuse, security, policy compliance, or an appropriate universal removal target.',finding:'Separate request, technical change, and verification times make residual access visible without assuming that ticket closure changed effective permissions.'},
 {slug:'offshore-legal-support-source-substitution-pattern-study',title:'Source-substitution patterns in offshore legal support handoffs',excerpt:'A bounded study of when preparers encounter missing approved sources and nearby records that appear similar.',question:'How should a firm study attempted source substitution without inviting workers to choose legally controlling records?',unit:'one work item with its named source, missing condition, nearby alternative, action taken, escalation, and reviewer disposition',caseNote:'A signed agreement is absent, while an unsigned copy with the same filename sits nearby. The preparer records the gap and path but does not extract from the substitute.',limit:'Hypothetical and sampled events cannot show intent, legal effect, completeness, or rates outside the reviewed queue.',finding:'A useful taxonomy distinguishes an unavailable source, stale version, unauthorized location, near-match, and reviewer-approved replacement.'},
 {slug:'law-firm-offshore-support-review-sample-selection-study',title:'Review-sample selection for law firm offshore support',excerpt:'Research comparing random, risk-based, exception-led, and first-batch review samples without claiming a universal formula.',question:'What should a firm preserve when choosing work for quality review so the resulting observations remain interpretable?',unit:'one defined work population, its sampling rule, selected items, exclusions, review criteria, observations, and correction record',caseNote:'A manager reviews only escalated items and finds many exceptions. The result describes the exception queue, not the quality of all completed work.',limit:'A local sample cannot prove future performance, compare vendors, establish legal quality, or remove the need for supervision.',finding:'Documented populations and selection rules prevent a convenient sample from being mistaken for a representative performance measure.'},
 {slug:'offshore-legal-support-instruction-version-drift-research',title:'Instruction-version drift in offshore legal support queues',excerpt:'A qualitative investigation of current instructions, cached copies, examples, templates, and reviewer corrections.',question:'Which evidence helps a firm detect when support work follows an older instruction after the approved procedure changes?',unit:'one recurring task across approved instruction version, distribution event, worker access, completed record, review, and correction',caseNote:'A template changes a required source field, yet a bookmarked older copy remains accessible. The worker records which copy was used and the reviewer traces the distribution gap.',limit:'Version evidence does not establish negligence, legal compliance, training quality, or the correctness of the newer instruction.',finding:'Instruction identity should travel with the work item because publication, access, acknowledgment, and actual use are different events.'},
];

const make=(s:Study,index:number):ResearchPost=>({slug:s.slug,title:s.title,excerpt:s.excerpt,published:'2026-09-04',sourceDate:'2026-09-04',cluster:'Legal Operations Evidence',headlineStat:`Research question: ${s.question}`,thumbnail:'/research-thumbnails/research-default.svg',relatedSlugs:studies.filter(x=>x.slug!==s.slug).slice(index%2,index%2+2).map(x=>x.slug),sources,sections:[
 {heading:'Research question and scope',body:`Published September 4, 2026. ${s.question} The unit of analysis is ${s.unit}. This report examines administrative evidence in a supervised legal-support workflow. It does not decide law, strategy, privilege, client rights, or the merits of a matter. The firm supplies the permitted sources and retains every legal and client-facing decision.`},
 {heading:'Method',body:`The study compares the seven listed sources for principles concerning supervision, confidentiality, limited access, accountable events, and review. Those authorities have different scopes and do not create one rule for every firm or jurisdiction. The method applies their common control themes to six hypothetical work items: two ordinary completions, two source or instruction gaps, one access exception, and one reviewer return. Observations, recommendations, and legal conclusions remain separate.`},
 {heading:'Evidence model',body:`The record preserves the work-item identifier, source identity, instruction version, preparer action, exception state, next owner, reviewer response, and correction lineage. ${s.finding} The design favors reconstructable events over a single completion percentage. It also records items outside the sample so the denominator does not disappear when results are summarized.`},
 {heading:'Niche scenario',body:`${s.caseNote} The support role can preserve what the approved systems display, identify the exact difference, and stop at the written boundary. It should not infer authority, legal effect, intent, or the correct substantive answer. The named firm owner reviews the sources and records the next instruction.`},
 {heading:'What the evidence can support',body:`The evidence can show whether the selected items carried their named sources, current instructions, attributable actions, visible exceptions, and owner dispositions. It can also reveal recurring administrative gaps worth testing in another bounded sample. It cannot turn a control design into proof that the control operated across every matter. A clean log supports review; it is not a compliance certificate.`},
 {heading:'Limitations',body:`${s.limit} The public sources do not certify LegalServicesOffshore.com, a vendor, a staffing model, or a firm's implementation. They cannot resolve jurisdiction-specific duties, client terms, cross-border transfer rules, privilege, retention, or incident obligations. Hypothetical cases test record design, not real-world frequency or outcomes. Local counsel, security owners, and firm management must decide the applicable requirements.`},
 {heading:'Practical test',body:`Define the population and selection rule before reviewing results. Use a small batch that includes ordinary items and known exception types. Ask whether a second authorized reviewer can locate the source, reproduce the administrative observation, see what remained unknown, and identify who accepted the disposition. Preserve corrections as new events. If the task, system, client instruction, or access scope changes, begin a new comparison rather than blending unlike cohorts.`},
 {heading:'Bounded conclusion',body:`The research supports a narrow conclusion: ${s.finding} Offshore legal support can contribute by preserving approved sources, factual actions, uncertainty, and review evidence. The firm retains legal interpretation, authority, remediation, and release. The useful result is a local record that another authorized person can reconstruct, not a broad claim about outsourcing quality or safety.`},
]});

export const september4ResearchPosts=studies.map(make);
