import type {ResearchPost} from '../fleet-data';

const sources = [
  {name:'Formal Opinion 08-451: Lawyer\'s Obligations When Outsourcing Legal and Nonlegal Support Services, American Bar Association',url:'https://www.americanbar.org/content/dam/aba/publications/YourABA/201106_08451.authcheckdam.pdf'},
  {name:'Model Rule 5.3: Responsibilities Regarding Nonlawyer Assistance, American Bar Association',url:'https://www.americanbar.org/groups/professional_responsibility/publications/model_rules_of_professional_conduct/rule_5_3_responsibilities_regarding_nonlawyer_assistant/'},
  {name:'Formal Opinion 506: Responsibilities Regarding Nonlawyer Assistants, American Bar Association',url:'https://www.americanbar.org/groups/professional_responsibility/committees_commissions/ethicsandprofessionalresponsibility/'},
  {name:'Cybersecurity Framework 2.0, National Institute of Standards and Technology',url:'https://www.nist.gov/publications/nist-cybersecurity-framework-csf-20'},
  {name:'Privacy Framework, National Institute of Standards and Technology',url:'https://www.nist.gov/privacy-framework'},
  {name:'Identity and Access Management: Recommended Best Practices for Administrators, Cybersecurity and Infrastructure Security Agency',url:'https://www.cisa.gov/sites/default/files/2023-12/ESF%20IDENTITY%20AND%20ACCESS%20MANAGEMENT%20RECOMMENDED%20BEST%20PRACTICES%20FOR%20ADMINISTRATORS%20PP-23-0248_508C.pdf'},
  {name:'Accountability and Governance, UK Information Commissioner\'s Office',url:'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/accountability-and-governance/'},
  {name:'Standards for Internal Control in the Federal Government, U.S. Government Accountability Office',url:'https://www.gao.gov/products/gao-14-704g'},
] as const;

type Study = {
  slug:string; title:string; excerpt:string; cluster:string; question:string; decision:string;
  unit:string; population:string; protocol:string; measures:string; scenario:string;
  finding:string; alternative:string; limitation:string; service:{slug:string;label:string;title:string;body:string};
};

const studies:readonly Study[] = [
  {
    slug:'law-firm-legal-support-task-arrival-coverage-study',
    title:'Task-arrival coverage for an offshore legal support role',
    excerpt:'A bounded staffing study that separates when work arrives, when it is ready, and when an authorized reviewer is available.',
    cluster:'Scope Benchmarks',
    question:'What evidence helps a law firm choose working hours for an offshore support role without confusing message arrival with work that is ready and authorized to begin?',
    decision:'whether the first offshore role needs overlapping firm hours, a later Philippines shift, or an asynchronous handoff based on the timing of genuinely ready tasks',
    unit:'one task-arrival event linked to its source request, readiness state, permitted service window, and named firm-side reviewer',
    population:'forty-two synthetic task events across intake follow-up, matter-file preparation, document formatting, billing cleanup, status reporting, urgent-message routing, incomplete requests, and after-hours submissions',
    protocol:'Assign each event a source timestamp, source time zone, task family, required inputs, authorization state, requested due window, and reviewer. Record when the task first becomes ready, when support can act under the written scope, and when the firm can answer an exception. Compare three coverage designs without treating an inbox timestamp as productive demand.',
    measures:'source timestamp and time zone, task family, requested due window, readiness timestamp, missing input, authorization state, permitted shift, start time, exception time, reviewer availability, administrative completion, and firm acceptance',
    scenario:'A document request enters the shared inbox at 6:10 p.m. firm time, but the approved source file and matter identifier arrive the next morning. Counting the email as evening workload overstates ready demand. The record supports an arrival event followed by a source hold, not work that an offshore operator could safely start.',
    finding:'Coverage decisions become more credible when raw arrivals, ready work, exceptions, and reviewer availability are measured separately. The best shift is the one that supports the defined lane and its review path, not necessarily the one that overlaps every incoming message.',
    alternative:'An apparent after-hours peak may reflect automated notifications, batched forwarding, a temporary matter mix, time-zone conversion errors, or incomplete requests. It does not by itself justify overnight staffing or promise faster client response.',
    limitation:'Synthetic task events cannot forecast a firm\'s volume, staffing requirement, turnaround time, labor cost, employee schedule, client demand, or service result.',
    service:{slug:'admin-support',label:'Plan a first support schedule',title:'Match coverage to ready work and reviewer access',body:'Map one repeatable task lane by source time, readiness, exception path, and firm review window before choosing shift coverage.'},
  },
  {
    slug:'offshore-legal-support-wait-state-research',
    title:'Wait states in offshore legal support: what cycle time can hide',
    excerpt:'Research on separating active preparation from source holds, access holds, attorney review, and client-dependent waiting.',
    cluster:'Workflow Design',
    question:'How can a law firm measure the elapsed time of delegated legal administration without assigning every period of waiting to the support worker?',
    decision:'whether a proposed service level and queue design distinguish controllable preparation time from holds owned by the firm, a system, a client, or an outside source',
    unit:'one work item moving through timestamped active and waiting states under a named instruction version',
    population:'thirty-six synthetic work items spanning ready preparation, missing-source holds, permission failures, reviewer queues, requested client information, changed instructions, returned work, and completed administrative handoffs',
    protocol:'Freeze a state vocabulary before observation. For each item, preserve entry and exit times for ready, active, source hold, access hold, firm decision, external response, review, correction, and accepted states. Require a cited event for each transition and compare elapsed time with active handling time.',
    measures:'work identifier, instruction version, state, state owner, entry event, exit event, elapsed minutes, active minutes, missing dependency, escalation, reviewer response, correction cycle, and accepted disposition',
    scenario:'A support worker prepares an index in forty minutes, then waits two business days for counsel to identify the operative document version. A three-day cycle-time label is arithmetically correct but incomplete. It does not show who controlled the hold or whether the original task packet was ready.',
    finding:'Cycle time is decision-useful only when active work and named wait states remain visible. A single elapsed total can conceal weak intake, access problems, reviewer capacity, or an unsafe instruction just as easily as it can reveal slow preparation.',
    alternative:'Long elapsed time may arise from a deliberate review gate, weekends, different time zones, unavailable sources, system outages, client response, or changed priorities. Short elapsed time may reflect a narrow sample or work released without full review.',
    limitation:'The design cannot set a universal service level, determine reasonable attorney response time, compare providers, establish productivity, or predict client outcomes.',
    service:{slug:'reporting-and-qa',label:'Design a state-aware scorecard',title:'Show active work and holds separately',body:'Define the states, evidence for each transition, owner, and review point before using cycle time to supervise a support lane.'},
  },
  {
    slug:'legal-support-rework-cause-attribution-study',
    title:'Rework in offshore legal support: tracing the cause before scoring quality',
    excerpt:'A decision study that separates preparation defects from changed instructions, missing sources, system behavior, and reviewer preference.',
    cluster:'Legal Reporting and QA',
    question:'What evidence lets a law firm learn from returned work without treating every revision as an operator error?',
    decision:'whether the firm has a fair and reproducible rework taxonomy for supervising a pilot, improving task instructions, and identifying which owner can prevent recurrence',
    unit:'one requested revision linked to the submitted version, applicable instruction, supplied sources, reviewer note, correction, and accepted disposition',
    population:'thirty synthetic returns across transcription errors, omitted checklist steps, ambiguous instructions, later source changes, inaccessible attachments, template defects, reviewer preference, substantive attorney edits, and duplicate review comments',
    protocol:'Preserve the submitted artifact and the sources available at submission. Have the reviewer identify the observable gap and requested next state without selecting a cause. A separate classification step compares the instruction, source packet, access record, submitted work, and later changes before assigning a bounded category or leaving cause unresolved.',
    measures:'work item and version, submission time, instruction version, source set, access state, reviewer request, observed difference, cause category, evidence for category, correction owner, correction version, and final acceptance',
    scenario:'A reviewer returns a draft because the client address changed after submission. The draft differs from the new source, but it matched the approved source available when prepared. Recording an operator defect would erase the timing evidence and direct the correction toward the wrong control.',
    finding:'A return count is not a defect count. Rework becomes actionable when the record distinguishes preparation error, source change, instruction gap, access failure, template problem, reviewer preference, and substantive firm revision.',
    alternative:'More recorded rework can reflect stricter review, better logging, a new work lane, granular version control, or a temporary source problem. Fewer returns can reflect stable work or incomplete review.',
    limitation:'Synthetic returns cannot estimate real error rates, compare individuals, prove legal quality, justify employment action, or show that any category caused a client or matter outcome.',
    service:{slug:'reporting-and-qa',label:'Build a rework taxonomy',title:'Turn returns into process evidence',body:'Preserve the submission, source, instruction, review note, and final disposition so the right owner can address repeat causes.'},
  },
  {
    slug:'attorney-review-capacity-offshore-legal-support-study',
    title:'Attorney review capacity before adding offshore legal support',
    excerpt:'A capacity study for matching delegated preparation with the firm-side review and exception decisions the work still requires.',
    cluster:'Hiring Controls',
    question:'How can a law firm test whether it has enough authorized review capacity for a new offshore support lane before increasing prepared-work volume?',
    decision:'whether to start, narrow, sequence, or postpone a support pilot based on the firm\'s ability to review early work and answer exceptions without bypassing professional gates',
    unit:'one review-eligible work item linked to its preparation state, required reviewer role, review window, disposition, and any returned question',
    population:'thirty-two synthetic work items across four weeks, including ordinary submissions, high-risk exceptions, missing sources, changed priorities, reviewer absences, partial reviews, returned items, and withdrawn work',
    protocol:'Define which items require full review, sampled review, or a firm decision before observation. Assign only reviewers with the required role. Record when an item becomes review-ready, when review starts, whether the required scope is completed, and when an exception receives an authorized answer. Compare staged pilot volumes while preserving unfinished inventory.',
    measures:'work lane, review requirement, risk class, ready time, assigned reviewer role, reviewer availability, review start, review completion, disposition, exception response, returned item, unresolved inventory, and instruction change',
    scenario:'An offshore worker prepares twelve matter updates on Friday, but the only authorized reviewer can inspect four before client communications are due. The preparation count looks productive; the accepted-work count and unresolved inventory show that adding more preparation would deepen the review bottleneck.',
    finding:'Delegated capacity and review capacity are one system. A pilot is not ready to scale merely because support can prepare more items; the firm must also sustain the promised review, exception, and release gates.',
    alternative:'A review backlog may reflect a temporary absence, unusually complex matters, training-period full review, changed priorities, late source delivery, or unclear reviewer assignment. It does not establish a permanent staffing ratio.',
    limitation:'The synthetic model cannot prescribe attorney workload, supervision ratios, legal deadlines, staffing levels, costs, service levels, or the review required for a particular jurisdiction or matter.',
    service:{slug:'reporting-and-qa',label:'Plan the firm-side review gate',title:'Capacity starts with the reviewer',body:'Define the review class, authorized owner, response window, backup, and unresolved-work limit before expanding delegated preparation.'},
  },
  {
    slug:'offshore-legal-support-scope-drift-request-study',
    title:'Scope drift in offshore legal support: study the request, not just the completed task',
    excerpt:'Research on detecting when everyday requests move a support role beyond its approved task, system, source, or decision boundary.',
    cluster:'Hiring Controls',
    question:'What request evidence helps a law firm see scope drift early without asking an offshore worker to interpret professional rules or negotiate authority?',
    decision:'whether a pilot has a usable task boundary and escalation path for plausible requests that fall outside the approved role',
    unit:'one incoming work request compared with the current task definition, approved source, permitted system, communication authority, and reviewer decision',
    population:'thirty synthetic requests spanning approved repeat work, adjacent clerical work, new systems, broader matter access, client messages, substantive edits, rushed exceptions, temporary coverage, ambiguous ownership, and clearly prohibited decisions',
    protocol:'Freeze the role card before testing. Have the operator record the request as received and compare only explicit fields: requester, task type, source, system, recipient, requested output, timing, and named approval. Out-of-scope or uncertain requests enter a stop state. An authorized firm owner then approves, narrows, rejects, or updates the role through version control.',
    measures:'request identifier, requester role, received time, role-card version, task match, source match, system match, access needed, communication recipient, decision requested, urgency claim, stop reason, owner disposition, and effective instruction version',
    scenario:'A worker approved to format attorney-drafted status updates is asked to answer a client\'s new question because counsel is in court. The request is urgent and adjacent to familiar work, but it changes the author, recipient risk, and decision boundary. The safe record is a stopped request and firm escalation, not a helpful improvisation.',
    finding:'Scope is controlled at intake, not after output exists. Recording out-of-scope and ambiguous requests reveals pressure on the role definition and lets the firm decide whether to clarify, expand, or preserve the boundary.',
    alternative:'More stops may reflect careful reporting, a new requester, an outdated role card, temporary coverage needs, or better detection rather than worsening performance. Few stops may mean stable work or unrecorded improvisation.',
    limitation:'Synthetic requests cannot determine unauthorized practice rules, privilege, confidentiality, employment duties, contractual authority, client consent, or the correct disposition for a real request.',
    service:{slug:'admin-support',label:'Define a controlled first role',title:'Give every new request a safe stop path',body:'Write the approved task, source, system, output, recipient, access, and escalation owner before a pilot starts.'},
  },
];

const make = (study:Study,index:number):ResearchPost => ({
  slug:study.slug,title:study.title,excerpt:study.excerpt,published:'2026-09-22',sourceDate:'2026-09-22',cluster:study.cluster,
  headlineStat:`Research question: ${study.question}`,thumbnail:'/research-thumbnails/research-default.svg',
  relatedSlugs:studies.filter(item=>item.slug!==study.slug).slice(index%3,index%3+2).map(item=>item.slug),sources,
  serviceLink:study.service,
  sections:[
    {heading:'Decision this research supports',body:`Published September 22, 2026. This study supports a narrow buyer decision: ${study.decision}. It does not rank providers or propose that an administrative control can replace a lawyer's professional duties. The practical purpose is to help a law firm ask for observable evidence before it delegates repeat work to a Philippines-based support role. Facts in the source record, actions taken by a support worker, decisions made by an authorized firm reviewer, and later outcomes are treated as separate evidence classes throughout the study.`},
    {heading:'Research question and unit of analysis',body:`The research question is: ${study.question} The unit of analysis is ${study.unit}. Defining the unit before measurement prevents a loose collection of messages, files, or dashboard labels from being mistaken for one comparable event. Each unit begins only when the required source and instruction are available. It ends at the bounded administrative disposition described in the protocol, not when a legal matter, client relationship, or commercial outcome reaches a conclusion.`},
    {heading:'Evidence base and source treatment',body:'The source review uses the eight authorities listed below, checked on September 22, 2026. ABA materials inform supervision, confidentiality, prospective-client intake, and the distinction between nonlawyer assistance and lawyer responsibility. NIST, CISA, ICO, and GAO materials inform governance, access, accountability, reliable records, monitoring, and corrective action. These authorities serve different purposes and jurisdictions. The study does not merge them into a single legal rule, claim they bind every firm, or present general control guidance as jurisdiction-specific advice.'},
    {heading:'Population and selection method',body:`The bounded study population is ${study.population}. Cases are synthetic and purposively selected to test ordinary states and foreseeable exceptions, not to estimate how often those events occur in real firms. Every case receives a stable identifier before review. Selection does not depend on whether the result looks favorable. The population definition, included cases, exclusions, and reason for each exclusion are retained so a reader can distinguish the observed set from a broader workload or market.`},
    {heading:'Methodology',body:`${study.protocol} The method records facts as displayed by the approved source and does not ask an operator to infer intent, legal meaning, privilege, urgency, or the correct substantive outcome. The second review tests whether another authorized person can reconstruct the administrative event from preserved evidence. Agreement can reveal that the record and definitions are usable. Disagreement is retained as a finding about definitions, source condition, or review design rather than silently resolved to improve a score.`},
    {heading:'Observation fields and measurement rules',body:`The minimum observation set is: ${study.measures}. Every field has a defined vocabulary, and unavailable information remains unavailable rather than being recoded as “no.” Timestamps use the source system and record the applicable time zone. Corrections append a new state rather than overwriting the original observation. Counts show their numerator, denominator, observation window, exclusions, and missing records. A status label is evidence only of the recorded state in the named system at the observed time; it is not proof that the underlying event was legally effective or factually complete.`},
    {heading:'Worked exception',body:`${study.scenario} This exception illustrates why a support record should preserve narrow observations and an explicit handoff. The operator can record the source, action, displayed result, and unresolved question. The firm decides the legal or professional consequence, any communication outside the approved script, and the next authorized action. A useful workflow makes that stop visible instead of rewarding the operator for converting uncertainty into an apparently complete record.`},
    {heading:'Finding and operational interpretation',body:`${study.finding} This is an inference from the synthetic comparison, not a measured claim about Legal Services Offshore, a customer, or the wider market. For a pilot, managers can translate the finding into written state definitions, a small exception taxonomy, and a named reviewer. They can then inspect early work item by item. If records cannot be reconstructed, the first response should be to check the source, instruction, access, and review design before attributing the problem to a person.`},
    {heading:'Alternative explanations',body:`${study.alternative} Other plausible explanations include changed instructions, reviewer availability, system behavior, permissions, case mix, missing source data, and inconsistent definitions. The research design therefore avoids causal language. A pattern can justify a question, a targeted sample, or a process correction. It cannot establish why the pattern occurred until competing explanations are examined with additional evidence.`},
    {heading:'Supervision, access, and privacy implications',body:'The firm should define the task boundary, approved systems, least-access role, permitted communications, source-of-truth fields, and escalation owner before work starts. Training should use redacted or synthetic examples when practical. Production access should be limited to what the role needs, reviewed when duties change, and removed when the assignment ends. The evidence record should identify sources without copying more confidential content than the firm requires. Lawyers and authorized firm leaders retain supervision, legal judgment, professional communications, client acceptance, substantive approval, and release decisions.'},
    {heading:'Pilot and replication protocol',body:'A replication starts by freezing the work-lane definition, instruction version, field vocabulary, review checklist, observation window, and selection rule. The firm then chooses a small set containing ordinary work and known exceptions. One operator prepares the administrative record; a second authorized reviewer repeats the checks from the preserved sources. Differences are classified by source, instruction, access, preparation, or review. The firm documents any correction and reruns a new sample after a material change. Results from different work lanes or instruction versions are not pooled without showing those differences.'},
    {heading:'Limitations and uncertainty',body:`${study.limitation} No live client information, customer files, production credentials, employees, or law firms were studied. The synthetic sample cannot estimate prevalence, effect size, causation, cost savings, service quality, or business outcomes. Public sources may be revised and local law, court rules, contracts, insurer requirements, professional rules, and firm policies may require a different design. The checked date shows when sources were reviewed, not a guarantee that a page remains current after publication.`},
    {heading:'Niche-specific conclusion',body:`For a law firm evaluating Philippines-based support, the decision-grade conclusion is narrow: ${study.finding} That finding favors a bounded first lane with approved inputs, explicit states, limited access, a visible stop rule, and an accountable firm reviewer. It does not support delegating legal judgment or treating a dashboard as proof of professional compliance. The next useful step is to test the protocol on synthetic or safely redacted examples, revise ambiguous definitions, and approve the live workflow only when the firm can reproduce what happened and who decided the exception.`},
  ],
});

export const september22ResearchPosts = studies.map(make);
