import type {ResearchPost} from '../fleet-data';

type Study={slug:string;title:string;excerpt:string;cluster:string;service:{slug:string;label:string;title:string;body:string};question:string;scope:string;sample:string;method:string;fields:string;exception:string;analysis:string;alternatives:string;limits:string;pilot:string;sources:readonly {name:string;url:string}[]};

const sharedSources=[
  {name:'Formal Opinion 08-451: Lawyer’s Obligations When Outsourcing Legal and Nonlegal Support Services, American Bar Association',url:'https://www.americanbar.org/content/dam/aba/publications/YourABA/201106_08451.authcheckdam.pdf'},
  {name:'Formal Opinion 477R: Securing Communication of Protected Client Information, American Bar Association',url:'https://www.americanbar.org/content/dam/aba/administrative/professional_responsibility/aba_formal_opinion_477.authcheckdam.pdf'},
  {name:'Model Rules of Professional Conduct, American Bar Association',url:'https://www.americanbar.org/groups/professional_responsibility/publications/model_rules_of_professional_conduct/'},
  {name:'Cybersecurity Framework 2.0, National Institute of Standards and Technology',url:'https://csrc.nist.gov/pubs/cswp/29/the-nist-cybersecurity-framework-csf-20/final'},
  {name:'Data Privacy Act of 2012, Philippines National Privacy Commission',url:'https://privacy.gov.ph/data-privacy-act/'},
  {name:'Implementing Rules and Regulations of the Data Privacy Act, Philippines National Privacy Commission',url:'https://privacy.gov.ph/implementing-rules-regulations-data-privacy-act-2012/'},
] as const;

const studies:readonly Study[]=[
  {
    slug:'law-firm-offshore-citation-update-preparation-study',title:'Citation-update preparation in offshore legal research support',excerpt:'A decision study of authority identity, source hierarchy, treatment signals, proposition mapping, and attorney-controlled legal conclusions.',cluster:'Workflow Design',
    service:{slug:'legal-research-support',label:'Plan a citation-update lane',title:'Keep legal treatment analysis with counsel',body:'Define the authority set, source trail, treatment fields, uncertainty, and attorney disposition before support updates a research packet.'},
    question:'Can offshore legal research support refresh a citation packet without deciding whether an authority remains good law or controls a client matter?',
    scope:'The permitted work is bibliographic and evidentiary. A worker may locate an authority named by counsel, preserve the court, date, docket, reporter citation, source URL, retrieval time, and available treatment references, then link those observations to the proposition counsel supplied. The worker does not characterize a case as controlling, distinguish facts, choose a jurisdiction, extend a holding, or state that research is complete. An “updated” packet means that the stated sources were checked under the written search protocol on the recorded date. It does not mean the legal analysis is current for every purpose.',
    sample:'The synthetic population contains thirty authority records: slip opinions later published in reporters, amended opinions, withdrawn dispositions, parallel citations, statutes with later amendments, regulations with correction notices, cited secondary sources, docket entries, similarly named cases, inaccessible commercial links, and an opinion discussed negatively without a simple treatment label. Purposive selection makes difficult source states visible; it cannot estimate how often those states occur in live research. No client question, confidential memorandum, production account, or real legal conclusion appears in the sample.',
    method:'Counsel freezes the jurisdiction, proposition list, seed authorities, approved databases, official-source preference, stopping time, and required output before the exercise. Support searches each seed using the exact citation and party names, records every source consulted, and captures neutral bibliographic changes. A second reviewer attempts to reproduce the search from the log. Counsel alone evaluates precedential weight, negative treatment, factual fit, conflicts among authorities, and whether more research is needed. Missing access remains a recorded gap instead of being replaced with an uncited summary.',
    fields:'authority identifier; proposition identifier supplied by counsel; court and jurisdiction as displayed; decision and publication dates; docket and reporter references; official, commercial, or secondary source class; URL; retrieval date; document version; later-history candidate; citing-reference candidate; quoted passage location; inaccessible source; search string; database coverage note; reviewer; and attorney disposition. Each observation retains its source. Treatment icons and citator phrases are transcribed with provider and timestamp, not converted by support into a legal status.',
    exception:'A database displays a warning symbol beside an appellate opinion, while the linked later case criticizes one proposition but relies on another. The official court copy has also been corrected after initial publication. Support saves the corrected version, logs the version difference, records the later-case citation and the exact provider signal, and routes both to counsel. It does not mark the original authority “overruled,” revise the memorandum, or infer which proposition the warning affects.',
    analysis:'The strongest operational finding is that citation updating should produce a review map, not a verdict. Source hierarchy, version identity, search coverage, and proposition linkage let an attorney see what changed and where judgment is required. A naked green or red flag hides provider coverage and the proposition actually at issue. For a Philippines-based support lane, competence is demonstrated through faithful retrieval, bounded searching, transparent gaps, and prompt escalation. The attorney’s signed disposition is a separate record because legal meaning cannot be delegated to a completion checkbox.',
    alternatives:'More treatment candidates can result from an older authority, a broader database, duplicate reporter records, an expansive citing-reference search, or noisy name matching. Fewer candidates may reflect a narrow time range, inaccessible material, a new decision, incomplete indexing, or a precise citation. Agreement between two services does not establish correctness because their coverage and editorial methods may overlap. Disagreement is useful evidence about coverage, not proof that one source is defective. Reviewers should compare search design and underlying documents before drawing a conclusion.',
    limits:'This qualitative exercise cannot determine binding authority, precedential value, good-law status, statutory currency, jurisdictional fit, exhaustion of research, relevance, accuracy of a citator, or the answer to a legal question. Official publications can be corrected; databases have different coverage; court rules govern citation form; and matter facts alter analysis. The public sources support distinctions between primary and secondary material and professional supervision, but none endorses this workflow or LegalServicesOffshore.com. Counsel must adapt the protocol and independently review the authorities.',
    pilot:'Use ten counsel-selected authorities from one completed, nonconfidential training problem. Define the jurisdiction, databases, date range, and stop rules in advance. Measure exact authority matching, source-version capture, proposition linkage, reproducible queries, missed later-history candidates, unsupported legal labels, and attorney corrections separately. Include an amended opinion, an inaccessible source, a parallel citation, and an ambiguous treatment signal. Review every record. If support supplies legal conclusions or a reviewer cannot reproduce a search, narrow the lane and repeat the affected sample.',
    sources:[...sharedSources,{name:'Legal Research: A Guide to Case Law, Law Library of Congress',url:'https://guides.loc.gov/case-law'},{name:'Legal Research: A Guide to Secondary Resources, Law Library of Congress',url:'https://guides.loc.gov/law-secondary-resources'},{name:'Authentication of Government Publications, GovInfo',url:'https://www.govinfo.gov/about/authentication'}]
  },
  {
    slug:'offshore-litigation-chronology-source-normalization-research',title:'Litigation chronology source normalization for offshore support',excerpt:'Research on date-bearing records, time zones, duplicate events, uncertainty, and counsel-owned relevance and narrative.',cluster:'Scope Benchmarks',
    service:{slug:'litigation-document-review',label:'Design a chronology-preparation pilot',title:'Separate observed events from the case narrative',body:'Map source versions, displayed dates, neutral event fields, conflicts, and attorney review before support prepares a chronology.'},
    question:'How can offshore litigation support normalize date-bearing records without deciding relevance, causation, credibility, or the legal significance of an event?',
    scope:'The proposed lane converts counsel-approved source records into neutral event candidates. Support may record text actually displayed, source location, document version, author or sender as shown, time zone if supplied, and the relationship between an attachment and parent message. It may normalize a date into a separate comparison field only under a written rule while preserving the original string. It may not select decisive events, describe misconduct, reconcile testimony, infer intent, calculate a legal deadline, or write the litigation story.',
    sample:'Thirty-six synthetic records represent email threads, attachments, contracts, invoices, photographs with metadata, meeting notes, declarations, docket notices, exported messages, OCR text, and spreadsheets. The set includes duplicate exports, forwarded messages, an impossible date, two time zones, a daylight-saving transition, an undated attachment, a corrected invoice, and an event mentioned retrospectively. Cases were designed to test stop conditions rather than prevalence. They contain invented names and facts and support no claim about a real dispute or vendor performance.',
    method:'Counsel supplies the bounded collection, issue-neutral event schema, approved timezone convention, duplicate rule, privilege handling instruction, and excluded material. Support hashes source files, preserves parent-child relationships, records displayed values, and creates event candidates without ranking them. Conflicting dates remain separate rows linked by an exception identifier. A second reviewer reconstructs selected entries from the unchanged packet. Counsel decides relevance, evidentiary use, admissibility, privilege, sequencing choices, annotations, and the narrative presented to a client, court, witness, or adversary.',
    fields:'matter training identifier; source hash; file name; document type; source page or field; original date string; supplied time zone; normalized comparison value; normalization rule; event text limited to observable words; actor as displayed; recipient as displayed; parent-child relationship; duplicate group; correction or amendment link; OCR confidence note; conflict code; excluded state; reviewer; and counsel disposition. Unknown day, zone, author, or sequence remains unknown. Later correction appends a state rather than erasing the first observation.',
    exception:'A forwarded email says a meeting occurred “yesterday,” its header is in Pacific time, the export presents UTC, and an attachment has a creation timestamp after the apparent send time. Support records each clock, the relative phrase, export context, and attachment relationship. It does not assign the meeting to a calendar day or accuse a record of being altered. Counsel can seek native data, choose a convention, exclude the item, or accept uncertainty after reviewing the source.',
    analysis:'The research supports normalization only when original evidence and transformed fields remain visibly separate. A single sortable timestamp is convenient but can conceal assumptions about zone, clock source, relative language, or export behavior. The useful output is therefore a layered chronology: immutable source reference, literal observation, mechanical transformation, exception, and professional disposition. In supervised offshore work, a worker should be rewarded for exposing a conflict rather than resolving it silently. The attorney retains control over which events matter and what relationship, if any, they establish.',
    alternatives:'A dense period can reflect duplicate exports, automated notifications, verbose participants, or a narrow collection window rather than substantive activity. A gap can reflect missing discovery, an offline conversation, time-zone conversion, a search limitation, or a genuinely quiet interval. Metadata disagreement may result from copying, scanning, migration, device settings, or processing. It is not by itself evidence of fabrication. Reviewers need the denominator, collection scope, transformation rules, and excluded records before interpreting counts or intervals.',
    limits:'A chronology cannot establish truth, authenticity, completeness, intent, causation, notice, service, timeliness, admissibility, privilege, or legal relevance. The Federal Rules of Civil Procedure provide context for discovery but do not resolve a matter-specific event or local requirement. Synthetic files omit real collection systems, human recollection, and production constraints. Hashes show file identity within the exercise, not authorship or authenticity. Counsel and qualified technical owners must define preservation, collection, interpretation, and any statement made outside the team.',
    pilot:'Select twenty synthetic event candidates spanning one invented week. Freeze the source set and require literal-date capture before normalization. Score source reconstruction, preservation of original strings, time-zone handling, parent-child linkage, duplicate grouping, exception visibility, unauthorized narrative language, and attorney corrections. Include a relative date, a corrected document, and a cross-midnight message. Compare reviewer decisions without forcing agreement. A pilot passes only if every normalized value can be traced and disputed without changing the source evidence.',
    sources:[...sharedSources,{name:'Federal Rules of Civil Procedure, United States Courts',url:'https://www.uscourts.gov/forms-rules/current-rules-practice-procedure/federal-rules-civil-procedure'},{name:'Current Rules of Practice and Procedure, United States Courts',url:'https://www.uscourts.gov/forms-rules/current-rules-practice-procedure'}]
  },
  {
    slug:'law-firm-offshore-immigration-translation-intake-study',title:'Immigration translation intake controls for offshore legal support',excerpt:'A study of source-language documents, translation certifications, identity matching, page completeness, and counsel-controlled filing use.',cluster:'Hiring Controls',
    service:{slug:'immigration-case-administration',label:'Plan a translation-intake lane',title:'Keep evidence sufficiency and filing use with immigration counsel',body:'Define source custody, page comparison, certification fields, identity exceptions, and counsel review before support handles translated evidence.'},
    question:'What translation-intake checks can offshore legal support perform while immigration counsel retains decisions about sufficiency, meaning, credibility, and filing?',
    scope:'Support may inventory a counsel-approved source document and its supplied English translation, compare page counts and visible labels, link certification pages, record translator statements as written, and surface missing or unreadable material. The role does not translate text, certify competence, repair a rendering, decide that a document satisfies an agency requirement, choose evidence, advise a client, calculate a response date, or submit anything. Intake establishes what was received and what appears unmatched under a mechanical checklist, not whether the evidence proves a fact.',
    sample:'The exercise uses twenty-eight synthetic pairs: civil records, education records, letters, identity pages, stamps, tables, seals, handwritten notes, multi-page exhibits, bilingual forms, partial translations, separate certifications, reused file names, and records with different transliterations. Designed exceptions include an omitted reverse side, a blank-looking page containing a seal, inconsistent page order, a certification naming the wrong file, and an English excerpt presented as complete. Artificial records avoid exposure of immigration histories or personal identifiers.',
    method:'Immigration counsel defines the evidence-request identifier, approved upload location, document naming rule, prohibited advice, translation requirement to observe, and reviewer. Support assigns stable pair identifiers, preserves original files, records visible features without interpreting them, and performs only listed comparisons. It never sends an unapproved request to a client or translator. A second reviewer traces a sample from register to files. Counsel evaluates regulatory fit, completeness, credibility, materiality, translation adequacy, identity differences, strategy, and filing use.',
    fields:'training matter; request identifier; source-language file hash; English file hash; source file name; language label as supplied; visible page count; translation page count; page mapping; stamp, seal, signature, table, or handwritten-feature presence; certification file; translator name as displayed; certification statements as displayed; competence statement presence; completion statement presence; identity string difference; unreadable segment; exception; reviewer; and counsel disposition. The register avoids copying narrative content beyond what is needed to identify the mismatch.',
    exception:'A three-page civil record is followed by a one-page certification, but the English file contains two translated pages and no indication whether the reverse side was blank. A surname is transliterated differently across the source label and translation. Support links all files, records the counts and strings, and stops the pair. It does not edit the surname, call the translation complete, or tell the client what to provide. Counsel decides whether clarification or a new translation is required.',
    analysis:'The evidence favors a custody-and-completeness lane rather than a language-judgment lane. Page pairing, certification linkage, feature visibility, and stable source hashes help counsel see exactly what entered the file. They do not show that meaning was carried accurately. Separating intake from translation also prevents a well-intentioned worker from becoming the unrecorded translator. For offshore operations, the clean boundary is observable comparison followed by an attributable legal decision. A visible mismatch is useful work even when it delays a packet.',
    alternatives:'Different page counts may result from formatting, combined pages, a certification appended to one file, blank pages, or a source that places several images on one sheet. Name differences may reflect transliteration conventions, prior records, typographical error, or different people. A missing stamp in the English rendering may be irrelevant or important. None of those possibilities can be resolved from a count alone. A low exception rate may reflect simple documents or weak checking rather than higher translation quality.',
    limits:'This study cannot assess translation accuracy, translator competence, identity, authenticity, evidentiary weight, eligibility, agency acceptance, document availability, response strategy, filing completeness, or legal advice. Immigration rules and form instructions can change, and case-specific notices control. The USCIS material is used only to illustrate a public translation requirement; counsel must identify the applicable authority and current instruction. Synthetic pages do not reproduce all scripts, layouts, cultural naming practices, accessibility needs, or fraud indicators.',
    pilot:'Begin with twelve invented document pairs approved by immigration counsel. Include a table, seal, handwritten notation, page-order problem, separate certification, and name difference. Score file pairing, source preservation, feature capture, certification linkage, unsupported corrections, privacy minimization, escalation time, and counsel changes. Review every pair. Ask a qualified language reviewer only about the separate translation-quality question. If intake staff begin interpreting language or communicating evidence advice, redesign the task before using any client material.',
    sources:[...sharedSources,{name:'8 CFR 103.2, Submission and Adjudication of Benefit Requests, Electronic Code of Federal Regulations',url:'https://www.ecfr.gov/current/title-8/chapter-I/subchapter-B/part-103/section-103.2'},{name:'USCIS Policy Manual, U.S. Citizenship and Immigration Services',url:'https://www.uscis.gov/policy-manual'}]
  },
  {
    slug:'offshore-real-estate-title-exception-packet-research',title:'Title-exception packet preparation in offshore real estate legal support',excerpt:'Research on commitment versions, exception references, source instruments, party strings, open items, and attorney-controlled title analysis.',cluster:'Workflow Design',
    service:{slug:'real-estate-legal-support',label:'Design a title-packet workflow',title:'Keep title interpretation and clearance with counsel',body:'Map commitment versions, exception references, source instruments, missing items, and attorney disposition before support prepares a title packet.'},
    question:'Can offshore real estate support assemble a title-exception review packet without deciding title status, legal effect, clearance, waiver, or closing readiness?',
    scope:'The lane is limited to organizing a counsel-designated title commitment and referenced materials. Support may preserve the commitment version, transcribe exception identifiers, link recorded instruments supplied by an approved source, compare party and property strings, and list documents that are unavailable. It may not interpret an easement, determine priority, declare an exception cleared, order a payoff, communicate a cure, handle funds, approve insurance, waive a condition, or state that a transaction can close.',
    sample:'Thirty synthetic exception records cover easements, covenants, tax references, judgments, releases, assignments, plats, legal descriptions, entity-name variants, recording-number errors, superseded commitments, missing schedules, illegible instruments, and a document that affects several parcels. The artificial packet includes routine and ambiguous states so a buyer can test routing. It is not a title search, abstract, opinion, or statistical sample, and it contains no real property address, borrower data, banking information, or client communication.',
    method:'Real estate counsel freezes the commitment, property identifier, approved repository, source hierarchy, exception schema, prohibited conclusions, and responsible reviewers. Support inventories the schedules, creates one record per listed exception, and links only source instruments found through the approved path. Changes between commitment versions are recorded without explaining their effect. A second reviewer reconstructs selected links and comparisons. Counsel or a qualified title professional determines coverage, priority, enforceability, cure, endorsement, waiver, closing conditions, and communications.',
    fields:'transaction training identifier; commitment issuer; commitment number; effective date and time as displayed; commitment version; schedule and exception number; exception text location; instrument type as labeled; recording reference; instrument date; grantor and grantee strings; property identifier as displayed; legal-description comparison state; source URL or repository path; document hash; missing or illegible state; later commitment action; reviewer; and attorney disposition. Status words are restricted to received, linked, missing, changed, or awaiting review.',
    exception:'Commitment version two removes one exception number but adds a broader reference to the same recording book, while the linked instrument names a predecessor entity and describes two parcels. Support records both commitment versions, the book and page, the party strings, and parcel references. It does not treat the removed number as clearance or decide which parcel is burdened. Counsel can obtain more evidence, ask the title company, revise the checklist, or resolve the issue through the authorized channel.',
    analysis:'A defensible title packet makes version and provenance conspicuous. Exception lists are not stable task lists: numbering, wording, source documents, and property references can change between commitments. The operational value of support lies in giving counsel a navigable map of those changes without converting clerical status into a title conclusion. For a Philippines-based team, the boundary should be encoded in permitted verbs and status values. “Instrument linked” is observable; “exception satisfied” is a professional decision requiring named authority.',
    alternatives:'A high number of exceptions may reflect jurisdiction, transaction type, property history, commitment drafting, or multiple parcels rather than greater defect risk. A missing instrument may result from repository limits, an indexing difference, a recent recording, or an incorrect reference. Removal between versions may reflect title-company review, correction, endorsement, or restructuring, but the change alone does not reveal why. Buyers should not infer quality, complexity, or closing readiness from counts without examining sources and professional dispositions.',
    limits:'The exercise cannot establish ownership, marketability, insurability, priority, encumbrance scope, legal-description accuracy, recording validity, satisfaction, payoff, endorsement availability, closing conditions, or the legal effect of any instrument. Title practices vary by state and transaction. CFPB materials describe certain mortgage and title documents but do not resolve a particular property issue. Synthetic packets omit local records, survey evidence, fraud risks, funding, and title-company procedures. Licensed professionals must adapt and own the review.',
    pilot:'Use one fictional transaction with fifteen exceptions and two commitment versions. Include a missing instrument, entity-name variance, parcel mismatch, illegible page, and renumbered exception. Measure version capture, exception-to-source linkage, exact-string preservation, property-reference comparisons, unsupported clearance labels, reviewer reconstruction, and counsel corrections. Keep funds, credentials, communications, and production systems outside the pilot. If any record can be marked cleared without attributable professional approval, the workflow needs a stronger state model.',
    sources:[...sharedSources,{name:'TILA-RESPA Integrated Disclosures, Consumer Financial Protection Bureau',url:'https://www.consumerfinance.gov/compliance/compliance-resources/mortgage-resources/tila-respa-integrated-disclosures/'},{name:'Comment for Appendix O: Title Commitment Report, Consumer Financial Protection Bureau',url:'https://www.consumerfinance.gov/rules-policy/regulations/1026/interp-o/'}]
  },
  {
    slug:'law-firm-offshore-billing-guideline-exception-preflight-study',title:'Billing-guideline exception preflight for offshore legal support',excerpt:'A study of client-rule versions, time-entry fields, code candidates, documentary flags, and firm-controlled billing judgment and release.',cluster:'Hiring Controls',
    service:{slug:'billing-and-time-entry-support',label:'Plan a billing preflight lane',title:'Keep billing judgment and invoice release with the firm',body:'Define guideline sources, mechanical checks, neutral exceptions, reviewer authority, and release controls before support reviews draft entries.'},
    question:'Which billing-guideline checks can offshore support perform without deciding reasonableness, privilege, staffing value, code meaning, appeal strategy, or what the firm should charge?',
    scope:'Support may run written mechanical checks against a client-specific guideline version supplied by the firm. Examples include required fields, date format, timekeeper identifier, duplicate-entry candidates, narrative length limits, prohibited-character rules, and whether an attachment listed in the instruction is present. Support can suggest a code candidate only when the firm supplies an exact deterministic map and labels the result for review. It cannot rewrite substance, determine reasonableness, disclose privileged detail, reduce time, approve a charge, appeal a rejection, or release an invoice.',
    sample:'The synthetic cohort contains forty draft entries from invented matters and timekeepers. It includes missing task codes, split entries, similar narratives on different dates, travel descriptions, block-billing candidates, zero-value lines, sensitive narrative text, alternative fee arrangements, corrected entries, tax fields, and guideline changes mid-cycle. The sample deliberately combines clear format defects with ambiguous billing questions. It does not estimate rejection rates, savings, timekeeper conduct, client preferences, or the correctness of any fee.',
    method:'The billing owner identifies the client, matter, controlling guideline version, effective date, approved code table, deterministic tests, sensitive-text rule, and reviewers. Support tests an export copy and records exceptions without changing the timekeeping source. Every proposed edit retains the original entry and rule reference. Ambiguity routes to the responsible billing lawyer or administrator. Separate authorized users approve narrative substance, rate or amount decisions, write-downs, invoice release, and client responses. A reviewer repeats a sample from the same frozen export.',
    fields:'client and matter training identifiers; guideline title and version; effective date; draft invoice version; entry identifier; work date; timekeeper identifier; hours as supplied; task and activity codes as supplied; narrative source; mechanical rule identifier; observed exception; deterministic code candidate; sensitive-text flag; proposed clerical correction; original value; reviewer decision; approved value; release owner; and submission result. The register should avoid copying more narrative text than the exception requires.',
    exception:'A draft entry uses a valid code but describes two activities, one of which may be excluded under the client guideline. Another entry has nearly identical wording because the same recurring report was prepared on consecutive days. Support records the exact rule references and similarity observation, leaving both originals unchanged. It does not split time, accuse the timekeeper of duplication, decide the work’s value, or edit the description. The billing lawyer determines the accurate narrative and charge.',
    analysis:'The evidence supports preflight as a reversible exception process. Client guidelines are contextual instructions, not universal billing rules, and the same wording can have different significance across matters. Reliable support therefore anchors each flag to a specific version and separates deterministic validation from professional billing judgment. A lower exception count is not automatically better; silent edits can produce a clean file with weak evidence. The firm should be able to trace original entry, rule, proposed clerical action, reviewer decision, and released invoice state.',
    alternatives:'Repeated narratives may describe duplicate work, a recurring task, template use, or incomplete description. A code mismatch may arise from an updated client table, system default, matter-specific instruction, or human error. Rejections can reflect format, budget, rate, staffing, narrative, timing, taxes, or client policy. Acceptance by an e-billing platform proves technical receipt, not that a charge is reasonable or finally approved. Any trend needs a stable denominator, guideline version, matter mix, and reviewer practice.',
    limits:'This study cannot determine fee reasonableness, compliance with an engagement, privilege, narrative adequacy, code correctness, staffing appropriateness, collectability, tax treatment, client acceptance, appeal merit, or accounting treatment. ABA professional rules, contracts, jurisdictional law, and client instructions may impose different duties. UTBMS provides exchange-oriented code standards but directs implementation questions to the requesting client or vendor. Synthetic entries omit real arrangements and must never be used to infer firm or worker performance.',
    pilot:'Choose twenty-five invented entries governed by one frozen guideline. Predefine ten mechanical checks and three mandatory escalation categories. Measure correct rule linkage, original-value preservation, false duplicate flags, unauthorized substantive edits, sensitive-text handling, reviewer turnaround, and differences between preflight and release decisions. Include a guideline effective-date change and a technically valid but judgment-dependent entry. Review all records. Do not connect the pilot to accounting, e-billing, client portals, or production credentials.',
    sources:[...sharedSources,{name:'Model Rule 1.5: Fees, American Bar Association',url:'https://www.americanbar.org/groups/professional_responsibility/publications/model_rules_of_professional_conduct/rule_1_5_fees/'},{name:'Uniform Task-Based Management System, LEDES Oversight Committee',url:'https://utbms.com/'},{name:'Contact UTBMS: Implementation Questions, LEDES Oversight Committee',url:'https://utbms.com/contact-utbms/'}]
  }
];

const make=(study:Study,index:number):ResearchPost=>({
  slug:study.slug,title:study.title,excerpt:study.excerpt,published:'2026-09-28',sourceDate:'2026-09-28',cluster:study.cluster,
  headlineStat:`Research question: ${study.question}`,thumbnail:'/research-thumbnails/research-default.svg',sources:study.sources,serviceLink:study.service,
  relatedSlugs:studies.filter(item=>item.slug!==study.slug).slice(index%3,index%3+2).map(item=>item.slug),
  sections:[
    {heading:'Decision and research question',body:`Published September 28, 2026. ${study.question} This report helps a law-firm owner, attorney, or operations lead decide whether a narrow Philippines-based support lane is reviewable before any client work enters it. The report distinguishes observed facts, mechanical support actions, professional analysis, and unresolved uncertainty. It does not rank providers, promise performance, or offer legal advice. The decision is whether the proposed evidence record and stop rules allow the firm to retain meaningful supervision.`},
    {heading:'Permitted scope and decision rights',body:study.scope},
    {heading:'Evidence base and source review',body:`The primary and authoritative sources listed below were checked on September 28, 2026. ABA materials frame outsourcing, supervision, confidentiality, protected communications, and professional responsibility. NIST provides a general risk-governance reference. Philippine National Privacy Commission materials supply local privacy and accountability context. Topic-specific public sources inform the workflow described here. They arise from different institutions and jurisdictions, so the analysis does not combine them into a universal rule. No source endorses LegalServicesOffshore.com, this method, or an operational outcome.`},
    {heading:'Population and selection',body:study.sample},
    {heading:'Methodology and responsibility split',body:study.method},
    {heading:'Observation model',body:study.fields},
    {heading:'Worked exception',body:study.exception},
    {heading:'Finding and operational interpretation',body:study.analysis},
    {heading:'Alternative explanations',body:study.alternatives},
    {heading:'Limitations and uncertainty',body:study.limits},
    {heading:'Buyer pilot',body:study.pilot},
    {heading:'Governance for offshore delivery',body:`Access should use named accounts, least privilege, an approved repository, and a defined end date. The firm should document who can change the instruction, accept an exception, authorize communication, and close a record. Support must not work around missing access with personal accounts, copied credentials, consumer tools, or unapproved downloads. Supervisors should review source-to-record fidelity and boundary compliance, not only throughput. A safe stop is a valid result. If the instruction, source, owner, or permitted action is unclear, the record should remain open and attributable.`},
    {heading:'Niche-specific conclusion',body:`For LegalServicesOffshore.com, this study supports a supervised administrative service rather than a substitute for counsel or another licensed professional. The most useful buying evidence is a reconstructable handoff: an approved source, a permitted action, an explicit non-action, a visible exception, a named decision owner, and a recorded disposition. Buyers should test those elements with realistic edge cases before increasing volume. A polished deliverable without its source trail is weaker than an incomplete record that truthfully preserves uncertainty and professional decision rights.`},
    {heading:'Future review',body:`Recheck the linked sources and the firm’s own professional, contractual, privacy, security, and client requirements before implementation. Record access dates, versions, jurisdictional fit, and any unavailable material. Revisit the workflow after a source or system change, a new data class, a material exception, a changed reviewer, or a client instruction update. If the public analysis later changes, retain September 28, 2026 as the original publication date and use dateModified only for the truthful revision date.`}
  ]
});

export const september28ResearchPosts=studies.map(make);
