import type { ResearchPost } from '../fleet-data';

const sources = [
  { name: 'ABA Formal Opinion 477R', url: 'https://www.americanbar.org/content/dam/aba/administrative/professional_responsibility/formal-opinions/477r.pdf' },
  { name: 'ABA Formal Opinion 498', url: 'https://www.americanbar.org/content/dam/aba/administrative/professional_responsibility/aba-formal-opinion-498.pdf' },
  { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework' },
  { name: 'NIST SP 800-207: Zero Trust Architecture', url: 'https://csrc.nist.gov/pubs/sp/800/207/final' },
  { name: 'ICO Data Protection by Design and Default', url: 'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/accountability-and-governance/guide-to-accountability-and-governance/data-protection-by-design-and-by-default/' },
  { name: 'Law Society Outsourcing Guidance', url: 'https://www.lawsociety.org.uk/topics/business-management/outsourcing' },
  { name: 'OWASP Logging Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html' },
] as const;

type Study = { slug: string; title: string; excerpt: string; question: string; unit: string; finding: string; limit: string; scenario: string; test: string };
const studies: readonly Study[] = [
  { slug: 'offshore-legal-support-review-return-reason-study', title: 'What do review-return reasons reveal about offshore legal support?', excerpt: 'A bounded method for separating source, instruction, access, preparation, and judgment-boundary returns.', question: 'Can return reasons show where a support routine needs correction without reducing quality to one rejection rate?', unit: 'one returned work item with its source, instruction version, preparer state, reviewer reason, correction, and disposition', finding: 'Defined reasons make process defects distinguishable when the reviewer also preserves a factual note and the source that supports the return.', limit: 'A return count cannot establish worker capability, legal quality, causation, or a benchmark for other firms.', scenario: 'A reviewer returns an intake record because a required identifier is absent from the approved source. Coding this as source incomplete, rather than preparer error, points the correction to the intake owner.', test: 'Compare independent reviewer classifications for the same 20-item cohort and discuss every disagreement before changing the taxonomy.' },
  { slug: 'law-firm-offshore-support-queue-interruption-research', title: 'Studying queue interruptions in law firm offshore support', excerpt: 'Research into interruption source, restart evidence, priority authority, and unfinished-work risk.', question: 'What evidence helps a firm study interruptions without assuming that every pause is wasted time?', unit: 'one task from initial assignment through interruption, preserved state, authorized reprioritization, restart, review, and closure', finding: 'Interruption records are useful when they distinguish owner-directed reprioritization, missing input, access failure, clarification, and true abandonment.', limit: 'Elapsed time and interruption counts do not prove productivity, urgency, or the legal importance of either task.', scenario: 'A document-index task pauses when the matter owner assigns an urgent filing check. The record preserves the last completed source and restart point, preventing a duplicate or skipped entry.', test: 'Sample interrupted items and ask whether a second authorized worker can resume them without private memory or an unrecorded assumption.' },
  { slug: 'offshore-legal-support-correction-lineage-evidence-study', title: 'Correction-lineage evidence in offshore legal support records', excerpt: 'A qualitative study of original values, authorized corrections, reasons, reviewers, and downstream updates.', question: 'How should a support record preserve corrections so its history remains understandable and proportionate?', unit: 'one corrected field across original source, entered value, detection, correction authority, new value, and affected downstream record', finding: 'An appended correction event provides stronger reconstruction evidence than overwriting the earlier value without attribution.', limit: 'A complete correction trail cannot prove the source was true, the legal conclusion was sound, or every downstream copy was found.', scenario: 'An approved party name is corrected after the client supplies a revised intake. The record keeps both source versions, the authorized correction, its reason, and the systems confirmed updated.', test: 'Select corrected items across three task types and trace whether the authority and every named downstream update can be located.' },
  { slug: 'law-firm-offshore-support-reviewer-availability-study', title: 'Reviewer availability and offshore legal-support handoffs', excerpt: 'Research separating preparation time, review waiting, clarification, correction, and final owner disposition.', question: 'Can firms identify review bottlenecks without treating all waiting time as support-team delay?', unit: 'one prepared handoff with readiness time, reviewer assignment, first response, clarification, correction, and acceptance', finding: 'Separate timestamps show where the item waited and whether the next action belonged to the preparer, reviewer, source owner, or access administrator.', limit: 'Queue timestamps alone cannot establish appropriate staffing, negligence, service quality, or a universal response target.', scenario: 'A packet is ready at 15:00, enters attorney review at 15:05, receives a source question the next morning, and is accepted after the source owner responds. One cycle-time number hides those owners.', test: 'Map a defined weekly cohort by state and owner, then review aged items individually before drawing a capacity conclusion.' },
  { slug: 'offshore-legal-support-template-change-impact-research', title: 'Measuring template-change impact in offshore legal support', excerpt: 'A before-and-after evidence design for instruction versions, affected fields, exceptions, and reviewer corrections.', question: 'What local evidence can show whether an approved template change improved a recurring support handoff?', unit: 'one task type across defined pre-change and post-change cohorts with template version, source conditions, exceptions, corrections, and disposition', finding: 'Comparable cohorts can expose changed error categories when the task, source, reviewer criteria, and selection method remain visible.', limit: 'A before-and-after comparison cannot isolate the template from training, workload, matter mix, reviewer behavior, or system changes.', scenario: 'A revised closing checklist adds a source-version field. Post-change records show fewer wrong-version returns, but the firm also changed reviewers, so the result remains a local observation rather than causal proof.', test: 'Define both cohorts before review, preserve denominators and exception mix, and record every concurrent operational change.' },
];

const makePost = (s: Study, index: number): ResearchPost => ({
  slug: s.slug, title: s.title, excerpt: s.excerpt, published: '2026-09-02', sourceDate: '2026-09-02', cluster: 'Legal Operations Evidence',
  headlineStat: `Research question: ${s.question}`, thumbnail: '/research-thumbnails/research-default.svg', relatedSlugs: [], sources,
  sections: [
    { heading: 'Research question and scope', body: `Published September 2, 2026. ${s.question} The unit of analysis is ${s.unit}. Study ${index + 1} addresses supervised administrative support, not legal advice, compliance certification, or a universal performance claim.` },
    { heading: 'Method', body: `This qualitative study compares the seven listed professional, security, privacy, outsourcing, and logging sources through a bounded workflow test. Source facts, local design choices, administrative actions, exceptions, owner decisions, and corrections are recorded separately.` },
    { heading: 'Finding', body: `${s.finding} The record should connect approved purpose, actor, time, source, instruction version, state, reason, next owner, and disposition. An attributable later event should correct a record rather than erase its history.` },
    { heading: 'Applied scenario', body: `${s.scenario} The example is a process illustration, not empirical proof. A second authorized reviewer should be able to reproduce the observation from the same approved evidence without relying on private chat.` },
    { heading: 'Proposed local test', body: `${s.test} Preserve the selection rule, observation period, denominator, exclusions, and reviewer definitions. Report category counts and disagreements instead of collapsing different failure modes into a single score.` },
    { heading: 'Role and decision boundary', body: `Support workers may record supplied facts, perform approved mechanical comparisons, and route uncertainty. Firm owners retain legal interpretation, advice, privilege, sufficiency, access approval, external release, and client-facing decisions. Changed conditions return the item to review.` },
    { heading: 'Evidence design', body: `A proportionate evidence record links purpose, source location and version, instruction owner, permitted action, unchanged material, exception, escalation time, reviewer response, correction, and closure. Controlled references are preferable to unnecessary copies of confidential facts.` },
    { heading: 'Limitations', body: `${s.limit} Public guidance does not certify a firm's implementation, cross-border transfer, contract, supervision, security, or professional duties. Jurisdiction-specific legal, privacy, records, security, and client-instruction review may be necessary.` },
    { heading: 'Conclusion', body: `The narrow conclusion is that ${s.title.toLowerCase()} becomes reviewable when the firm preserves source provenance, state changes, role boundaries, stop rules, and owner dispositions. Local evidence can guide a routine, but it should not be presented as proof that offshore support is inherently safe, faster, or less costly.` },
  ],
});

export const september2ResearchPosts: readonly ResearchPost[] = studies.map(makePost);
