import type {ResearchPost} from '../fleet-data';

const sources=[
 {name:'ABA Formal Opinion 477R',url:'https://www.americanbar.org/content/dam/aba/administrative/professional_responsibility/formal-opinions/477r.pdf'},
 {name:'ABA Formal Opinion 498',url:'https://www.americanbar.org/content/dam/aba/administrative/professional_responsibility/aba-formal-opinion-498.pdf'},
 {name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'},
 {name:'NIST SP 800-53 Revision 5',url:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'},
 {name:'NIST SP 800-207 Zero Trust Architecture',url:'https://csrc.nist.gov/pubs/sp/800/207/final'},
 {name:'CISA Identity and Access Management',url:'https://www.cisa.gov/topics/cyber-threats-and-advisories/identity-and-access-management'},
 {name:'ICO Accountability Framework',url:'https://ico.org.uk/for-organisations/advice-and-services/accountability-framework/'},
 {name:'Law Society Outsourcing Guidance',url:'https://www.lawsociety.org.uk/topics/business-management/outsourcing'},
 {name:'OWASP Logging Cheat Sheet',url:'https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html'},
] as const;

type Study={slug:string;title:string;excerpt:string;question:string;unit:string;method:string;scenario:string;finding:string;limits:string};
const studies:readonly Study[]=[
 {slug:'offshore-legal-support-source-to-field-reproducibility-study',title:'Can reviewers reproduce source-to-field checks in offshore legal support?',excerpt:'A bounded comparison of source links, field observations, instructions, and independent reviewer outcomes.',question:'Which evidence lets a second reviewer reproduce an administrative source-to-field check without relying on the first reviewer\'s conclusion?',unit:'one field, its approved source, the instruction used, the observed value, and an independent recheck',method:'Construct ten hypothetical field checks across names, dates, identifiers, status labels, and version references. Give a second reviewer the full evidence for five checks and omit one evidence element from each remaining check. Compare whether the observation can be repeated, not whether it is legally correct.',scenario:'A first reviewer records a party name from an attachment. The second reviewer receives the email but not the attachment version, so the apparent match cannot be reproduced.',finding:'Reproducibility depends on a stable source reference, source version, instruction, observation time, field rule, and preserved exception.',limits:'The comparison cannot establish legal accuracy, reviewer competence, source authenticity, prevalence, causation, or performance in a live firm.'},
 {slug:'law-firm-offshore-reviewer-handoff-continuity-study',title:'Testing reviewer handoff continuity in law firm offshore queues',excerpt:'A bounded study of what survives when an open administrative queue passes to a new firm-side reviewer.',question:'Can a successor reviewer reconstruct an open queue item when the handoff separates completed preparation, unresolved questions, and the next authorized action?',unit:'one open queue item at the moment responsibility passes between two named firm reviewers',method:'Model eight hypothetical handoffs. Vary the presence of source snapshots, preparation history, unresolved questions, next-action limits, acceptance time, and superseded instructions. Test whether a successor can identify what happened and what remains undecided without contacting the prior reviewer.',scenario:'A successor receives a packet marked prepared. The handoff also shows that an amendment is missing and release was never approved, so the successor can distinguish administrative completion from the unresolved firm decision.',finding:'A reviewer handoff remains reconstructable when it preserves the prepared state, source snapshot, unresolved question, superseded instruction, receiving owner, and accepted next-action boundary.',limits:'The cases cannot prove reviewer authority, competence, workload, legal sufficiency, delay, matter risk, or the correct disposition in a real firm.'},
 {slug:'offshore-legal-support-evidence-link-decay-observation',title:'Observing evidence-link decay in offshore legal support records',excerpt:'A qualitative study of moved files, changed permissions, expired links, and the boundary between access failure and missing evidence.',question:'How should a support record distinguish a source that no longer opens from evidence that never existed?',unit:'one recorded evidence link checked at two defined observation times',method:'Create twelve hypothetical links across moved files, renamed folders, revoked access, expired shares, deleted drafts, and unavailable system records. Preserve original path, identifier, permission context, error as displayed, check time, and owner response.',scenario:'A source identifier remains in the register, but the folder path now returns access denied after a matter-team change. The observation proves failed access at that time, not deletion.',finding:'Link decay is interpretable only when identity, original location, access context, displayed result, observation time, and owner disposition remain separate.',limits:'A failed link cannot prove deletion, spoliation, disclosure, improper access, source truth, or the complete history of a repository.'},
 {slug:'law-firm-offshore-instruction-exception-density-study',title:'Instruction exception density in law firm offshore support tasks',excerpt:'A method study that counts rule-triggered exceptions without treating the count as a quality score or legal-risk measure.',question:'What can an exception count say about a written task instruction when task mix and source condition remain visible?',unit:'one item checked against one named instruction version during a fixed review period',method:'Build a hypothetical cohort of twenty items divided between two instruction versions and four source conditions. Count the first triggered exception by category, preserve multiple observations separately, and compare rates only within like task and source groups.',scenario:'One instruction version treats a missing version label as a stop, while the other does not mention it. The count shows a rule difference rather than worker error.',finding:'Exception density can identify questions for instruction review when the denominator, task mix, source condition, rule version, and classification method are reported.',limits:'The rate cannot measure legal risk, accuracy, worker quality, efficiency, causation, compliance, or performance outside the defined cohort.'},
 {slug:'offshore-legal-support-temporary-access-expiry-research',title:'Temporary access expiry evidence in offshore legal support',excerpt:'A bounded study of approval windows, observed permissions, removal records, and what a point-in-time check cannot prove.',question:'Which events show that temporary task access followed its approved lifecycle without claiming that no residual access exists?',unit:'one named identity, one resource permission, one approved purpose, and one access window',method:'Construct six hypothetical access lifecycles covering on-time removal, late removal, group inheritance, reapproval, unavailable logs, and an active session after permission change. Compare approval, grant, use as observed, expiry, removal, verification, and exception events.',scenario:'A direct permission is removed at expiry, but a later review finds the identity in a broader inherited group. The lifecycle records both paths rather than calling removal complete.',finding:'Expiry evidence is useful when approval, purpose, permission path, grant, expiry, removal, verification time, and residual observations are attributable.',limits:'The study cannot prove absence of cached files, tokens, sessions, alternate identities, undiscovered systems, disclosure, harm, or legal compliance.'},
];

const make=(s:Study,index:number):ResearchPost=>({slug:s.slug,title:s.title,excerpt:s.excerpt,published:'2026-09-10',sourceDate:'2026-09-10',cluster:'Legal Operations Evidence',headlineStat:`Research question: ${s.question}`,thumbnail:'/research-thumbnails/research-default.svg',relatedSlugs:studies.filter(x=>x.slug!==s.slug).slice(index%3,index%3+2).map(x=>x.slug),sources,sections:[
 {heading:'Research question and scope',body:`Published September 10, 2026. ${s.question} The unit of analysis is ${s.unit}. This qualitative method examines administrative evidence in a supervised legal-support workflow. It does not decide privilege, legal duty, strategy, matter merit, client rights, or a required outcome.`},
 {heading:'Methodology',body:`${s.method} The comparison uses the nine listed professional, security, privacy, access, and accountability sources. Those sources address different purposes and jurisdictions, so the analysis does not combine them into one legal rule. Source principles, hypothetical observations, and local operating recommendations remain labeled separately.`},
 {heading:'Observation window',body:'The bounded observation window is September 1 through September 7, 2026. Each hypothetical unit is checked only at the review point or points defined in the method, and no event before or after that window is treated as observed. The window is a study-design boundary, not a claim that a live firm, system, or matter was monitored during those dates.'},
 {heading:'Evidence and measurement',body:`For each unit, record its identifier, approved purpose, instruction version, source, actor, event time, observed state, exception, owner, disposition, and correction link. ${s.finding} Any count must show its selection rule, denominator, period, exclusions, and unavailable records.`},
 {heading:'Worked scenario',body:`${s.scenario} The offshore role records what approved systems and sources display, then sends the narrow uncertainty to the named firm owner. It does not infer intent, authority, fault, legal meaning, urgency, or the correct substantive response.`},
 {heading:'Inference boundaries',body:'The observations may support a repeat check, a revised instruction, or an access review within the defined sample. They do not convert a complete administrative record into proof of compliance, security, legal sufficiency, or work quality. Alternative explanations include source condition, system design, access state, task mix, instruction wording, and reviewer availability.'},
 {heading:'Limitations',body:`${s.limits} No client files, production systems, workers, or firms were studied. Hypothetical qualitative cases cannot estimate prevalence, effect size, causation, or future results. Public guidance does not certify LegalServicesOffshore.com or any offshore arrangement. Jurisdiction-specific transfer, confidentiality, privilege, retention, consent, notification, and remediation questions require authorized legal review.`},
 {heading:'Replication protocol',body:'Define the population, selection rule, approved sources, instruction version, state vocabulary, reviewer, and period before checking records. Include ordinary items and known exceptions. Have a second authorized reviewer repeat the observation from the preserved evidence. Start a new comparison when the task, system, source type, permission scope, instruction, or reviewer changes.'},
 {heading:'Bounded conclusion',body:`The narrow finding is: ${s.finding} A supervised offshore worker may preserve approved inputs, observable events, unknowns, and reviewer dispositions. The firm retains interpretation, remediation, legal judgment, authority, and release. The output is a locally reconstructable record, not a general assurance.`},
]});

export const september10ResearchPosts=studies.map(make);
