import type {ResearchPost} from '../fleet-data';

const sources=[
 {name:'ABA Formal Opinion 477R',url:'https://www.americanbar.org/content/dam/aba/administrative/professional_responsibility/formal-opinions/477r.pdf'},
 {name:'ABA Formal Opinion 498',url:'https://www.americanbar.org/content/dam/aba/administrative/professional_responsibility/aba-formal-opinion-498.pdf'},
 {name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'},
 {name:'NIST SP 800-53 Revision 5',url:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'},
 {name:'CISA Identity and Access Management',url:'https://www.cisa.gov/topics/cyber-threats-and-advisories/identity-and-access-management'},
 {name:'ICO Data Protection by Design and Default',url:'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/accountability-and-governance/guide-to-accountability-and-governance/data-protection-by-design-and-by-default/'},
 {name:'Law Society Outsourcing Guidance',url:'https://www.lawsociety.org.uk/topics/business-management/outsourcing'},
 {name:'OWASP Logging Cheat Sheet',url:'https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html'},
] as const;

type Study={slug:string;title:string;excerpt:string;question:string;unit:string;method:string;scenario:string;finding:string;limit:string};
const studies:readonly Study[]=[
 {slug:'offshore-legal-support-evidence-link-decay-study',title:'When evidence links decay in offshore legal support records',excerpt:'A bounded study of moved files, expired links, renamed folders, and the metadata that helps an authorized reviewer recover context.',question:'Which recorded fields make a legal-support evidence reference reconstructable after its original link stops working?',unit:'one approved evidence reference from creation through later reviewer access, including source system, stable identifier, visible path, access date, change event, and disposition',method:'Compare six hypothetical references: two unchanged links, one moved file, one renamed folder, one expired share, and one record removed under instruction. Remove one recovery field at a time and note what remains reproducible.',scenario:'A matter folder is renamed after an index is prepared. The original link fails, but the record retains the platform, document identifier, earlier path, and access date for the system owner to trace.',finding:'A link is stronger evidence when paired with a stable identifier, source system, observation date, and recorded change history.',limit:'Recoverability does not prove authenticity, completeness, authorization, preservation compliance, or the legal significance of a source.'},
 {slug:'law-firm-offshore-reviewer-reassignment-continuity-research',title:'Reviewer reassignment and continuity in offshore legal support',excerpt:'Research on whether source links, open questions, and decision histories let a newly assigned firm reviewer resume work safely.',question:'What minimum handoff record helps a successor reviewer continue a supervised support task without relying on private memory?',unit:'one work item reassigned between authorized reviewers after preparation but before final disposition',method:'Construct five hypothetical reassignments with a common task. Vary the presence of the instruction version, source links, last completed action, open question, prior reviewer note, and next permitted step.',scenario:'A lawyer becomes unavailable after requesting a correction. The successor sees the original source, the exact request, the corrected draft, and the still-unresolved release decision.',finding:'Continuity improves when the handoff preserves the source, instruction, action history, unresolved question, and authority boundary together.',limit:'A complete handoff cannot establish that a successor has appropriate expertise, authority, capacity, conflicts clearance, or enough context to decide the matter.'},
 {slug:'offshore-legal-support-exception-denominator-method-study',title:'Why exception counts need denominators in legal support reviews',excerpt:'A qualitative method study separating raw exception totals from the population, sampling rule, and opportunity for each check.',question:'How does the stated denominator change the interpretation of exception counts in a supervised legal-support workflow?',unit:'one defined administrative check applied to an explicitly selected population during a fixed review period',method:'Compare eight hypothetical review summaries that share the same exception count but vary total population, eligible population, sample rule, duplicate handling, and unavailable records.',scenario:'Five missing-source flags appear in 20 sampled records. Another report also shows five flags, but across 500 eligible records with only 20 selected; the same count supports a different and still limited observation.',finding:'An exception count is locally interpretable only when the eligible population, inspected set, selection rule, exclusions, and check definition remain visible.',limit:'Small descriptive samples cannot establish causation, worker quality, future rates, materiality, legal risk, or comparisons across different tasks.'},
 {slug:'law-firm-offshore-instruction-version-drift-research',title:'Instruction-version drift in law firm offshore workflows',excerpt:'A study of how old templates, saved messages, and local copies can pull recurring work away from the current approved instruction.',question:'Which evidence distinguishes use of an outdated instruction from ambiguity in the current workflow?',unit:'one recurring task completed against a named instruction, template, source set, and reviewer decision',method:'Build six hypothetical tasks across three instruction versions. Compare the version cited at assignment, the file opened, the fields completed, the reviewer response, and the later corrective action.',scenario:'A worker follows a saved checklist that lacks a newly required source-date field. The record links the old checklist and the current assignment message instead of attributing the omission to carelessness.',finding:'Version drift is easier to diagnose when assignment, opened artifact, effective instruction, and correction remain separate attributable events.',limit:'The record cannot determine intent, competence, fault, legal sufficiency, or whether a particular instruction should have been adopted.'},
 {slug:'offshore-legal-support-access-removal-evidence-study',title:'What proves access removal in an offshore legal support closeout?',excerpt:'Research comparing requests, system events, effective capability checks, and reviewer sign-off at the end of an assignment.',question:'What bounded evidence can support a local statement that assigned access was removed without claiming universal absence of access?',unit:'one named identity and one approved system entitlement from removal instruction through system-owner verification',method:'Compare five hypothetical closeouts: confirmed removal, queued request, disabled account with active session, group removal with direct permission, and unavailable verification. Record only approved observations.',scenario:'An account is disabled, but a system-owner report shows a direct shared-folder permission. The closeout remains open and routes the residual entitlement without testing client content.',finding:'Removal evidence is strongest when it joins the instruction, attributable system event, entitlement scope, verification time, exception check, and authorized owner disposition.',limit:'A local check cannot prove absence of every credential, cached copy, session, export, alternate identity, disclosure, or access path.'},
];

const make=(s:Study,index:number):ResearchPost=>({slug:s.slug,title:s.title,excerpt:s.excerpt,published:'2026-09-08',sourceDate:'2026-09-08',cluster:'Legal Operations Evidence',headlineStat:`Research question: ${s.question}`,thumbnail:'/research-thumbnails/research-default.svg',relatedSlugs:studies.filter(x=>x.slug!==s.slug).slice(index%3,index%3+2).map(x=>x.slug),sources,sections:[
 {heading:'Research question and scope',body:`Published September 8, 2026. ${s.question} The unit of analysis is ${s.unit}. This report examines administrative evidence in a supervised legal-support workflow. It does not decide privilege, legal duties, strategy, client rights, or the merits of a matter.`},
 {heading:'Methodology',body:`${s.method} The documentary comparison uses the eight listed sources for principles concerning supervision, protected information, access, attributable events, and review. They arise from different jurisdictions and control settings, so the analysis does not combine them into a single legal rule. Source guidance, hypothetical observations, and local recommendations are kept separate.`},
 {heading:'Evidence fields and measurement',body:`For every unit, record its identifier, approved source, instruction version, actor, event time, observed state, exception, next owner, reviewer response, and correction link. ${s.finding} Excluded and unavailable records stay visible so a clean subset is not mistaken for the whole population.`},
 {heading:'Worked scenario',body:`${s.scenario} The offshore support role preserves what approved systems show and routes one precise uncertainty. It does not infer intent, authority, legal meaning, fault, or the proper substantive outcome.`},
 {heading:'Interpretation and inference limits',body:`The evidence may show whether the sampled workflow used traceable sources, current instructions, attributable actions, explicit unknowns, and documented owner decisions. It may justify another bounded check. It cannot turn an orderly record into a certification, and alternative explanations such as source quality, access design, instruction clarity, or reviewer availability must remain visible.`},
 {heading:'Limitations',body:`${s.limit} Public guidance does not certify LegalServicesOffshore.com, an offshore staffing arrangement, or a firm's implementation. This hypothetical qualitative method cannot resolve jurisdiction-specific professional duties, cross-border transfer requirements, privilege, retention, client consent, notification, or remediation. No private client files were used, and the sample cannot estimate real-world frequency, effect size, or causation.`},
 {heading:'Practical replication',body:`Define the population, selection rule, state vocabulary, permitted sources, and review period before looking at outcomes. Include ordinary items and known exceptions. Ask whether a second authorized reviewer can reproduce the observation and identify what remained unknown. Start a new comparison if the task, system, instruction, access scope, or reviewer changes.`},
 {heading:'Bounded conclusion',body:`The analysis supports one narrow conclusion: ${s.finding} A supervised offshore worker can preserve approved inputs, observable actions, uncertainty, and reviewer evidence. The firm retains interpretation, remediation, authority, and release. The useful output is a locally reconstructable record, not a broad claim about compliance, safety, quality, or legal effect.`},
]});

export const september8ResearchPosts=studies.map(make);
