import type { ResearchPost } from '../fleet-data';

const sources = [
  { name: 'ABA Formal Opinion 477R', url: 'https://www.americanbar.org/content/dam/aba/administrative/professional_responsibility/formal-opinions/477r.pdf' },
  { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework' },
  { name: 'NIST SP 800-207 Zero Trust Architecture', url: 'https://csrc.nist.gov/pubs/sp/800/207/final' },
  { name: 'ICO Data Protection by Design and Default', url: 'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/accountability-and-governance/guide-to-accountability-and-governance/data-protection-by-design-and-by-default/' },
  { name: 'OWASP Logging Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html' },
  { name: 'Law Society Outsourcing Guidance', url: 'https://www.lawsociety.org.uk/topics/business-management/outsourcing' },
];

const supplements: Record<string, string> = {
  'offshore-legal-intake-source-provenance-study': 'The review should also distinguish a missing source from a source that was never requested. That distinction affects training and queue design. A worker who follows an incomplete instruction may have performed the task correctly while still producing a record that cannot be accepted. The firm owner can decide whether to request the missing material, narrow the intake, or close the item with a documented reason. The result should not be scored as a clean intake merely because every visible field contains text. This is especially important when support is measured by throughput. A count of completed forms can conceal unresolved identity, urgency, or authority questions. Source provenance gives the reviewer a second measure: whether the record can be trusted for the next decision without asking the worker to supply legal meaning.',
  'law-firm-offshore-document-version-lineage-research': 'Lineage evidence is also useful when a document returns for rework. The returned file should keep its prior identifier, the reviewer instruction, and the reason for the new comparison. A worker may record that a requested change appears in the new file, but should not infer that all requested changes were made or that the reviewer accepted them. The firm can sample returned items to see whether the same file is being sent back repeatedly, whether instructions identify a source version, and whether corrections preserve history. Those observations can improve the workflow without turning an offshore support worker into a document approver. A visible rework state is more informative than repeatedly renaming a file until it appears final.',
  'offshore-legal-support-deadline-timezone-evidence-study': 'The record should also distinguish a time conversion from a deadline calculation. A conversion changes how the same instant is displayed. A deadline calculation may depend on service, business days, court rules, extensions, or facts that are not present in the source. A worker can document the first when the firm supplies the rule and system. The second belongs with the authorized reviewer. A sample should test both so training does not blur them. Managers can then see whether a queue is waiting for a technical entry or a legal decision. That distinction reduces silent assumptions and gives the offshore role a clear way to pause without abandoning the operational handoff. The review should record whether the source used a date only, a date and time, or an interval described in ordinary language. It should say whether the worker preserved the source wording, whether a system changed the display, and whether a reviewer supplied the zone or rule. Those details allow a later reader to separate a harmless display difference from a disputed legal event. They also support safer training examples. A worker can learn to recognize a missing zone, an inconsistent timestamp, or a copied calendar value without learning to resolve the underlying legal question. If a firm later changes its calendar system, the old evidence should remain available so the reviewer can understand why the display differs. The handoff should capture the system version or location when that detail is available, but it should not collect unrelated matter data merely to make the record look complete.',
  'legal-support-access-recertification-entitlement-research': 'A useful recertification record can include a "not tested" field. It should state whether inherited groups, external sharing, API tokens, downloads, and unrelated matter areas were outside the approved observation. That field keeps a limited check from being read as a complete audit. It also protects the support worker from being asked to probe beyond scope. The firm can expand a later review through a separate instruction and owner. Until then, the record should report the observed state and its limits. This is a practical control for legal support because access to a system can expose more than the assigned task requires, even when the displayed role name sounds narrow.',
  'offshore-legal-research-authority-currency-study': 'The same discipline applies to research notes that cite secondary summaries. A support worker can record that a summary points to a source and whether the source was retrieved, but should not treat the summary as a substitute for the authority the attorney requested. If the source is unavailable, the record should say so and preserve the retrieval boundary. An owner may choose another source or accept the limitation. The support role can make that choice visible without making it. A small review sample should therefore test direct sources, summaries, archived pages, and jurisdiction mismatches. The outcome is evidence about the research packet, not a conclusion about the law.'
};

export const august20ResearchPosts: readonly ResearchPost[] = [
  {
    slug: 'offshore-legal-intake-source-provenance-study',
    title: 'Offshore legal intake source provenance: which facts are ready for review?',
    excerpt: 'A research study of source-linked intake preparation for supervised legal support teams.',
    published: '2026-08-20', sourceDate: '2026-08-20', cluster: 'Workflow Design',
    headlineStat: 'A six-source study of intake facts, uncertainty, and reviewer ownership.',
    relatedSlugs: ['legal-intake-duplicate-party-review', 'legal-support-matter-status-evidence'], thumbnail: '/research-heroes/aug20-intake-provenance.svg', sources,
    sections: [
      { heading: 'Research question', body: 'When a supervised offshore legal support worker prepares new-matter intake, what evidence makes an individual fact ready for a firm-side review, and what evidence only shows that someone typed it into a form? This distinction matters because intake mixes names, contact details, matter descriptions, requested services, urgency, and documents supplied by a prospective client. The study focuses on a Philippines-based support role that receives approved instructions, compares supplied information, preserves source references, and routes uncertainty. It does not ask the worker to decide whether a firm should accept the matter, whether a conflict exists, whether a claim has merit, or what advice a client should receive. The central unit is the fact-to-source link: what was observed, where it came from, when it was captured, what rule was applied, and who must decide its meaning.' },
      { heading: 'Methodology and evidence scope', body: 'The method compares ABA Formal Opinion 477R, NIST Cybersecurity Framework 2.0, NIST Zero Trust Architecture, ICO data-protection-by-design guidance, OWASP logging guidance, and Law Society outsourcing guidance. These sources serve different jurisdictions and purposes, so the comparison identifies recurring control principles rather than one universal intake rule. I apply those principles to four hypothetical records: a name copied from an email signature, a matter description inferred from an attachment filename, a phone number supplied without country context, and a client request that contains a deadline but no source document. The review separates source-backed observations from operating recommendations. It is qualitative process research, not a study of conversion, response time, accuracy, or legal outcomes.' },
      { heading: 'Findings', body: 'The strongest intake evidence preserves the original value beside the normalized value. A worker may enter a firm-approved spelling while retaining the supplied spelling and the source location. That allows a reviewer to see whether a correction was mechanical or interpretive. The same principle applies to matter type: a selected category can show the worker used a supplied taxonomy, but it cannot prove the legal characterization is right. Least-privilege guidance also changes what good evidence looks like. The record should contain enough context for review without copying an entire email chain or unrelated attachment into a second system. An attributable timestamp, source reference, operator identity, and exception reason often tell a reviewer more than a polished paragraph. Missing evidence should remain a named state, not be filled with a plausible guess.' },
      { heading: 'Niche operating example', body: 'Suppose a prospective client writes that a former employer has sent a demand and asks whether the firm can help. The worker can preserve the message, record the sender and received time, identify that the demand document is not attached, and route the item using the firm\'s approved intake rule. The worker can also flag that the phrase "sent a demand" does not establish service, a deadline, or a legal issue. The worker should not classify the claim, promise a consultation outcome, screen for conflicts beyond supplied criteria, or tell the person that the firm can take the matter. The firm-side reviewer decides what follow-up is appropriate. This example keeps the company\'s niche central: offshore support organizes repeatable intake work while the legal team retains acceptance and judgment.' },
      { heading: 'Limitations', body: 'A source-linked intake field can still be false, stale, incomplete, or misunderstood. A message header does not prove the sender’s identity, and a supplied date does not establish a controlling deadline. Public guidance cannot resolve a particular firm’s conflict process, client agreement, retention rule, or cross-border transfer requirement. The hypothetical records cannot establish a firm’s intake quality or identify the right fields for every practice area. The firm must define permitted systems, required source evidence, escalation owners, retention, and who may communicate externally. Support should not broaden access to investigate a question that belongs with counsel or an authorized intake owner.' },
      { heading: 'Evidence-led conclusion', body: 'The research supports intake preparation when the record distinguishes supplied fact, normalized entry, source, missing evidence, and reviewer decision. A supervised offshore worker can preserve those layers and route a clear exception. The worker should not turn an incomplete description into a legal category, deadline, conflict result, or acceptance decision. For LegalServicesOffshore.com, source provenance is the useful benchmark: a reviewer should be able to reconstruct why a field is present and what it does not prove. A form that looks complete but hides its sources is weaker than a shorter record that makes uncertainty visible.' },
      { heading: 'Review design', body: 'A practical review sample should include ordinary submissions and the records most likely to expose a boundary problem. One sample can test a clean contact field, a normalized organization name, and a matter description copied from an approved message. Another can test an absent attachment, an unclear deadline phrase, or a request that asks for legal advice. The reviewer should mark each field as source-linked, mechanically normalized, incomplete, or requiring judgment. That vocabulary prevents a worker from being judged against a conclusion they were never authorized to make. It also gives the firm a way to revise the role brief. If the same missing source appears repeatedly, the intake instruction may need a new required field. If workers repeatedly escalate a routine mechanical issue, the firm can provide a clearer example. The worker can prepare the comparison, but the firm decides whether to change the form, access, training, or review threshold. Any change should retain the old rule and its effective date so a later reader can understand why records were handled differently. For cross-border support, the review should also check that the worker has not copied unnecessary matter information into an informal tracker. Evidence quality includes restraint: the record should be sufficient for the decision and no broader.' },
    ],
  },
  {
    slug: 'law-firm-offshore-document-version-lineage-research',
    title: 'Law-firm offshore document version lineage: can support prove which draft was reviewed?',
    excerpt: 'Research on document lineage, version comparison, and review boundaries in offshore legal support.',
    published: '2026-08-20', sourceDate: '2026-08-20', cluster: 'Workflow Design',
    headlineStat: 'A version-lineage study that separates file identity from legal approval.',
    relatedSlugs: ['legal-document-version-control', 'legal-support-handoff-reliability-research'], thumbnail: '/research-heroes/aug20-version-lineage.svg', sources,
    sections: [
      { heading: 'Research question', body: 'Can an offshore legal support role establish which document version entered a review queue without implying that the document was legally approved? Legal teams often exchange drafts through email, shared drives, portals, and matter-management systems. A filename may stay constant while the contents change, or a copied document may lose the relationship to the instruction that created it. This study examines a narrow support task: preserve file identity, compare supplied metadata, record a mechanical difference, and hand the result to an authorized reviewer. It excludes redline judgment, privilege decisions, substantive approval, filing decisions, and client advice. The research question is therefore about lineage, not correctness: can another reviewer trace the file, instruction, transformation, and review state without treating a clean version number as proof of legal sufficiency?' },
      { heading: 'Methodology and evidence scope', body: 'I compare the six named authorities above with four hypothetical version events: a draft uploaded after an email instruction, a PDF exported from a word-processing file, a duplicate with the same filename, and a revised document whose prior version is no longer visible in the working folder. The method records source path, file name, version label, timestamp, actor, checksum or system identifier when available, supplied instruction, observed change, and unresolved question. The analysis separates facts about document handling from recommendations about review control. It does not measure turnaround, error rates, document quality, or filing outcomes. The evidence scope is limited to approved systems and the minimum content needed to establish lineage.' },
      { heading: 'What lineage evidence can show', body: 'A source path and system identifier can show where a file was observed. A timestamp and account can show when an action was recorded. A comparison can show that text or metadata differs between two available versions. None of those facts proves that the later draft is approved, that the comparison captured every meaningful change, or that the document is ready for a client or court. OWASP logging guidance makes attribution and event context useful, while access guidance supports limiting the comparison workspace to the assigned matter. The practical boundary is simple: support can report "version B differs from version A at these locations" when the tools make that comparison reproducible. The reviewer decides whether the difference matters.' },
      { heading: 'Operating example', body: 'A firm sends a support worker an instruction to prepare a draft agreement for attorney review. The worker receives a file called "agreement-final," then finds an earlier file with the same name in a separate approved folder. The worker may preserve both identifiers, note their locations and timestamps, compare the available text, and flag that the instruction does not identify a controlling version. The worker should not delete the earlier copy, rename one "approved," merge changes, decide which clause is acceptable, or upload a client-facing copy. The designated attorney or manager decides which source governs and whether the draft can move forward. The evidence is the lineage packet, not the legal answer.' },
      { heading: 'Limitations', body: 'File metadata can be altered, copied, stripped during export, or inherited from another system. A checksum can show equality or difference but cannot explain why a change was made. A version history may omit downloads, local edits, or a document sent outside the system. The cited guidance does not specify a universal naming rule or determine whether a draft satisfies a matter-specific instruction. The examples are hypothetical and cannot establish completeness. Firms must set retention, access, approved comparison tools, source precedence, and review ownership. Support should preserve an ambiguity rather than use a filename or newest timestamp as a substitute for authorization.' },
      { heading: 'Evidence-led conclusion', body: 'The research supports version-lineage preparation when file identity, source instruction, observed change, and review state remain separate. A supervised offshore worker can build a traceable comparison and route gaps. The worker should not certify a draft, destroy a prior version, or convert "latest" into "approved." For LegalServicesOffshore.com, the useful result is a handoff that lets a firm owner answer four questions: which files were examined, what changed, what was outside scope, and who accepted the next state. That is stronger than a final-looking filename with no history.' },
      { heading: 'Review design', body: 'A lineage review works best when the firm chooses the comparison boundary before the worker opens the files. The instruction should identify the matter, approved folder or system, expected document type, permitted comparison method, and reviewer who resolves conflicts. The worker can record the file identifiers, compare the supplied versions, and list changes in neutral language. The worker should also record what was not available, such as a local copy, an earlier attachment, or a prior redline. A reviewer can then distinguish a missing source from a clean comparison. Sampling should include a document with one obvious metadata change, a document exported to another format, and a duplicate filename. These cases test whether the evidence survives ordinary handoffs rather than only ideal examples. If a reviewer corrects a version label, the correction should add a decision record instead of overwriting the initial observation. That history protects the process from hindsight. It also keeps the offshore role narrow. The worker is responsible for careful handling and clear reporting; the attorney or firm owner remains responsible for deciding which draft governs, whether a clause is acceptable, and whether a document may be sent or filed. A lineage control is successful when it makes those responsibilities easier to see.' },
    ],
  },
  {
    slug: 'offshore-legal-support-deadline-timezone-evidence-study',
    title: 'Offshore legal support and deadline time zones: what can a date reconciliation record prove?',
    excerpt: 'A bounded study of time-zone evidence, source conflicts, and the line before deadline judgment.',
    published: '2026-08-20', sourceDate: '2026-08-20', cluster: 'Scope Benchmarks',
    headlineStat: 'A time-context study for supervised calendar and notice administration.',
    relatedSlugs: ['legal-support-deadline-source-reconciliation', 'legal-deadline-escalation-matrix'], thumbnail: '/research-heroes/aug20-timezone-evidence.svg', sources,
    sections: [
      { heading: 'Research question', body: 'What can a legal support date-reconciliation record establish when a notice, email, calendar, or task system displays different time zones? The question is practical for an offshore team because a worker in the Philippines may operate systems used by a firm, court, or client in another jurisdiction. Time conversion is a technical action, but choosing a controlling date or deciding that a deadline is protected can be legal judgment. This research examines whether support can preserve the original expression, identify the displayed conversion, record conflicts, and route a review question. It does not determine service, filing periods, extensions, urgency, or client obligations. The desired output is a factual comparison that makes the transformation visible instead of hiding it in a calendar entry.' },
      { heading: 'Methodology and evidence scope', body: 'The study compares ABA Formal Opinion 477R, NIST Cybersecurity Framework 2.0, NIST Zero Trust Architecture, ICO design guidance, OWASP logging guidance, and Law Society outsourcing guidance. I test four hypothetical records: a firm instruction with an explicit zone, a court notice with a date but no zone, an email whose sender and calendar use different zones, and two sources with conflicting dates. For each, the method records original wording, source location, received time, displayed time, time-zone label, mechanical conversion, operator, and escalation state. The study is qualitative and addresses evidence design. It makes no claim about deadline accuracy, legal effect, or performance across firms.' },
      { heading: 'Findings', body: 'A conversion should add context, not erase it. A record is more reviewable when it retains the source\'s exact date and time, identifies the zone as written, states the system\'s displayed zone, and marks whether the conversion was mechanical or supplied by an owner. If the zone is missing, "unknown" is more accurate than a guessed default. Logging principles support preserving the event and actor, while least-privilege principles caution against browsing unrelated matter records to resolve the question. A task can be flagged as requiring review without being labeled legally urgent. The distinction matters because a neat calendar entry can create false confidence when its source, transformation, or reviewer is invisible.' },
      { heading: 'Niche operating example', body: 'A firm instruction says to place a client meeting on September 4 at 10:00 a.m. Eastern. The worker can enter the event using the approved system, retain the instruction reference, and verify how the calendar displays the zone. If a court notice says only "September 4," the worker can preserve that wording, record the missing zone, and route the question. If two sources disagree, the worker can list both without selecting the controlling date. The worker should not calculate a response period, infer service, choose the newest source, or tell a client that a deadline is safe. A firm-side reviewer decides the legal significance.' },
      { heading: 'Limitations', body: 'A calendar display cannot establish valid service, a controlling deadline, notice sufficiency, or the legal effect of an extension. Systems may convert times differently, clocks may drift, and a document may use a local convention that is not obvious from its text. Public security and professional guidance do not resolve a particular court rule, engagement, or client instruction. The hypothetical cases cannot establish a firm’s date accuracy. Firms must define approved sources, time-zone handling, retention, correction history, and escalation ownership. Support should preserve the ambiguity and stop at the stated boundary.' },
      { heading: 'Evidence-led conclusion', body: 'The evidence supports date reconciliation as a bounded administrative lane when original wording, time context, conversion, and uncertainty remain visible. A supervised offshore worker can preserve a source and perform an approved mechanical entry. The worker should not choose a controlling date or give deadline advice. For LegalServicesOffshore.com, the benchmark is reconstructability: can the firm owner see what the source said, what the system displayed, what changed, and what still requires judgment? If not, the calendar record is not ready to carry operational meaning.' },
      { heading: 'Review design', body: 'A date review should start with a written source hierarchy supplied by the firm, not with the worker’s preferred calendar or local time zone. The hierarchy may identify which system or document the owner wants compared, but it cannot authorize the worker to decide an unresolved legal conflict. The record should preserve the source expression, the time zone as written, the receiving system’s display, and any mechanical conversion. It should also state whether the worker entered an event, created a review task, or took no action because the source was ambiguous. A sample can include an explicit meeting instruction, a notice lacking a zone, and two sources that disagree. Reviewers should inspect whether the original wording survived and whether the worker avoided adding a default time. If the firm later selects a controlling date, that decision belongs in a separate owner field with its own timestamp. It should not be disguised as a worker correction. This structure helps managers distinguish a technical data-entry defect from a legal question. It also gives an offshore support team a safe stop rule: when the source does not supply the needed fact, record the gap and route it. A calendar can remain useful while its uncertainty stays visible.' },
    ],
  },
  {
    slug: 'legal-support-access-recertification-entitlement-research',
    title: 'Legal support access recertification: does a permission record prove entitlement?',
    excerpt: 'Research separating observed system capability from authorization in supervised offshore legal support.',
    published: '2026-08-20', sourceDate: '2026-08-20', cluster: 'Hiring Controls',
    headlineStat: 'A six-source study of access observations, approval evidence, and escalation.',
    relatedSlugs: ['legal-support-access-recertification-evidence', 'legal-access-deprovisioning-workflow'], thumbnail: '/research-heroes/aug20-access-entitlement.svg', sources,
    sections: [
      { heading: 'Research question', body: 'Does an access recertification record prove that a legal-support account is entitled to use a system, or does it only show what the account could do when someone looked? That distinction is important for law firms using supervised offshore support. A worker may be asked to compare an account with a role brief, but capability, business purpose, client authorization, and current approval are different facts. The study considers a narrow administrative contribution: record the observed permission, the approved review boundary, the source of authorization, and the unresolved gap. It excludes granting, revoking, or expanding access; deciding whether a client agreement permits the access; investigating unrelated matter content; and labeling a capability as a breach.' },
      { heading: 'Methodology and evidence scope', body: 'The method compares ABA Formal Opinion 477R, NIST Cybersecurity Framework 2.0, NIST SP 800-207, ICO design guidance, OWASP logging guidance, and Law Society outsourcing guidance. Four hypothetical observations are tested: an account matching its role, a role with broader search than expected, a former queue assignment that remains active, and an approval record with no owner or expiry. The record includes account, system, group, effective capability observed within scope, approval reference, review date, operator, and disposition owner. This is qualitative research about evidence design, not an access audit or compliance certification. It does not establish whether data was viewed, downloaded, or disclosed.' },
      { heading: 'Findings', body: 'Observed capability is evidence about system state, not proof of authorization. A role label such as "intake assistant" may hide cross-matter search, download, sharing, or inherited permissions. A useful record therefore names what was tested and what was not tested. Zero-trust guidance supports checking the actual request and resource instead of trusting a broad label. Logging guidance supports attribution and event context. Confidentiality guidance supports limiting the review to the approved account and workspace. The offshore support role can report that a permission was visible, compare it with supplied criteria, and route a discrepancy. The organization that owns the matter decides whether the permission is acceptable, should be narrowed, or needs investigation.' },
      { heading: 'Operating example', body: 'Imagine an account described as "intake assistant" that can search a workspace containing unrelated matters. The worker may record the displayed group, observed search scope, review instruction, and observation time. The worker should not browse unrelated files to prove the point, copy client content into a ticket, or remove the access without authorization. If a former queue assignment remains active, the worker can preserve the account and approval references and route the stale-assignment question. A firm owner may request technical review or confirm a documented exception. The evidence distinguishes capability, intended purpose, and disposition without forcing the support role to make an authorization decision.' },
      { heading: 'Limitations', body: 'A permission screen may omit inherited groups, APIs, devices, temporary grants, or external sharing. An approval record may be stale, incomplete, or stored separately from the system state. The cited sources do not decide whether a permission violates a client contract, professional duty, privacy law, or incident threshold. The examples are hypothetical and cannot establish a firm’s access posture. Each firm must define test scope, evidence handling, deprovisioning authority, retention, and escalation timing. Support should not probe beyond the instruction or infer misuse from capability alone.' },
      { heading: 'Evidence-led conclusion', body: 'The research supports recertification preparation when observed capability, intended purpose, approval evidence, and disposition are recorded separately. A supervised offshore worker can prepare that comparison and flag gaps. The worker should not grant or revoke access, decide entitlement, investigate unrelated content, or call an observation a breach. For LegalServicesOffshore.com, the useful result is a role boundary and a review pattern: state what the account could do, what approval was supplied, what was outside scope, and who decided the next step. A binary "certified" label is weaker when its evidence boundary is hidden.' },
      { heading: 'Review design', body: 'The review boundary should be explicit before any account is inspected. The firm should name the account or cohort, system, role brief, approved evidence source, observation window, and owner of the disposition. The worker can compare the supplied role with the displayed capability and record a gap without opening unrelated matter content. A useful sample includes a normal account, a recent role change, an expired assignment, and a permission inherited from a group. These cases test whether the record distinguishes ordinary state from an exception. The reviewer should ask whether the observation proves capability only, or also has an approved purpose and current authorization. Usually it proves only the first. If the system changes during the review, the worker should preserve both observations with their timestamps. That prevents a later permission change from making the initial state disappear. The firm owner can then confirm, narrow, or escalate the access. The same evidence may support technical remediation or an incident review, but the support worker should not choose that path based on capability alone. A well-scoped recertification task is therefore less about producing a green status and more about showing the limits of the observation. That is a useful hiring and workflow signal for LegalServicesOffshore.com: the role requires disciplined evidence handling, not independent authority over client systems.' },
    ],
  },
  {
    slug: 'offshore-legal-research-authority-currency-study',
    title: 'Offshore legal research support and authority currency: how should stale sources be surfaced?',
    excerpt: 'A research study of source currency checks for supervised legal research administration.',
    published: '2026-08-20', sourceDate: '2026-08-20', cluster: 'Scope Benchmarks',
    headlineStat: 'A source-currency study that keeps retrieval separate from legal interpretation.',
    relatedSlugs: ['legal-research-authority-currency', 'law-firm-knowledge-base-source-expiry'], thumbnail: '/research-heroes/aug20-authority-currency.svg', sources,
    sections: [
      { heading: 'Research question', body: 'How can offshore legal research support surface a potentially stale authority without deciding what the authority means or whether it governs a matter? Research administration often includes retrieving a supplied citation, checking a source date, recording a later version, and organizing materials for an attorney. The risk begins when a broken link, changed text, or newer publication is silently converted into a statement that the law changed. This study focuses on a supervised role that preserves the requested source, compares public versions using an approved method, records the observed difference, and escalates. It does not authorize the worker to interpret precedent, determine current law, select controlling authority, or advise a client.' },
      { heading: 'Methodology and evidence scope', body: 'I compare ABA Formal Opinion 477R, NIST Cybersecurity Framework 2.0, NIST Zero Trust Architecture, ICO design guidance, OWASP logging guidance, and Law Society outsourcing guidance with four hypothetical research records: an intact citation with an old review date, a broken link, a replaced agency page, and a later version whose scope is unclear. The method records title, issuing body, URL, access date, version or publication date, requested proposition, observed difference, retrieval limit, and reviewer question. Sources with different jurisdictions and purposes are treated as control guidance, not legal authorities for a client matter. The method is qualitative and does not estimate research accuracy or legal outcomes.' },
      { heading: 'Findings', body: 'Currency is not the same as legal relevance. An intact link may lead to a revised page, while a newer document may not apply to the question the attorney asked. A support record should therefore distinguish source identity, retrieval result, visible change, and interpretation. A broken link can be reported as a retrieval failure. A changed heading can be recorded as an observed difference. Neither fact proves that a rule changed, was repealed, or governs the matter. Version history and access controls also matter: preserve the retrieved source under the firm’s rules, identify who requested the check, and avoid copying more confidential matter detail than the research task requires.' },
      { heading: 'Niche operating example', body: 'An attorney asks support to retrieve a cited regulator page and confirm whether the page still displays the publication referenced in a research note. The worker can use the approved source, record the access date, preserve the cited text or document reference under the firm’s rules, and note that the current page differs from the note. The worker should not write that the authority is no longer good law, replace the citation in a client memo, or explain the effect of the change. The attorney decides whether the difference matters. If the page cannot be retrieved, the worker reports that limitation instead of substituting a search result that merely looks similar.' },
      { heading: 'Limitations', body: 'Public pages can change without a clear history, links can fail temporarily, and a source can remain current while its application depends on jurisdiction, date, posture, or facts. Retrieval evidence does not prove completeness, authenticity, or legal effect. The cited guidance cannot resolve a matter-specific research question or professional duty. The hypothetical records cannot establish a firm’s source library quality. Firms must define approved databases, capture rules, review owners, retention, and escalation for uncertainty. Support should preserve the source boundary and leave interpretation to the designated legal reviewer.' },
      { heading: 'Evidence-led conclusion', body: 'The research supports authority-currency administration when retrieval, version observation, source limits, and legal interpretation are separate states. A supervised offshore worker can find a supplied source, record what was visible, preserve a reference, and route a difference. The worker should not decide that law changed, select replacement authority, or give advice. For LegalServicesOffshore.com, source currency is a review input rather than a conclusion. A firm owner should be able to see the requested citation, the retrieval method, the date checked, the observed gap, and the question still waiting for judgment.' },
      { heading: 'Review design', body: 'A source-currency queue should record the request before the retrieval begins. The request should identify the citation, proposition or passage being checked, permitted source locations, access boundary, and legal reviewer. The support worker can then report whether the requested source was found, whether the page or document shows a publication or revision date, and whether the visible text differs from the research note. A sample should include an intact source, a broken link, a revised public page, and a source that is available but outside the requested jurisdiction. Reviewers can use those cases to test whether workers report retrieval facts without making legal claims. A broken link should not become a replacement citation merely because a search result has similar words. A revised page should not be described as a change in law unless the authorized reviewer reaches that conclusion. When a source is archived, the record should identify the archive or repository and the limits of what it proves. If a research note is updated, the old citation and the reason for the update should remain available under the firm’s retention rules. This approach keeps source administration useful for attorneys while giving the offshore role an honest stop condition. The worker can find, preserve, compare, and route. The legal team decides relevance, authority, currency for the matter, and advice.' },
    ],
  },
].map(post => ({ ...post, sections: [...post.sections, { heading: 'Additional evidence note', body: supplements[post.slug] }] }));
