import type {ResearchPost} from '../fleet-data';

const sources = [
  {name:'Formal Opinion 08-451: Lawyer\'s Obligations When Outsourcing Legal and Nonlegal Support Services, American Bar Association',url:'https://www.americanbar.org/content/dam/aba/publications/YourABA/201106_08451.authcheckdam.pdf'},
  {name:'Model Rule 5.3: Responsibilities Regarding Nonlawyer Assistance, American Bar Association',url:'https://www.americanbar.org/groups/professional_responsibility/publications/model_rules_of_professional_conduct/rule_5_3_responsibilities_regarding_nonlawyer_assistant/'},
  {name:'Formal Opinion 506: Responsibilities Regarding Nonlawyer Assistants, American Bar Association',url:'https://www.americanbar.org/groups/professional_responsibility/committees_commissions/ethicsandprofessionalresponsibility/'},
  {name:'Cybersecurity Framework 2.0, National Institute of Standards and Technology',url:'https://www.nist.gov/publications/nist-cybersecurity-framework-csf-20'},
  {name:'Privacy Framework, National Institute of Standards and Technology',url:'https://www.nist.gov/privacy-framework'},
  {name:'Identity and Access Management, Cybersecurity and Infrastructure Security Agency',url:'https://www.cisa.gov/topics/cyber-threats-and-advisories/identity-and-access-management'},
  {name:'Accountability Framework, UK Information Commissioner\'s Office',url:'https://ico.org.uk/for-organisations/advice-and-services/accountability-framework/'},
  {name:'Standards for Internal Control in the Federal Government, U.S. Government Accountability Office',url:'https://www.gao.gov/products/gao-14-704g'},
] as const;

type Study = {
  slug:string; title:string; excerpt:string; cluster:string; question:string; decision:string;
  unit:string; population:string; protocol:string; measures:string; scenario:string;
  finding:string; alternative:string; limitation:string; service:{slug:string;label:string;title:string;body:string};
};

const studies:readonly Study[] = [
  {
    slug:'law-firm-intake-callback-attempt-outcome-study',
    title:'Law firm intake callback attempts: what the outcome record can actually show',
    excerpt:'A bounded research design for distinguishing callback effort, contact, qualification, booking, and attorney-owned acceptance decisions.',
    cluster:'Legal Client Intake',
    question:'Which event fields let a law firm evaluate prospective-client callback handling without treating an attempted call as contact or contact as a retained matter?',
    decision:'whether a first offshore intake lane has sufficiently clear scripts, outcome states, and escalation ownership to begin a supervised pilot',
    unit:'one firm-authorized callback attempt connected to one prospective-client inquiry and one current intake instruction',
    population:'twenty-four synthetic inquiry records distributed across unanswered calls, wrong numbers, requested call-backs, completed factual intake, out-of-scope inquiries, conflict-review holds, and urgent-message escalations',
    protocol:'Assign each synthetic inquiry a source timestamp, approved contact window, script version, permitted fields, and named firm owner. Have a support operator record only the channel event and words supplied by the prospect. A second reviewer then classifies whether the record proves an attempt, two-way contact, a booked consultation, a pending firm decision, or no authorized next step.',
    measures:'attempt timestamp, channel, destination used, displayed connection result, script version, prospect-requested next step, facts collected, urgency flag, conflict-review state, attorney handoff time, and reviewer disposition',
    scenario:'An operator calls the number on a web inquiry. Voicemail answers, but the mailbox is full. The record supports an attempted call to the supplied number at that time. It does not support contact, refusal, lost interest, a completed follow-up, or permission to try an unapproved channel.',
    finding:'A useful callback record separates effort, connection, conversation, booking, qualification review, and engagement. Combining them into one “contacted” status hides both service gaps and professional decision boundaries.',
    alternative:'A low connection rate could reflect invalid contact details, the approved calling window, caller identification, channel preference, or the age and source of the inquiry. It does not by itself establish weak operator performance or weak demand.',
    limitation:'Synthetic cases cannot estimate a real firm\'s conversion rate, prove compliance with solicitation or communications rules, establish the validity of consent, or predict whether a prospect becomes a client.',
    service:{slug:'customer-support',label:'Plan an intake-support lane',title:'Turn intake follow-up into a supervised first role',body:'Define the script, allowed channels, outcome states, attorney escalation owner, and first-week review sample before callback work begins.'},
  },
  {
    slug:'offshore-legal-appointment-reminder-disposition-research',
    title:'Appointment reminder dispositions for offshore legal intake support',
    excerpt:'Research on the evidence needed to separate delivery attempts, confirmations, rescheduling requests, and sensitive replies.',
    cluster:'Legal Client Intake',
    question:'What should an appointment-reminder record preserve so a law firm can tell what was sent, what the recipient actually did, and what still requires firm action?',
    decision:'whether appointment reminders are narrow and observable enough for offshore support without allowing scheduling administration to drift into advice, promises, or uncontrolled messaging',
    unit:'one approved reminder event for one scheduled consultation, using one authorized template and delivery channel',
    population:'eighteen synthetic appointments covering successful delivery, delivery failure, no response, confirmation, cancellation, requested rescheduling, new factual information, requests for legal advice, and messages indicating urgency',
    protocol:'Create a fixed appointment record and an approved reminder template for each case. Preserve the intended recipient, channel, send time, platform result, reply text, and permitted response. Require the operator to route any change of facts, urgency, advice request, or representation question to the named firm owner rather than resolving it.',
    measures:'appointment identifier, source schedule, authorized template, recipient and channel, send event, platform status, reply event, requested change, sensitivity flag, routed owner, firm instruction, and final administrative disposition',
    scenario:'A text platform displays “delivered,” and the recipient later asks whether missing the consultation will hurt the case. Delivery is observable; receipt by a particular person and understanding are not proven. The question also crosses the reminder lane and must go to the firm.',
    finding:'Reminder administration becomes reviewable when send evidence, platform evidence, recipient response, schedule change, and firm decision remain distinct. A single “confirmed” field is too coarse for common exceptions.',
    alternative:'No reply can arise from channel preference, an obsolete number, timing, device settings, accessibility needs, or a changed appointment. Silence does not prove that the reminder was ignored or understood.',
    limitation:'The study does not determine whether a channel or template is legally permitted, whether a message creates an attorney-client relationship, whether an appointment was attended, or what a lawyer must communicate in a jurisdiction.',
    service:{slug:'customer-support',label:'Scope appointment support',title:'Build a reminder lane around firm-approved messages',body:'Choose the source calendar, message templates, rescheduling boundary, sensitive-reply route, and review cadence for a controlled pilot.'},
  },
  {
    slug:'legal-document-template-field-deviation-study',
    title:'Template field deviations in offshore legal document preparation',
    excerpt:'A field-level study of missing values, conflicting sources, stale template labels, and edits that need firm review.',
    cluster:'Legal Admin Support',
    question:'Which deviations can an offshore legal administrator identify mechanically when preparing a document from a firm-approved template, and which changes must stop for review?',
    decision:'whether a proposed document-preparation lane has a stable template, named sources, explicit field rules, and a safe stop condition for substantive uncertainty',
    unit:'one field in one working copy tied to a named template version, an approved source, and a documented preparation instruction',
    population:'thirty synthetic fields across names, addresses, matter identifiers, dates, repeated captions, optional blocks, calculated labels, signature placeholders, and free-text clauses',
    protocol:'Give operators an approved template, a source packet, and field rules that distinguish copy, format, leave blank, and escalate. Seed missing sources, conflicting spellings, obsolete labels, broken cross-references, optional sections, and apparent clause changes. Compare the working copy and exception log with the source packet at field level.',
    measures:'template identifier and version, field identifier, source location, source value, prepared value, allowed transformation, observed deviation, operator action, reviewer instruction, correction version, and release approval',
    scenario:'The current source lists “Suite 410,” while the template example contains “Suite 401.” The operator may flag the conflict and preserve both sources. The operator should not decide which address is legally effective or silently overwrite a substantive notice field.',
    finding:'A deviation log is most useful when it distinguishes absent input, conflicting input, permitted formatting, template defect, and requested substantive change. The categories direct different questions to different owners.',
    alternative:'A high deviation count can result from a newly introduced template, unusually incomplete source packets, granular field definitions, or deliberate early-stage review. The count alone is not an accuracy or productivity score.',
    limitation:'The method cannot establish legal sufficiency, document enforceability, filing compliance, the meaning of a clause, or whether an apparent source is authoritative. Those decisions remain with the firm.',
    service:{slug:'admin-support',label:'Plan document-preparation support',title:'Start with one approved document type',body:'Choose one template, its source fields, permitted formatting rules, exception owner, and full-review period before expanding the lane.'},
  },
  {
    slug:'law-firm-billing-correction-authorization-chain-study',
    title:'Authorization chains for law firm billing corrections prepared offshore',
    excerpt:'A research method for tracing a billing question from source entry through instruction, correction, review, and invoice release.',
    cluster:'Legal Admin Support',
    question:'What evidence shows that an administrative billing correction followed a firm instruction without implying that the offshore preparer made a billing judgment?',
    decision:'whether billing cleanup can be delegated as evidence-based preparation while write-offs, rate changes, narrative judgment, disputes, and invoice release stay with authorized firm personnel',
    unit:'one proposed change to one billing field, connected to the original entry, stated reason, authorizing instruction, revised draft, and release decision',
    population:'twenty synthetic billing questions covering missing matter codes, duplicate-looking entries, incomplete narratives, date mismatches, arithmetic display differences, rate questions, write-off requests, and client objections',
    protocol:'Freeze each original entry and provide a role matrix defining who may clarify a field, approve a correction, authorize a write-off, change a rate, or release an invoice. Have the operator log the issue and prepare only the change explicitly instructed. A separate reviewer compares the instruction, draft, and released state.',
    measures:'original entry identifier, field and value, source record, issue category, requested decision, authorizing person and role, instruction time, prepared change, reviewer, release state, superseded version, and unresolved objection',
    scenario:'Two entries have similar narratives and equal time. The operator may flag a possible duplicate with links to both originals. Without an authorized instruction, similarity is not permission to delete either entry, combine time, or decide what should be billed.',
    finding:'The reliable unit is not a cleaned invoice but an attributable change chain. Original value, question, authority, instruction, prepared revision, approval, and release need separate states.',
    alternative:'Many billing questions may reflect a new matter setup, timekeeper training, import behavior, a client-specific guideline, or a more exact review process. Counts cannot identify cause without task and source context.',
    limitation:'This study cannot decide whether time is billable, a fee is reasonable, a write-off is appropriate, an invoice complies with a contract, or a client objection has merit. It does not test live financial systems.',
    service:{slug:'admin-support',label:'Scope billing-support work',title:'Keep billing preparation separate from billing authority',body:'Map the source fields, correction roles, protected original, approval gate, and invoice-release owner before assigning cleanup work.'},
  },
  {
    slug:'offshore-legal-qa-first-pass-acceptance-denominator-study',
    title:'First-pass acceptance in offshore legal support QA: define the denominator first',
    excerpt:'A measurement study showing how eligibility rules, returns, partial reviews, and changed instructions alter a familiar QA rate.',
    cluster:'Legal Reporting and QA',
    question:'How should a law firm define first-pass acceptance so a weekly scorecard does not hide exclusions, changed instructions, or items that never reached an authorized review?',
    decision:'whether a QA scorecard gives managers enough context to supervise one repeatable work lane and improve its instructions without turning a local measure into a vendor-wide quality claim',
    unit:'one submitted work item at its first review opportunity under a named instruction version and acceptance checklist',
    population:'forty synthetic work items divided among complete submissions, missing-source holds, operator escalations, reviewer returns, partial reviews, changed instructions, withdrawn matters, and accepted items',
    protocol:'Define eligibility before observing results. Classify whether each item entered review, which checklist and instruction applied, whether review was complete, and why an item was accepted, returned, paused, or excluded. Recalculate the rate under three plausible denominator rules and compare the management story each version creates.',
    measures:'work-lane identifier, submission time, instruction version, checklist version, eligibility state, review start, review completeness, disposition, return reason, correction requirement, resubmission, reviewer, and exclusion rationale',
    scenario:'Ten of forty items are paused because the firm did not supply required sources. Calling the remaining thirty the entire workload raises the displayed acceptance rate and erases an important process constraint. Including all forty as failures would wrongly attribute the source hold to prepared work.',
    finding:'First-pass acceptance is interpretable only with a declared population, eligibility rule, review boundary, instruction version, and disposition taxonomy. The denominator is a management choice that must be visible.',
    alternative:'A falling rate can reflect stricter review, a new task mix, a revised checklist, newly recorded defects, or genuine deterioration. A rising rate can reflect narrower eligibility or unrecorded returns. Direction alone does not identify cause.',
    limitation:'Synthetic rates cannot benchmark an industry, compare workers or providers, prove legal quality, predict future work, or justify employment decisions. The study addresses measurement design, not a universal target.',
    service:{slug:'reporting-and-qa',label:'Design a legal-support scorecard',title:'Make the population and review rule visible',body:'Choose one work lane, define eligibility and return reasons, preserve exclusions, and review samples alongside the weekly rate.'},
  },
];

const make = (study:Study,index:number):ResearchPost => ({
  slug:study.slug,title:study.title,excerpt:study.excerpt,published:'2026-09-18',sourceDate:'2026-09-18',cluster:study.cluster,
  headlineStat:`Research question: ${study.question}`,thumbnail:'/research-thumbnails/research-default.svg',
  relatedSlugs:studies.filter(item=>item.slug!==study.slug).slice(index%3,index%3+2).map(item=>item.slug),sources,
  serviceLink:study.service,
  sections:[
    {heading:'Decision this research supports',body:`Published September 18, 2026. This study supports a narrow buyer decision: ${study.decision}. It does not rank providers or propose that an administrative control can replace a lawyer's professional duties. The practical purpose is to help a law firm ask for observable evidence before it delegates repeat work to a Philippines-based support role. Facts in the source record, actions taken by a support worker, decisions made by an authorized firm reviewer, and later outcomes are treated as separate evidence classes throughout the study.`},
    {heading:'Research question and unit of analysis',body:`The research question is: ${study.question} The unit of analysis is ${study.unit}. Defining the unit before measurement prevents a loose collection of messages, files, or dashboard labels from being mistaken for one comparable event. Each unit begins only when the required source and instruction are available. It ends at the bounded administrative disposition described in the protocol, not when a legal matter, client relationship, or commercial outcome reaches a conclusion.`},
    {heading:'Evidence base and source treatment',body:'The source review uses the eight authorities listed below, checked on September 18, 2026. ABA materials inform supervision, confidentiality, prospective-client intake, and the distinction between nonlawyer assistance and lawyer responsibility. NIST, CISA, ICO, and GAO materials inform governance, access, accountability, reliable records, monitoring, and corrective action. These authorities serve different purposes and jurisdictions. The study does not merge them into a single legal rule, claim they bind every firm, or present general control guidance as jurisdiction-specific advice.'},
    {heading:'Population and selection method',body:`The bounded study population is ${study.population}. Cases are synthetic and purposively selected to test ordinary states and foreseeable exceptions, not to estimate how often those events occur in real firms. Every case receives a stable identifier before review. Selection does not depend on whether the result looks favorable. The population definition, included cases, exclusions, and reason for each exclusion are retained so a reader can distinguish the observed set from a broader workload or market.`},
    {heading:'Methodology',body:`${study.protocol} The method records facts as displayed by the approved source and does not ask an operator to infer intent, legal meaning, privilege, urgency, or the correct substantive outcome. The second review tests whether another authorized person can reconstruct the administrative event from preserved evidence. Agreement can reveal that the record and definitions are usable. Disagreement is retained as a finding about definitions, source condition, or review design rather than silently resolved to improve a score.`},
    {heading:'Observation fields and measurement rules',body:`The minimum observation set is: ${study.measures}. Every field has a defined vocabulary, and unavailable information remains unavailable rather than being recoded as “no.” Timestamps use the source system and record the applicable time zone. Corrections append a new state rather than overwriting the original observation. Counts show their numerator, denominator, observation window, exclusions, and missing records. A status label is evidence only of the recorded state in the named system at the observed time; it is not proof that the underlying event was legally effective or factually complete.`},
    {heading:'Worked exception',body:`${study.scenario} This exception illustrates why a support record should preserve narrow observations and an explicit handoff. The operator can record the source, action, displayed result, and unresolved question. The firm decides the legal or professional consequence, any communication outside the approved script, and the next authorized action. A useful workflow makes that stop visible instead of rewarding the operator for converting uncertainty into an apparently complete record.`},
    {heading:'Finding and operational interpretation',body:`${study.finding} This is an inference from the synthetic comparison, not a measured claim about Legal Services Offshore, a customer, or the wider market. For a pilot, managers can translate the finding into written state definitions, a small exception taxonomy, and a named reviewer. They can then inspect early work item by item. If records cannot be reconstructed, the first response should be to check the source, instruction, access, and review design before attributing the problem to a person.`},
    {heading:'Alternative explanations',body:`${study.alternative} Other plausible explanations include changed instructions, reviewer availability, system behavior, permissions, case mix, missing source data, and inconsistent definitions. The research design therefore avoids causal language. A pattern can justify a question, a targeted sample, or a process correction. It cannot establish why the pattern occurred until competing explanations are examined with additional evidence.`},
    {heading:'Supervision, access, and privacy implications',body:'The firm should define the task boundary, approved systems, least-access role, permitted communications, source-of-truth fields, and escalation owner before work starts. Training should use redacted or synthetic examples when practical. Production access should be limited to what the role needs, reviewed when duties change, and removed when the assignment ends. The evidence record should identify sources without copying more confidential content than the firm requires. Lawyers and authorized firm leaders retain supervision, legal judgment, professional communications, client acceptance, substantive approval, and release decisions.'},
    {heading:'Pilot and replication protocol',body:'A replication starts by freezing the work-lane definition, instruction version, field vocabulary, review checklist, observation window, and selection rule. The firm then chooses a small set containing ordinary work and known exceptions. One operator prepares the administrative record; a second authorized reviewer repeats the checks from the preserved sources. Differences are classified by source, instruction, access, preparation, or review. The firm documents any correction and reruns a new sample after a material change. Results from different work lanes or instruction versions are not pooled without showing those differences.'},
    {heading:'Limitations and uncertainty',body:`${study.limitation} No live client information, customer files, production credentials, employees, or law firms were studied. The synthetic sample cannot estimate prevalence, effect size, causation, cost savings, service quality, or business outcomes. Public sources may be revised and local law, court rules, contracts, insurer requirements, professional rules, and firm policies may require a different design. The checked date shows when sources were reviewed, not a guarantee that a page remains current after publication.`},
    {heading:'Niche-specific conclusion',body:`For a law firm evaluating Philippines-based support, the decision-grade conclusion is narrow: ${study.finding} That finding favors a bounded first lane with approved inputs, explicit states, limited access, a visible stop rule, and an accountable firm reviewer. It does not support delegating legal judgment or treating a dashboard as proof of professional compliance. The next useful step is to test the protocol on synthetic or safely redacted examples, revise ambiguous definitions, and approve the live workflow only when the firm can reproduce what happened and who decided the exception.`},
  ],
});

export const september18ResearchPosts = studies.map(make);
